import type {Locale} from '../i18n';

export const strategyEnglish={
 evBaseline:'EV is in play chips for the player acting at this node, relative to an equal split of the starting pot. It includes this tree’s future investments and average-policy continuation.',
 title:'Strategy Lab',intro:'Study a river decision, inspect the assumptions, then compare actions. These restricted games do not solve every poker situation.',
 fallback:'Strategy Lab is currently translated into English and Romanian. This section uses English; technical engine evidence and imported pack text retain their original language. Translations are machine-drafted and not linguistically reviewed.',
 translation:'English and Romanian interface text is available. Romanian text is machine-drafted and has not had human linguistic review. Technical evidence and imported pack text retain their original language.',
 scenario:'Choose a scenario',bundled:'Bundled study packs',imported:'Imported study pack',custom:'Custom scenario',board:'River board',pot:'Starting pot',stack:'Effective stack',chips:'chips',
 oop:'Out of position',ip:'In position',ranges:'Weighted starting ranges',tree:'Allowed betting tree',assumptions:'Inputs and assumptions',
 study:'Study a solution',chooseNode:'Decision node',chooseHand:'Private hand',action:'Action',frequency:'Strategy frequency',ev:'Action EV',strategy:'Strategy',
 tryDecision:'Try a decision',guessFirst:'Choose an action before showing the strategy.',show:'Show strategy and explanation',hide:'Hide strategy',tryAgain:'Try another decision',
 selectedAction:'Your action',bestEV:'Best action EV in this result',regret:'EV difference from the best available action',regretExplanation:'Difference = best action EV − chosen action EV. This compares actions in the supplied model; it does not grade your general poker ability or a lucky runout.',
 qualityCaveat:'Frequencies and EVs depend on this board, ranges, tree, solver settings, and convergence evidence. A small difference may be below solution accuracy. A mixed strategy can intentionally use more than one action.',
 noEV:'Action EV is unavailable for this row. No numerical regret is graded.',noNode:'This pack has no supported decision nodes to display.',noHands:'This node has no hand rows to display.',
 quality:'Solution quality',method:'Method',engine:'Engine',iterations:'Iterations',elapsed:'Elapsed time',accuracy:'Accuracy evidence',termination:'Termination',
 evidence:'Provenance and verification',raw:'Advanced: structured pack data',limits:'Limitations',technical:'Technical identifiers, poker notation, and solver evidence use their recorded notation.',
 advanced:'Edit a river scenario',advancedHelp:'Edits create a separate solve request. They do not rewrite the bundled solution or a played hand.',
 boardHelp:'Five distinct cards, for example As Kd 7c 4h 2s.',oopRange:'Out-of-position range',ipRange:'In-position range',rangeHelp:'Use the supported weighted range notation. Cards on the board block incompatible combinations.',
 betSizes:'Bet sizes',raiseSizes:'Raise sizes',allIn:'Allow all-in',budget:'Calculation budget',seconds:'seconds',seed:'Seed',apply:'Apply scenario edits',
 settings:'Advanced solver settings',requestJSON:'Validated solve request (JSON)',reset:'Restore selected scenario',invalid:'The scenario or pack is invalid. Check the highlighted inputs or the recorded validation details.',
 solve:'Solve locally',cancel:'Cancel solve',running:'Local calculation is running.',cancelled:'Calculation cancelled.',completed:'Calculation complete.',
 localOnly:'The static browser does not launch Java or a native solver. Offline study packs remain available without an account or server.',
 accountRequired:'A signed-in account on the local online edition is required to request a solve.',account:'Open Account',
 permission:'I permit this bounded calculation on the configured local solver.',permissionHelp:'Only the selected study request is sent. The live table, hidden cards, future deck, and private notebook are not included.',
 unavailable:'The local solver is unavailable or disabled. You can still study bundled packs.',refresh:'Check local solver',status:'Local solver status',ready:'Ready',notReady:'Not ready',
 export:'Export study pack',import:'Import study pack',importHelp:'Import a validated POK solution JSON file. Imported text is displayed as text; files cannot run code.',
 importedOK:'The validated pack is ready to study.',exported:'The pack export was created.',fileTooLarge:'This file exceeds the allowed import size.',
 error:'The request could not be completed.',progress:'Calculation progress',requestId:'Request identifier',retry:'Retry',
 qualityUnknown:'Accuracy is not established by the available evidence.',notFullGame:'Restricted river study · no claim of a solved full game',
 check:'Check',fold:'Fold',call:'Call',bet:'Bet',raise:'Raise',allin:'All-in',
 details:'Details',selected:'Selected',changeScenario:'Changing the scenario clears the current practice choice.',
 noPack:'No study pack is available. Import a supported pack or use a configured local solver.',loading:'Loading…',
 nativeAndroid:'Native desktop solvers are unavailable in the Android offline edition. Study packs and browser calculations remain local.',
 resultHidden:'The answer is hidden until you choose an action or show the strategy.',
 goodWithinModel:'This action has the highest displayed EV in this result. Check the accuracy evidence before treating a small difference as meaningful.',
 savedVerified:'Saved verified solution',fresh:'Fresh local result · independent review not run',importTrust:'Imported verification statements are supplied by the file author. A checksum detects changes; it does not certify authorship or accuracy.',
 gap:'Global best-response gap (NashConv)',gapHelp:'NashConv is the sum of both best-response gains, in chips, for this restricted game. It is not a per-hand error bound.',
 partial:'Partial result: the requested precision was not reached.',unreached:'This information set has negligible reach. Conditional EV uses a fallback belief; numeric decision grading is unavailable.',
 noGrade:'This result does not support confident decision grading. The displayed EV comparison is for study only.',
 weightsHelp:'Weights are relative. The editor uses 0–1 or percentages and normalizes larger imported weights. Maximum 32 concrete combinations per player.',
 treeHelp:'Bet amounts and raise TO amounts are integer chips, not pot percentages. At most two bet sizes and one raise TO size are supported; an empty raise field disables raising.',
 maxRaises:'Maximum raises',dead:'Explicit dead cards',learner:'Learner position',learnerCards:'Learner hand',targetGap:'Requested global gap (chips)',statusComplete:'Complete',statusPartial:'Partial',statusOther:'No usable solution',
 applied:'Scenario edits applied. Solve this new request to obtain a matching result.',verificationTolerance:'Independent check tolerance',verificationValue:'Recorded check value',viewInputs:'Show solved inputs',
 attemptNote:'This study choice does not submit an action at your table or change chips. It is not added to numeric lesson-accuracy totals.',solvedModel:'Solved model',customModel:'Edited model · no solution yet',
 bundledInvalid:'A bundled study pack failed validation and was not loaded.',freshTitle:'Local river study',freshExplanation:'Local solver output for the recorded restricted river model. Independent verification has not been run for this request.',pendingEdits:'The editor has unapplied changes. Apply them before solving, or restore the selected scenario.'
} as const;

export type StrategyKey=keyof typeof strategyEnglish;
export const strategyRomanian:Record<StrategyKey,string>={
 evBaseline:'EV este exprimat în jetoane pentru jucătorul care acționează aici, față de împărțirea egală a potului inițial. Include investițiile viitoare din acest arbore și continuarea conform strategiei medii.',
 title:'Laborator de strategie',intro:'Studiază o decizie pe river, verifică ipotezele, apoi compară acțiunile. Aceste jocuri restrânse nu rezolvă orice situație de poker.',
 fallback:'Laboratorul de strategie este tradus în prezent în engleză și română. Această secțiune folosește engleza; dovezile tehnice ale motorului și textele pachetelor importate își păstrează limba originală. Traducerile sunt redactate automat și nu sunt revizuite lingvistic.',
 translation:'Interfața este disponibilă în engleză și română. Textul românesc este redactat automat și nu a fost revizuit de un lingvist. Dovezile tehnice și textele pachetelor importate își păstrează limba originală.',
 scenario:'Alege un scenariu',bundled:'Pachete de studiu incluse',imported:'Pachet de studiu importat',custom:'Scenariu personalizat',board:'Cărțile comune pe river',pot:'Pot inițial',stack:'Stack efectiv',chips:'jetoane',
 oop:'Fără poziție',ip:'În poziție',ranges:'Range-uri inițiale ponderate',tree:'Arborele de pariuri permis',assumptions:'Date și ipoteze',
 study:'Studiază o soluție',chooseNode:'Nod de decizie',chooseHand:'Mână privată',action:'Acțiune',frequency:'Frecvență în strategie',ev:'EV al acțiunii',strategy:'Strategie',
 tryDecision:'Încearcă o decizie',guessFirst:'Alege o acțiune înainte de a afișa strategia.',show:'Arată strategia și explicația',hide:'Ascunde strategia',tryAgain:'Încearcă altă decizie',
 selectedAction:'Acțiunea ta',bestEV:'Cel mai bun EV al unei acțiuni în acest rezultat',regret:'Diferența de EV față de cea mai bună acțiune disponibilă',regretExplanation:'Diferență = cel mai bun EV − EV al acțiunii alese. Comparăm acțiunile din modelul furnizat; nu evaluăm aptitudinea ta generală la poker și nici norocul cărților.',
 qualityCaveat:'Frecvențele și valorile EV depind de aceste cărți comune, range-uri, arbore, setări ale solverului și dovezi de convergență. O diferență mică poate fi sub precizia soluției. O strategie mixtă poate folosi intenționat mai multe acțiuni.',
 noEV:'EV al acțiunii nu este disponibil pentru acest rând. Nu evaluăm numeric diferența de EV.',noNode:'Acest pachet nu conține noduri de decizie compatibile pentru afișare.',noHands:'Acest nod nu conține rânduri de mâini pentru afișare.',
 quality:'Calitatea soluției',method:'Metodă',engine:'Motor',iterations:'Iterații',elapsed:'Timp scurs',accuracy:'Dovezi privind precizia',termination:'Încheiere',
 evidence:'Proveniență și verificare',raw:'Avansat: datele structurate ale pachetului',limits:'Limite',technical:'Identificatorii tehnici, notația de poker și dovezile solverului păstrează notația înregistrată.',
 advanced:'Editează un scenariu pe river',advancedHelp:'Modificările creează o cerere separată de calcul. Nu rescriu soluția inclusă sau o mână jucată.',
 boardHelp:'Cinci cărți distincte, de exemplu As Kd 7c 4h 2s.',oopRange:'Range fără poziție',ipRange:'Range în poziție',rangeHelp:'Folosește notația ponderată acceptată pentru range-uri. Cărțile comune blochează combinațiile incompatibile.',
 betSizes:'Dimensiuni de pariu',raiseSizes:'Dimensiuni de raise',allIn:'Permite all-in',budget:'Buget de calcul',seconds:'secunde',seed:'Sămânță aleatoare',apply:'Aplică modificările scenariului',
 settings:'Setări avansate ale solverului',requestJSON:'Cerere validată de calcul (JSON)',reset:'Restaurează scenariul selectat',invalid:'Scenariul sau pachetul este nevalid. Verifică datele marcate sau detaliile de validare înregistrate.',
 solve:'Calculează local',cancel:'Anulează calculul',running:'Calculul local este în curs.',cancelled:'Calcul anulat.',completed:'Calcul încheiat.',
 localOnly:'Browserul static nu lansează Java sau un solver nativ. Pachetele de studiu offline rămân disponibile fără cont sau server.',
 accountRequired:'Pentru a solicita un calcul, trebuie să fii autentificat în ediția online locală.',account:'Deschide Cont',
 permission:'Permit acest calcul limitat pe solverul local configurat.',permissionHelp:'Se trimite doar cererea de studiu selectată. Masa activă, cărțile ascunse, cărțile viitoare și caietul privat nu sunt incluse.',
 unavailable:'Solverul local este indisponibil sau dezactivat. Poți studia în continuare pachetele incluse.',refresh:'Verifică solverul local',status:'Starea solverului local',ready:'Pregătit',notReady:'Nepregătit',
 export:'Exportă pachetul de studiu',import:'Importă un pachet de studiu',importHelp:'Importă un fișier JSON validat cu o soluție POK. Textul importat este afișat ca text; fișierele nu pot executa cod.',
 importedOK:'Pachetul validat este pregătit pentru studiu.',exported:'Exportul pachetului a fost creat.',fileTooLarge:'Acest fișier depășește dimensiunea permisă la import.',
 error:'Cererea nu a putut fi finalizată.',progress:'Progresul calculului',requestId:'Identificatorul cererii',retry:'Reîncearcă',
 qualityUnknown:'Dovezile disponibile nu stabilesc precizia.',notFullGame:'Studiu restrâns pe river · fără afirmația că întregul joc este rezolvat',
 check:'Check',fold:'Fold',call:'Call',bet:'Pariu',raise:'Raise',allin:'All-in',
 details:'Detalii',selected:'Selectat',changeScenario:'Schimbarea scenariului șterge alegerea din exercițiul curent.',
 noPack:'Nu este disponibil niciun pachet de studiu. Importă un pachet compatibil sau folosește un solver local configurat.',loading:'Se încarcă…',
 nativeAndroid:'Solverele native pentru calculator nu sunt disponibile în ediția Android offline. Pachetele de studiu și calculele din browser rămân locale.',
 resultHidden:'Răspunsul rămâne ascuns până alegi o acțiune sau afișezi strategia.',
 goodWithinModel:'Această acțiune are cel mai mare EV afișat în acest rezultat. Verifică dovezile privind precizia înainte de a considera relevantă o diferență mică.',
 savedVerified:'Soluție verificată salvată',fresh:'Rezultat local nou · fără verificare independentă',importTrust:'Afirmațiile despre verificare provin de la autorul fișierului importat. O sumă de control detectează modificările; nu certifică autorul sau precizia.',
 gap:'Abatere globală față de cele mai bune răspunsuri (NashConv)',gapHelp:'NashConv este suma câștigurilor ambilor jucători prin cel mai bun răspuns, în jetoane, pentru acest joc restrâns. Nu este o limită a erorii pentru fiecare mână.',
 partial:'Rezultat parțial: precizia solicitată nu a fost atinsă.',unreached:'Acest set de informații are o probabilitate de atingere neglijabilă. EV condiționat folosește o ipoteză de rezervă; evaluarea numerică a deciziei nu este disponibilă.',
 noGrade:'Acest rezultat nu permite evaluarea sigură a deciziei. Comparația EV afișată servește doar studiului.',
 weightsHelp:'Ponderile sunt relative. Editorul folosește 0–1 sau procente și normalizează ponderile importate mai mari. Maximum 32 de combinații concrete pentru fiecare jucător.',
 treeHelp:'Pariurile și raise TO sunt exprimate în jetoane întregi, nu în procente din pot. Sunt permise cel mult două dimensiuni de pariu și o dimensiune raise TO; câmpul gol pentru raise dezactivează majorarea.',
 maxRaises:'Numărul maxim de raise-uri',dead:'Cărți moarte explicite',learner:'Poziția cursantului',learnerCards:'Mâna cursantului',targetGap:'Abaterea globală solicitată (jetoane)',statusComplete:'Complet',statusPartial:'Parțial',statusOther:'Fără soluție utilizabilă',
 applied:'Modificările scenariului au fost aplicate. Calculează această cerere nouă pentru a obține un rezultat corespunzător.',verificationTolerance:'Toleranța verificării independente',verificationValue:'Valoarea înregistrată a verificării',viewInputs:'Arată datele rezolvate',
 attemptNote:'Această alegere de studiu nu trimite o acțiune la masa ta și nu schimbă jetoanele. Nu este adăugată la scorul de precizie al lecțiilor numerice.',solvedModel:'Model rezolvat',customModel:'Model editat · fără soluție încă',
 bundledInvalid:'Un pachet de studiu inclus nu a trecut validarea și nu a fost încărcat.',freshTitle:'Studiu local pe river',freshExplanation:'Rezultat al solverului local pentru modelul restrâns pe river înregistrat. Nu a fost efectuată o verificare independentă pentru această cerere.',pendingEdits:'Editorul conține modificări neaplicate. Aplică-le înainte de calcul sau restaurează scenariul selectat.'
};

export function strategyText(locale:Locale,key:StrategyKey):string{return (locale==='ro'?strategyRomanian:strategyEnglish)[key];}

const romanianStudyAssumptions=' Studiu educațional original POK. Range-urile ponderate depind de ipoteze și nu sunt range-uri preflop aprobate de un solver. Ipotezele privind ponderile și dimensiunile restrânse definesc acest studiu; nu este o soluție pentru întregul joc. Programarea liniară independentă verifică același joc finit.';
export const bundledRomanianText:Record<string,{title:string;explanation:string}>={
 'dry-broadway-bluff-catcher':{title:'Un bluff catcher sub draw-urile broadway',explanation:'Studiază cum se combină mâinile de valoare și bluffurile ratate cu cărți mici împotriva call-urilor cu o pereche.'+romanianStudyAssumptions},
 'monotone-heart-blockers':{title:'Trei inimi și inima mare care lipsește',explanation:'Compară valoarea unei culori, blockerii de inimă mare și bluff catcherii folosind range-uri ponderate explicite.'+romanianStudyAssumptions},
 'paired-queen-boats':{title:'Dame pereche și presiunea unui full house',explanation:'Deosebește trei cărți de același rang de un full house, ținând cont de excluderea combinațiilor care au cărți comune.'+romanianStudyAssumptions},
 'straight-board-shared-value':{title:'O chintă pe masă nu este întotdeauna mâna maximă',explanation:'Studiază egalitățile în care se joacă masa, chintele mai mari și distribuțiile condiționate de blockeri.'+romanianStudyAssumptions},
 'ace-high-explicit-dead':{title:'O carte moartă explicită și draw-uri ratate',explanation:'Verifică o carte moartă declarată în studiu față de range-uri deja compatibile, apoi compară valoarea marginală cu draw-urile ratate.'+romanianStudyAssumptions},
 'paired-five-raise-abstraction':{title:'Două dimensiuni de pariu și un raise complet',explanation:'Compară un arbore restrâns de raise-uri cu răspunsurile check, pariu, call și fold.'+romanianStudyAssumptions}
};
