import type {AnalysisRequest,EngineId} from './contract';
import {EQUITY_VERSION} from '../equity';
export const ADAPTER_VERSION='pok-analysis-1.0.0';
// Separate role in the existing registry. Runtime readiness is verified by the authenticated backend.
export const strategyRegistry=[{id:'texas-holdem-java-dcfr',name:'TexasHoldemSolverJava / POK river',role:'strategy solver',revision:'e90d1bb4c7cf6fbd433428d6acf41f606e0c8530',adapterVersion:'pok-river-1',license:'MIT upstream; Apache-2.0 Java dependencies; POK adapter license unchanged',location:'local-jvm',scope:'Heads-up river, explicit weighted ranges, restricted discrete betting tree, no rake',weightedRanges:true,deadCards:true,sidePots:false,multiway:false,seed:'Deterministic traversal; no random seed',cancellation:'Owned JVM termination and Windows Job memory/kill guard',runtimeReady:false,availability:'Authenticated health query; desktop only. Saved packs work offline.',evidence:'docs/architecture/JAVA_SOLVER_REVIEW.md; independent sequence-form oracle report'}];
export const registry=[
  {id:'pok-standard' as EngineId,name:'POK Standard',role:'equity engine',description:'Built-in equity and hand evaluator. Browser, offline.',revision:EQUITY_VERSION,license:'Original POK source; no new public license grant.',location:'browser-worker' as const,detected:true,built:true,tested:true,runtimeReady:true,weightedRanges:true,deadCards:true,fractionalTies:true,sidePots:true,methods:['exact','monte-carlo'],seed:'POK Mulberry32; independent analysis stream',cancellation:'Worker termination',components:['POK validation','POK weighted sampler / enumeration','POK pot eligibility wrapper','POK evaluator'],evidence:'Original equity regression; tests/engines.test.ts'},
  {id:'pok-ph' as EngineId,name:'POK + PH Evaluator',role:'equity engine + alternative hand evaluator',description:'POK equity + PH hand evaluator. Browser, offline; Apache-2.0 upstream.',revision:'PH-0.6.1/10be452e4c1ee40a6a56f06457f46bff27ca495a/pok-wasm-port-1',license:'Apache-2.0 (PH source and generated tables); bundled notice',location:'browser-worker' as const,detected:true,built:true,tested:true,runtimeReady:true,weightedRanges:true,deadCards:true,fractionalTies:true,sidePots:true,methods:['exact','monte-carlo'],seed:'Same POK sampler and analysis stream as Standard',cancellation:'Worker termination',components:['POK validation','POK weighted sampler / enumeration','POK pot eligibility wrapper','PH WASM evaluator'],evidence:'tests/ph-evaluator.test.ts; tests/engines.test.ts; PH census artifact'},
  {id:'ompeval-native' as EngineId,name:'OMPEval Native',role:'native equity reference',description:'Built and tested development CLI. Not connected to this static browser preview.',revision:'4aec210ff75b0851af0ee170b35a7899e1a4fe8f',license:'ISC + libdivide notices',location:'local-native' as const,detected:true,built:true,tested:true,runtimeReady:false,weightedRanges:false,deadCards:true,fractionalTies:true,sidePots:false,methods:['exact'],seed:'Native Monte Carlo is not exposed; no upstream seed control',cancellation:'Owned process deadline / stop and join',components:['POK boundary validation','OMPEval native enumeration/evaluator'],evidence:'12 native adapter tests; 10,000 independent seven-card comparisons; docs/OMPEVAL_VERIFICATION.json'},
];
export function entryFor(id:AnalysisRequest['engine']){return registry.find(e=>e.id===(id==='automatic'?'pok-standard':id))!}
export function compatibility(r:AnalysisRequest):{compatible:boolean;reason:string}{
  const entry=entryFor(r.engine);
  if(!entry.runtimeReady)return {compatible:false,reason:entry.description};
  if(entry.location==='local-native'&&r.executionPermission!=='local-native-opt-in')return {compatible:false,reason:'Explicit local native permission is required.'};
  if(r.method!=='auto'&&!entry.methods.includes(r.method))return {compatible:false,reason:'Requested method is unsupported.'};
  return {compatible:true,reason:'Hold’em high, 2–6 players, all streets, explicit dead cards, weighted compatible assignments and eligible side pots.'};
}
