package pok.solver;

import com.fasterxml.jackson.core.*;
import com.fasterxml.jackson.databind.*;
import icybee.solver.*;
import icybee.solver.nodes.*;
import icybee.solver.ranges.PrivateCards;
import icybee.solver.solver.PokBoundedSolver;
import java.io.*;
import java.util.*;
import java.util.concurrent.*;

/** Strict structured-input bridge; never accepts file paths, URLs, commands or class names. */
public final class PokRiverMain {
 static final String REVISION="e90d1bb4c7cf6fbd433428d6acf41f606e0c8530";
 static final ObjectMapper JSON=new ObjectMapper(JsonFactory.builder().enable(StreamReadFeature.STRICT_DUPLICATE_DETECTION).streamReadConstraints(StreamReadConstraints.builder().maxNestingDepth(10).maxStringLength(256).maxNumberLength(32).build()).build()).enable(DeserializationFeature.FAIL_ON_TRAILING_TOKENS);
 static final long START=System.nanoTime();
 static double jointWeight;static int pot,stack,maxRaises;static int[]bets,raises,board;static PrivateCards[][] ranges;static ReferenceCompairer eval;
 static final Map<GameTreeNode,Meta> meta=new IdentityHashMap<>();
 static final Map<ActionNode,double[][]> policy=new IdentityHashMap<>();
 static final class Meta {String id;int[] committed;List<Map<String,Object>> actions=new ArrayList<>();Meta(String id,int[]c){this.id=id;committed=c.clone();}}
 static Map<String,Object> map(Object... pairs){Map<String,Object> result=new LinkedHashMap<>();for(int i=0;i<pairs.length;i+=2)result.put((String)pairs[i],pairs[i+1]);return result;}
 static synchronized void emit(Object value){try{String text=JSON.writeValueAsString(value);if(text.length()>2_000_000)throw new IllegalArgumentException("output_too_large");System.out.println(text);System.out.flush();}catch(Exception ex){throw new IllegalStateException("output_error");}}
 static void require(boolean test,String code){if(!test)throw new IllegalArgumentException(code);}
 static void keys(JsonNode n,String... names){require(n!=null&&n.isObject(),"invalid_object");Set<String> allowed=Set.of(names);n.fieldNames().forEachRemaining(k->require(allowed.contains(k),"unknown_field"));}
 static int integer(JsonNode n,int min,int max){require(n!=null&&n.isIntegralNumber()&&n.canConvertToInt(),"invalid_integer");int v=n.intValue();require(v>=min&&v<=max,"invalid_integer");return v;}
 static int[]cards(JsonNode n,int min,int max){require(n!=null&&n.isArray()&&n.size()>=min&&n.size()<=max,"invalid_cards");int[] result=new int[n.size()];long used=0;for(int i=0;i<n.size();i++){require(n.get(i).isTextual()&&n.get(i).textValue().matches("[2-9TJQKA][cdhs]"),"invalid_card");int c=Card.strCard2int(n.get(i).textValue());require((used&(1L<<c))==0,"duplicate_card");used|=1L<<c;result[i]=c;}return result;}
 static List<String>texts(int[] cards){List<String> result=new ArrayList<>();for(int c:cards)result.add(Card.intCard2Str(c));return result;}
 static int[] amounts(JsonNode n){require(n!=null&&n.isArray()&&n.size()<=2,"invalid_sizes");int[] result=new int[n.size()];Set<Integer> seen=new HashSet<>();for(int i=0;i<n.size();i++){result[i]=integer(n.get(i),1,stack);require(seen.add(result[i]),"duplicate_size");}Arrays.sort(result);return result;}
 static PrivateCards[] range(JsonNode n,long blocked){require(n!=null&&n.isArray()&&n.size()>0&&n.size()<=128,"invalid_range");List<PrivateCards> result=new ArrayList<>();List<Double> weights=new ArrayList<>();Set<Long> seen=new HashSet<>();double maximum=0;for(JsonNode row:n){keys(row,"cards","weight");int[] c=cards(row.get("cards"),2,2);Arrays.sort(c);long mask=Card.boardInts2long(c);require(seen.add(mask),"duplicate_combination");JsonNode w=row.get("weight");require(w!=null&&w.isNumber(),"invalid_weight");double weight=w.doubleValue();require(Double.isFinite(weight)&&weight>=0&&weight<=1e12,"invalid_weight");if((mask&blocked)!=0||weight==0)continue;maximum=Math.max(maximum,weight);result.add(new PrivateCards(c[0],c[1],0));weights.add(weight);}require(!result.isEmpty(),"empty_range_after_blockers");for(int i=0;i<result.size();i++){double normalized=weights.get(i)/maximum;require(normalized>=1e-8,"weight_dynamic_range_unsupported");result.get(i).weight=(float)normalized;}return result.toArray(PrivateCards[]::new);}
 static boolean compatible(int a,int b){return (ranges[0][a].toBoardLong()&ranges[1][b].toBoardLong())==0;}
 static GameTreeNode terminal(String id,int[]c,Integer winner){GameTreeNode node;if(winner==null){double a=pot/2.0+c[1],b=pot/2.0+c[0];node=new ShowdownNode(new Double[]{(c[1]-c[0])/2.0,(c[0]-c[1])/2.0},new Double[][]{{a,-a},{-b,b}},GameTreeNode.GameRound.RIVER,(double)(pot+c[0]+c[1]),null);}else{double gain=pot/2.0+c[1-winner];Double[]payoff=winner==0?new Double[]{gain,-gain}:new Double[]{-gain,gain};node=new TerminalNode(payoff,winner,GameTreeNode.GameRound.RIVER,(double)(pot+c[0]+c[1]),null);}meta.put(node,new Meta(id,c));return node;}
 static void add(ActionNode node,GameTreeNode.PokerActions type,int amount,int target,GameTreeNode child){node.getActions().add(new GameActions(type,type==GameTreeNode.PokerActions.BET||type==GameTreeNode.PokerActions.RAISE?(double)target:null));node.getChildrens().add(child);child.setParent(node);String label=type.name()+(type==GameTreeNode.PokerActions.BET||type==GameTreeNode.PokerActions.RAISE?" "+target:"");meta.get(node).actions.add(map("label",label,"type",type.name(),"amount",amount,"raiseTo",target,"child",meta.get(child).id));}
 static GameTreeNode tree(String id,int actor,int[]c,int checks,int raiseCount,int lastRaise){require(meta.size()<96,"tree_budget_exceeded");ActionNode node=new ActionNode(new ArrayList<>(),new ArrayList<>(),actor,GameTreeNode.GameRound.RIVER,(double)(pot+c[0]+c[1]),null);meta.put(node,new Meta(id,c));int call=c[1-actor]-c[actor];if(call==0){GameTreeNode child=checks==1?terminal(id+"/CHECK",c,null):tree(id+"/CHECK",1-actor,c,checks+1,raiseCount,lastRaise);add(node,GameTreeNode.PokerActions.CHECK,0,c[actor],child);for(int bet:bets){if(c[actor]+bet>stack)continue;int[]next=c.clone();next[actor]+=bet;add(node,GameTreeNode.PokerActions.BET,bet,next[actor],tree(id+"/BET:"+next[actor],1-actor,next,0,raiseCount,bet));}}else{add(node,GameTreeNode.PokerActions.FOLD,0,c[actor],terminal(id+"/FOLD",c,1-actor));int[]next=c.clone();next[actor]=c[1-actor];add(node,GameTreeNode.PokerActions.CALL,call,next[actor],terminal(id+"/CALL",next,null));if(raiseCount<maxRaises)for(int target:raises){if(target-c[1-actor]<lastRaise||target>stack)continue;next=c.clone();next[actor]=target;add(node,GameTreeNode.PokerActions.RAISE,target-c[actor],target,tree(id+"/RAISE:"+target,1-actor,next,0,raiseCount+1,target-c[1-actor]));}}return node;}
 static void capture(GameTreeNode n){if(n instanceof ActionNode a){float[]raw=a.getTrainable().getAverageStrategy();int hands=ranges[a.getPlayer()].length;double[][]rows=new double[hands][a.getActions().size()];for(int h=0;h<hands;h++){double sum=0;for(int j=0;j<rows[h].length;j++){double p=raw[j*hands+h];require(Double.isFinite(p)&&p>=0&&p<=1.00001,"invalid_solver_policy");rows[h][j]=p;sum+=p;}require(sum>0&&Math.abs(sum-1)<0.0001,"invalid_solver_policy");for(int j=0;j<rows[h].length;j++)rows[h][j]/=sum;}policy.put(a,rows);for(GameTreeNode child:a.getChildrens())capture(child);}}
 static double payoff(GameTreeNode n,int h0,int h1){if(n instanceof TerminalNode t)return t.get_payoffs()[0];if(n instanceof ShowdownNode s){int a=eval.get_rank(ranges[0][h0].get_hands(),board),b=eval.get_rank(ranges[1][h1].get_hands(),board);return s.get_payoffs(a==b?ShowdownNode.ShowDownResult.TIE:ShowdownNode.ShowDownResult.NOTTIE,a==b?null:a<b?0:1)[0];}ActionNode a=(ActionNode)n;double value=0;double[]probs=policy.get(a)[a.getPlayer()==0?h0:h1];for(int i=0;i<probs.length;i++)value+=probs[i]*payoff(a.getChildrens().get(i),h0,h1);return value;}
 static void export(GameTreeNode n,double[][]reach,List<Object> out){Meta m=meta.get(n);Map<String,Object> row=map("id",m.id,"kind",n.getType().name(),"committed",m.committed,"pot",n.getPot());out.add(row);if(n instanceof ActionNode a){int actor=a.getPlayer();row.put("actor",actor);row.put("actions",m.actions);List<Object> perHand=new ArrayList<>();for(int h=0;h<ranges[actor].length;h++){double mass=0;double[]evs=new double[a.getActions().size()];for(int o=0;o<ranges[1-actor].length;o++){int h0=actor==0?h:o,h1=actor==0?o:h;if(!compatible(h0,h1))continue;mass+=reach[1-actor][o];for(int j=0;j<evs.length;j++)evs[j]+=reach[1-actor][o]*payoff(a.getChildrens().get(j),h0,h1)*(actor==0?1:-1);}double observedMass=mass;boolean fallback=mass==0;if(fallback){for(int o=0;o<ranges[1-actor].length;o++){int h0=actor==0?h:o,h1=actor==0?o:h;if(!compatible(h0,h1))continue;double weight=ranges[1-actor][o].weight;mass+=weight;for(int j=0;j<evs.length;j++)evs[j]+=weight*payoff(a.getChildrens().get(j),h0,h1)*(actor==0?1:-1);}}List<Object> actionsEV=new ArrayList<>();double ev=0;for(int j=0;j<evs.length;j++){evs[j]/=mass;ev+=policy.get(a)[h][j]*evs[j];actionsEV.add(evs[j]);}perHand.add(map("cards",texts(new int[]{ranges[actor][h].card1,ranges[actor][h].card2}),"weight",ranges[actor][h].weight,"probabilities",policy.get(a)[h],"evChips",ev,"actionEvChips",actionsEV,"ownReach",reach[actor][h],"opponentReachMass",observedMass,"informationSetReach",reach[actor][h]*observedMass/jointWeight,"evBelief",fallback?"initial-range-fallback-no-opponent-reach":"conditional-on-opponent-action-reach"));}row.put("policies",perHand);for(int j=0;j<a.getActions().size();j++){double[][]next={reach[0].clone(),reach[1].clone()};for(int h=0;h<next[actor].length;h++)next[actor][h]*=policy.get(a)[h][j];export(a.getChildrens().get(j),next,out);}}else if(n instanceof TerminalNode t){row.put("payoffs",t.get_payoffs());}else if(n instanceof ShowdownNode s){row.put("winPayoffs",new Double[][]{s.get_payoffs(ShowdownNode.ShowDownResult.NOTTIE,0),s.get_payoffs(ShowdownNode.ShowDownResult.NOTTIE,1)});row.put("tiePayoffs",s.get_payoffs(ShowdownNode.ShowDownResult.TIE,null));}}
 static Object solve(JsonNode request)throws Exception{
  keys(request,"schema","op","board","dead","ranges","pot","effectiveStack","betSizes","raiseTo","maxRaises","iterations","deadlineMs");board=cards(request.get("board"),5,5);int[]dead=cards(request.get("dead"),0,43);long blocked=Card.boardInts2long(board);for(int c:dead){require((blocked&(1L<<c))==0,"duplicate_card");blocked|=1L<<c;}pot=integer(request.get("pot"),2,100000);stack=integer(request.get("effectiveStack"),1,100000);bets=amounts(request.get("betSizes"));raises=amounts(request.get("raiseTo"));maxRaises=integer(request.get("maxRaises"),0,1);int iterations=integer(request.get("iterations"),1,20000),deadlineMs=integer(request.get("deadlineMs"),100,15000);JsonNode inRanges=request.get("ranges");require(inRanges!=null&&inRanges.isArray()&&inRanges.size()==2,"two_players_required");ranges=new PrivateCards[][]{range(inRanges.get(0),blocked),range(inRanges.get(1),blocked)};double joint=0;int assignments=0;for(int p=0;p<2;p++)for(int h=0;h<ranges[p].length;h++){boolean found=false;for(int o=0;o<ranges[1-p].length;o++)if((ranges[p][h].toBoardLong()&ranges[1-p][o].toBoardLong())==0)found=true;require(found,"hand_has_no_compatible_opponent");}for(int a=0;a<ranges[0].length;a++)for(int b=0;b<ranges[1].length;b++)if(compatible(a,b)){joint+=(double)ranges[0][a].weight*ranges[1][b].weight;assignments++;}require(joint>0,"impossible_joint_ranges");jointWeight=joint;
  Deck deck=new Deck(Arrays.asList("2","3","4","5","6","7","8","9","T","J","Q","K","A"),Arrays.asList("c","d","h","s"));GameTreeNode root=tree("root",0,new int[]{0,0},0,0,1);eval=new ReferenceCompairer();PokBoundedSolver solver=new PokBoundedSolver(new GameTree(deck,root),ranges[0],ranges[1],board,eval,deck,iterations);List<Object> trace=new ArrayList<>();long deadline=System.nanoTime()+TimeUnit.MILLISECONDS.toNanos(deadlineMs);solver.solve(deadline,p->{emit(p);trace.add(p);});double[] br=solver.bestResponseValues();capture(root);double[][]reach={new double[ranges[0].length],new double[ranges[1].length]};for(int p=0;p<2;p++)for(int h=0;h<ranges[p].length;h++)reach[p][h]=ranges[p][h].weight;List<Object> nodes=new ArrayList<>();export(root,reach,nodes);double ev=0;for(int a=0;a<ranges[0].length;a++)for(int b=0;b<ranges[1].length;b++)if(compatible(a,b))ev+=(double)ranges[0][a].weight*ranges[1][b].weight*payoff(root,a,b)/joint;List<Object>rangeOutput=new ArrayList<>();for(int p=0;p<2;p++){List<Object> rows=new ArrayList<>();for(PrivateCards h:ranges[p])rows.add(map("cards",texts(new int[]{h.card1,h.card2}),"weight",h.weight,"rank",eval.get_rank(h.get_hands(),board)));rangeOutput.add(rows);}double gap=br[0]+br[1];
  return map("schema",1,"type","result","ok",true,"status","COMPLETE","engine","TexasHoldemSolverJava","upstreamRevision",REVISION,"adapterVersion","pok-java-river-1","algorithm","upstream DiscountedCfrTrainable; theta=0.9 alpha=1.5 beta=0.5 gamma=2","iterations",solver.completed,"elapsedMs",(System.nanoTime()-START)/1e6,"computeThreads",1,"board",texts(board),"dead",texts(dead),"pot",pot,"effectiveStack",stack,"ranges",rangeOutput,"compatibleAssignments",assignments,"normalizedJointWeight",joint,"nodes",nodes,"trace",trace,"profileEvChips",new double[]{ev,-ev},"upstreamBestResponseValues",br,"nashConvChips",gap,"exploitabilityChips",gap/2,"exploitabilityPercentPot",gap/2/pot*100,"definitions",map("utility","Centered zero-sum chips: root pot split equally as baseline; winner gains half initial pot plus opponent future investment; loser loses half initial pot plus own future investment.","nashConvChips","BR0(profile1)+BR1(profile0), from upstream BestResponse; independent oracle validation required.","profileEvChips","Exact compatible weighted pair evaluation under exported normalized average policies.","perComboEv","Counterfactual conditional EV against compatible opponent action reach; zero opponent reach uses explicitly labelled initial-range fallback and informationSetReach=0, unsuitable for grading.","policy","Upstream accumulated discounted average, normalized for float row rounding; every own combo at every node included.","rank","POK reference five-card Java port, best-of-21, negated base-15 score; lower stronger."),"limitations",List.of("Heads-up river only; no chance nodes, rake, side pots or multistreet solution.","Discrete configured bets and at most one full raise; omitted sizes are not solved.","Old unmaintained upstream solver with float arithmetic; independent quality gates determine readiness.","Iteration budget is not a convergence certificate; displayed metric requires oracle validation."));
 }
 public static void main(String[]args){ScheduledExecutorService watchdog=Executors.newSingleThreadScheduledExecutor(r->{Thread t=new Thread(r,"pok-bounded-watchdog");t.setDaemon(true);return t;});watchdog.schedule(()->{emit(map("type","result","schema",1,"ok",false,"code","process_timeout"));Runtime.getRuntime().halt(124);},17,TimeUnit.SECONDS);try{byte[] raw=System.in.readNBytes(131073);require(raw.length<=131072,"input_too_large");JsonNode request=JSON.readTree(raw);require(request!=null&&integer(request.get("schema"),1,1)==1&&request.has("op")&&request.get("op").isTextual(),"invalid_request");String op=request.get("op").textValue();Object result;if(op.equals("evaluate")){keys(request,"schema","op","hands");JsonNode hands=request.get("hands");require(hands!=null&&hands.isArray()&&hands.size()>0&&hands.size()<=10000,"invalid_hands");List<Integer>ranks=new ArrayList<>();for(JsonNode hand:hands)ranks.add(ReferenceCompairer.evaluate(cards(hand,5,7)));result=map("schema",1,"type","result","ok",true,"ranks",ranks,"rankOrder","higher-is-better","rankEncoding","POK base-15 category-and-kicker score");}else if(op.equals("info")){keys(request,"schema","op");result=map("schema",1,"type","result","ok",true,"engine","TexasHoldemSolverJava","upstreamRevision",REVISION,"adapterVersion","pok-java-river-1","maxIterations",20000,"maxRangeCombinations",128,"maxDecisionTreeNodes",96,"maxDeadlineMs",15000,"computeThreads",1);}else{require(op.equals("solve"),"unsupported_operation");result=solve(request);}emit(result);}catch(Exception ex){String code=ex instanceof IllegalArgumentException||ex instanceof IllegalStateException?ex.getMessage():"invalid_request_or_solver_failure";if(code==null||!code.matches("[a-z_]{1,80}"))code="invalid_request_or_solver_failure";emit(map("schema",1,"type","result","ok",false,"code",code));System.exit(2);}finally{watchdog.shutdownNow();}}
}
