import {test,expect,type Page,type BrowserContext} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import path from 'node:path';
const base='http://127.0.0.1:4319';
const shots='artifacts/pok-screenshots';
const evidence:{name:string;passed:boolean}[]=[];
async function start(page:Page){await page.goto(base+'/holdem-lab/');const explore=page.getByRole('button',{name:'Explore first',exact:true});await expect(explore).toBeVisible();await explore.click();await expect(page.getByRole('dialog')).toHaveCount(0);}
async function area(page:Page,name:string){await page.getByRole('navigation',{name:'Platform navigation'}).getByRole('button',{name,exact:true}).click();}
async function tab(page:Page,name:string){await page.getByRole('navigation',{name:'Help and community'}).getByRole('button',{name,exact:true}).click();}
async function account(page:Page,name:string){
 const id=randomUUID(),email=`${id}@example.invalid`,password=randomUUID()+'aA9!';
 await start(page);await area(page,'Account');await page.getByRole('button',{name:'Create account',exact:true}).click();await page.getByLabel('Email',{exact:true}).fill(email);await page.getByLabel('Display name',{exact:true}).fill(name);await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('checkbox',{name:/I am 18/}).check();await page.getByRole('button',{name:'Create account',exact:true}).click();await expect(page.getByText('Check your email to verify your account.',{exact:false})).toBeVisible();
 const mail=await (await page.context().request.get(base+'/api/dev/mail?email='+encodeURIComponent(email))).json();expect(mail.messages).toHaveLength(1);await page.goto(mail.messages[0].url);await area(page,'Account');await page.getByLabel('Email',{exact:true}).fill(email);await page.getByLabel('Password',{exact:true}).fill(password);await page.locator('form').getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.locator('.member-strip')).toContainText(name);const me=await (await page.context().request.get(base+'/api/me')).json();return {email,password,me};
}
async function screenshot(page:Page,name:string){await mkdir(shots,{recursive:true});await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:`${shots}/${name}.png`,fullPage:true});}
async function post(context:BrowserContext,route:string,body:unknown,csrf:string){return context.request.post(base+route,{headers:{Origin:base,'X-POK-CSRF':csrf},data:body})}
test('real local accounts, feedback-to-CP, Q&A, two-context chat, restrictions, sync and disabled AI',async({browser})=>{
 const contexts:BrowserContext[]=[];const external:string[]=[],errors:string[]=[];
 async function fresh(){const c=await browser.newContext({viewport:{width:1440,height:1000},serviceWorkers:'block'});contexts.push(c);await c.route('**/*',r=>{const u=new URL(r.request().url());if(!['127.0.0.1','localhost'].includes(u.hostname)&&!['data:','blob:'].includes(u.protocol)){external.push(u.origin);return r.abort()}return r.continue()});const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));return p}
 const a=await fresh(),b=await fresh();const alice=await account(a,'Study Alpha'),bob=await account(b,'Study Beta');evidence.push({name:'UI registration, real SQLite, local mail verification and session login in two isolated contexts',passed:true});
 // Local operator bootstrap: no first-registrant privilege and no public admin endpoint.
 const denied=await a.context().request.get(base+'/api/admin/users');expect(denied.status()).toBe(403);
 execFileSync(process.execPath,['--import','tsx','server/operator.ts','bootstrap-owner',alice.me.user.id],{cwd:path.resolve('.'),env:{...process.env,POK_DATA_DIR:path.resolve('artifacts/online-test-data')},stdio:'pipe'});
 await a.reload();await area(a,'Account');await expect(a.getByRole('button',{name:'Control panel',exact:true})).toBeVisible();
 // Feedback sent from the UI, persisted and responded to by the actual CP.
 await area(b,'Community');await tab(b,'Feedback');await b.getByLabel('Title',{exact:true}).fill('Readable cards study');await b.getByLabel('Message',{exact:true}).fill('Can the card labels remain readable at large text size?');await b.locator('form').getByRole('button',{name:'Send',exact:true}).click();await expect(b.getByText('Readable cards study',{exact:true})).toBeVisible();
 await a.getByRole('button',{name:'Control panel',exact:true}).click();await expect(a.getByRole('heading',{name:'Readable cards study',exact:true})).toHaveCount(0);await expect(a.locator('.admin-list')).toContainText('Readable cards study');await a.locator('.admin-list').getByRole('button',{name:'Reply',exact:true}).first().click();await a.getByLabel('Reply',{exact:true}).fill('Yes. Appearance includes card size and text scaling through 200%.');await a.locator('form').getByRole('button',{name:'Send',exact:true}).click();
 await b.getByRole('button',{name:'Refresh',exact:true}).click();await b.getByRole('button',{name:'Replies',exact:true}).first().click();await expect(b.locator('.thread')).toContainText('text scaling through 200%');await screenshot(b,'feedback');await screenshot(a,'control-panel');evidence.push({name:'Feedback UI -> persistent ticket -> authorized CP reply -> member thread',passed:true});
 // Q&A and real study-room chat from separate sessions.
 await tab(b,'Questions');await b.getByLabel('Title',{exact:true}).fill('Why is this call twenty percent?');await b.getByLabel('Message',{exact:true}).fill('The pot is eighty and I call twenty.');await b.locator('form').getByRole('button',{name:'Send',exact:true}).click();await b.getByRole('button',{name:'Mark resolved',exact:true}).first().click();await expect(b.getByText('✓ Resolved')).toBeVisible();
 await tab(a,'Study room');await tab(b,'Study room');await b.getByLabel('Message',{exact:true}).fill('Working through pot odds together.');await b.locator('form').getByRole('button',{name:'Send',exact:true}).click();await a.getByRole('button',{name:'Refresh',exact:true}).click();await expect(a.locator('.community-item')).toContainText('Working through pot odds together.');
 const am=await (await a.context().request.get(base+'/api/me')).json(),bm=await (await b.context().request.get(base+'/api/me')).json();
 let r=await post(a.context(),'/api/admin/sanctions',{targetId:bm.user.id,kind:'mute',reason:'Temporary classroom test restriction',expiresAt:Date.now()+60000},am.csrf);expect(r.status()).toBe(201);const sanction=await r.json();r=await post(b.context(),'/api/content',{kind:'chat',body:'This must be blocked on the existing session'},bm.csrf);expect(r.status()).toBe(403);expect((await (await b.context().request.get(base+'/api/sync')).json()).revision).toBe(0);
 r=await post(b.context(),'/api/appeals',{sanctionId:sanction.id,body:'Please review this controlled test.'},bm.csrf);expect(r.status()).toBe(201);r=await post(a.context(),'/api/admin/sanctions',{targetId:bm.user.id,kind:'revoke',sanctionId:sanction.id,reason:'Classroom test finished'},am.csrf);expect(r.status()).toBe(200);evidence.push({name:'Q&A resolution; two-context chat; existing-session mute, appeal, reversal without deleting progress',passed:true});
 // Explicit synchronization and account separation; no automatic guest upload.
 await tab(b,'Account');await b.getByRole('button',{name:'Upload selected data',exact:true}).click();await expect(b.getByRole('status')).toContainText('Saved');const saved=await (await b.context().request.get(base+'/api/sync')).json();expect(saved.revision).toBe(1);expect(saved.payload.settings).toBeDefined();expect((await (await a.context().request.get(base+'/api/sync')).json()).payload).toBeNull();
 await tab(b,'Ask AI coach');await expect(b.getByText('Cloud coach is disabled',{exact:false})).toBeVisible();await expect(b.locator('form').getByRole('button',{name:'Send',exact:true})).toBeDisabled();evidence.push({name:'Explicit preference sync and two-account isolation; missing AI key leaves lessons available',passed:true});
 await tab(b,'Account');const download=b.waitForEvent('download');await b.getByRole('button',{name:'Export account data',exact:true}).click();expect((await download).suggestedFilename()).toBe('POK-account.json');await b.getByRole('button',{name:'Sign out',exact:true}).click();await expect(b.getByLabel('Email',{exact:true})).toBeVisible();await expect(b.locator('.member-strip')).toHaveCount(0);await b.getByText('More sign-in options',{exact:true}).click();await screenshot(b,'provider-choices');expect((await b.context().request.get(base+'/api/account/export')).status()).toBe(401);
 expect(external).toEqual([]);expect(errors).toEqual([]);await writeFile('artifacts/pok-online-browser-evidence.json',JSON.stringify({observedAt:new Date().toISOString(),browser:browser.version(),scope:'Built online edition; real loopback server and SQLite; local mail sink; no live external providers or AI calls',evidence,externalRequests:external,pageErrors:errors},null,2));for(const c of contexts)await c.close();
});
