// Existing functional regression run against the isolated strategy bundle.
import {test,expect,type Page} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';
import {defaultAppearance} from '../src/appearance';
import {readFileSync} from 'node:fs';
const catalogs=JSON.parse(readFileSync('src/locales/engines.json','utf8')) as Record<string,Record<string,string>>;
const evidence:any[]=[];const faults=new WeakMap<Page,{external:string[];errors:string[];wasm:number}>();
const nav=async(page:Page,name:string)=>page.getByRole('navigation',{name:'Main navigation'}).getByRole('button',{name,exact:false}).click();
async function results(page:Page){return page.evaluate(()=>(window as any).engineEvidence.results as any[])}
async function snap(page:Page,name:string){await page.screenshot({path:`artifacts/solver/screenshots/${name}.png`,fullPage:true,animations:'disabled'})}
test.beforeEach(async({context,page})=>{
  const f={external:[] as string[],errors:[] as string[],wasm:0};faults.set(page,f);
  await context.route('**/*',route=>{const u=new URL(route.request().url());if(!['localhost','127.0.0.1','[::1]'].includes(u.hostname)&&!['data:','blob:'].includes(u.protocol)){f.external.push(u.origin);return route.abort()}if(u.pathname.endsWith('.wasm'))f.wasm++;return route.continue()});
  page.on('pageerror',e=>f.errors.push(e.message));
  await page.addInitScript(()=>{
    (window as any).engineEvidence={results:[],progress:[],requests:[]};const Original=window.Worker;
    window.Worker=class extends Original{constructor(url:string|URL,options?:WorkerOptions){super(url,options);this.addEventListener('message',e=>{if(e.data?.kind==='result')(window as any).engineEvidence.results.push(e.data.result);if(e.data?.kind==='progress')(window as any).engineEvidence.progress.push(e.data.progress)})}override postMessage(message:any,transfer?:any){if(message?.schemaVersion===1)(window as any).engineEvidence.requests.push(message);super.postMessage(message,transfer)}};
  });
  await mkdir('artifacts/solver/screenshots',{recursive:true});await page.goto('./',{waitUntil:'networkidle'});await page.getByRole('button',{name:'Explore first',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);
});
test.afterEach(async({page},info)=>{evidence.push({name:info.title,status:info.status,...faults.get(page)});await writeFile('artifacts/engine-browser-evidence.json',JSON.stringify({observedAt:new Date().toISOString(),context:'Fresh Edge contexts, empty caches, nonloopback blocked before first navigation, real Apache build and real workers',evidence},null,2));expect(faults.get(page)?.external).toEqual([]);expect(faults.get(page)?.errors).toEqual([])});
test('each enabled engine executes, attributes its result and compares identical snapshots offline',async({page})=>{
  await nav(page,'Odds Lab');expect(faults.get(page)?.wasm).toBe(0);
  const chooser=page.getByLabel('Analysis engine',{exact:true});await expect(chooser).toHaveValue('automatic');await expect(chooser.locator('option')).toHaveCount(3);
  for(const engine of ['pok-standard','pok-ph']){
    await chooser.selectOption(engine);await page.getByRole('button',{name:'Calculate equity',exact:true}).click();await expect(page.getByTestId('engine-attribution')).toContainText(engine==='pok-ph'?'POK + PH Evaluator':'POK Standard');await expect(page.getByTestId('equity-result')).toContainText('990 outcomes');const r=(await results(page)).at(-1);expect(r.engineId).toBe(engine);expect(r.status).toBe('COMPLETE');expect(r.location).toBe('browser-worker');
  }
  expect(faults.get(page)!.wasm).toBeGreaterThan(0);
  await page.getByRole('button',{name:'Compare engines',exact:true}).click();await expect(page.getByRole('region',{name:'Engine comparison'})).toContainText('Exact agreement within tolerance');
  const r=(await results(page)).slice(-2);expect(r[0].inputHash).toBe(r[1].inputHash);expect(r[0].result.equity).toBe(r[1].result.equity);expect(r[0].counts.completed).toBe(990);
  const inputs=await page.evaluate(()=>(window as any).engineEvidence.requests);for(const request of inputs){expect(request).not.toHaveProperty('deck');expect(request).not.toHaveProperty('log');expect(request).not.toHaveProperty('future');expect(request.dead).toEqual([])}
  await snap(page,'engines-light-comparison');evidence.push({comparisons:r.map(x=>({engine:x.engineId,equity:x.result.equity,states:x.counts.completed,elapsedMs:x.elapsedMs,overheadMs:x.overheadMs,hash:x.inputHash})),sharedSampler:true});
});
test('PH load failure is explicit, unavailable native stays catalog-only, invalid cards preserve the scenario',async({page,context})=>{
  await nav(page,'Odds Lab');await context.route('**/engines/ph-evaluator.wasm',r=>r.fulfill({status:503,body:'test-owned unavailable fixture'}));await page.getByLabel('Analysis engine').selectOption('pok-ph');await page.getByRole('button',{name:'Calculate equity',exact:true}).click();await expect(page.getByRole('alert')).toContainText('HTTP 503');await expect(page.getByTestId('equity-result')).toHaveCount(0);await expect(page.getByLabel('Hero cards')).toHaveValue('As Ah');
  await page.getByRole('button',{name:'Use POK Standard',exact:true}).click();await expect(page.getByLabel('Analysis engine')).toHaveValue('pok-standard');await page.getByRole('button',{name:'Calculate equity',exact:true}).click();await expect(page.getByTestId('equity-result')).toContainText('990 outcomes');
  await page.locator('.engine-control > details > summary').click();await page.getByText('Other engines and requirements',{exact:true}).click();await expect(page.locator('.engine-choices')).toContainText('Not connected to this static browser preview');expect(await page.getByLabel('Analysis engine').locator('option[value="ompeval-native"]').count()).toBe(0);
  await page.getByLabel('Hero cards').fill('As As');await page.getByRole('button',{name:'Calculate equity',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Duplicate');await expect(page.getByLabel('Hero cards')).toHaveValue('As As');
});
test('selection and cancel terminate real work; fixed-budget latency and responsiveness are measured',async({page})=>{
  await nav(page,'Odds Lab');await page.getByLabel('Board cards').fill('');await page.getByLabel('Opponents',{exact:true}).selectOption('5');for(let i=1;i<=5;i++)await page.getByLabel(`Opponent ${i} range`).fill('random');await page.getByLabel('Calculation method').selectOption('monte-carlo');await page.getByLabel('Sample budget').selectOption('50000');await page.getByLabel('Analysis engine').selectOption('pok-ph');
  await page.getByRole('button',{name:'Calculate equity',exact:true}).evaluate(b=>{(b as HTMLButtonElement).click();(b as HTMLButtonElement).click()});await expect(page.getByRole('button',{name:'Cancel calculation'})).toBeVisible();const start=Date.now();await page.getByLabel('Analysis engine').selectOption('pok-standard');await expect(page.getByRole('button',{name:'Cancel calculation'})).toHaveCount(0);const cancelMs=Date.now()-start;await expect(page.getByTestId('equity-result')).toHaveCount(0);
  await page.getByLabel('Sample budget').selectOption('10000');const metrics=[];
  for(const engine of ['pok-standard','pok-ph'])for(let repetition=0;repetition<3;repetition++){
    await page.getByLabel('Analysis engine').selectOption(engine);await page.evaluate(()=>{(window as any).frameProbe={running:true,last:performance.now(),gaps:[]};function tick(now:number){const s=(window as any).frameProbe;s.gaps.push(now-s.last);s.last=now;if(s.running)requestAnimationFrame(tick)}requestAnimationFrame(tick)});
    const started=Date.now();await page.getByRole('button',{name:'Calculate equity',exact:true}).click();await expect(page.getByTestId('equity-result')).toContainText('MONTE CARLO ESTIMATE');const elapsed=Date.now()-started;const gaps:number[]=await page.evaluate(()=>{(window as any).frameProbe.running=false;return (window as any).frameProbe.gaps});const output=(await results(page)).at(-1);expect(output.result.samples).toBe(10000);expect(output.result.confidence).toBe(.95);metrics.push({engine,repetition,endToEndMs:elapsed,workerElapsedMs:output.elapsedMs,overheadMs:output.overheadMs,equity:output.result.equity,samples:output.result.samples,frameGapP95Ms:gaps.sort((a,b)=>a-b)[Math.floor(gaps.length*.95)],frameMaxMs:Math.max(...gaps)});
  }
  evidence.push({cancelUiMs:cancelMs,metrics});await writeFile('artifacts/engine-browser-benchmarks.json',JSON.stringify({measuredAt:new Date().toISOString(),plan:'3 fixed repetitions per engine; fresh worker every calculation; same seeded sampler; no rerun-to-pass',metrics,cancelUiMs:cancelMs},null,2));
  await page.getByRole('button',{name:'Calculate equity',exact:true}).click();await page.getByRole('button',{name:'Cancel calculation',exact:true}).click();await expect(page.getByTestId('equity-result')).toHaveCount(0);
});
test('preview storage is separate; theme, text and RTL changes preserve analysis and migration data',async({page})=>{
  await page.evaluate(async()=>{localStorage.setItem('pok:appearance:v1',JSON.stringify({sentinel:'normal-notebook'}));await new Promise<void>((resolve,reject)=>{const r=indexedDB.open('hil-study-v1',1);r.onupgradeneeded=()=>r.result.createObjectStore('state');r.onerror=()=>reject(r.error);r.onsuccess=()=>{const t=r.result.transaction('state','readwrite');t.objectStore('state').put({sentinel:'normal-notebook'},'hil:session');t.oncomplete=()=>{r.result.close();resolve()}}})});
  await nav(page,'Settings');const legacy={schema:1,revision:0,settings:{locale:'en',seats:6,stack:1000,smallBlind:5,bigBlind:10,mode:'learn',advanced:false,reducedMotion:false,speed:650},hand:null,hands:[],attempts:[],scenarios:[],onboarded:true};await page.getByLabel('Import backup',{exact:true}).setInputFiles({name:'hil-v1-test.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(legacy))});await page.getByRole('dialog').getByRole('button',{name:'Confirm',exact:true}).click();
  await nav(page,'Odds Lab');await page.getByLabel('Analysis engine').selectOption('pok-ph');await page.getByRole('button',{name:'Compare engines',exact:true}).click();await expect(page.getByRole('region',{name:'Engine comparison'})).toContainText('Exact agreement');
  await page.getByRole('button',{name:'Appearance',exact:true}).click();const drawer=page.locator('.appearance-drawer[open]');await drawer.getByRole('button',{name:'Dark',exact:true}).click();for(let i=0;i<5;i++)await drawer.getByRole('button',{name:'Increase text size',exact:true}).click();await expect(drawer.locator('output')).toHaveText('200%');await page.keyboard.press('Escape');await expect(page.getByTestId('engine-attribution')).toContainText('POK + PH');await snap(page,'engines-dark-200');
  await page.getByRole('button',{name:'Appearance',exact:true}).click();await page.locator('.appearance-drawer[open]').getByRole('button',{name:'Reset appearance',exact:true}).click();await page.keyboard.press('Escape');await page.setViewportSize({width:430,height:900});await page.getByLabel('Language',{exact:true}).selectOption('ar');await expect(page.locator('html')).toHaveAttribute('dir','rtl');await expect(page.getByLabel('Analysis engine')).toHaveValue('pok-ph');await expect(page.getByTestId('equity-result')).toContainText('990');await snap(page,'strategy-equity-rtl-small');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
  for(const locale of Object.keys(catalogs)){await page.getByLabel('Language',{exact:true}).selectOption(locale);await expect(page.locator('.engine-control')).toContainText((catalogs as any)[locale].engine)}
  await page.reload({waitUntil:'networkidle'});const normal=await page.evaluate(async()=>({appearance:JSON.parse(localStorage.getItem('pok:appearance:v1')!),notebook:await new Promise(resolve=>{const r=indexedDB.open('hil-study-v1');r.onsuccess=()=>{const g=r.result.transaction('state').objectStore('state').get('hil:session');g.onsuccess=()=>{resolve(g.result);r.result.close()}}})}));expect(normal).toEqual({appearance:{sentinel:'normal-notebook'},notebook:{sentinel:'normal-notebook'}});expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('pok:strategy-validation:appearance:v1')!).textScale)).toBe(defaultAppearance.textScale);
});
