import {describe,it,expect} from 'vitest';
import catalog from '../fixtures/strategy/scenarios.json';
import {scenarioRequest} from '../src/strategy/scenario';
import {validateSolveRequest,solveHash,validateSolveResult,validatePack,digest,decisionRegret} from '../src/strategy/contract';
import {canonicalSolveResult,nativeSolveRequest,javaAvailability,runJavaSolver} from '../server/strategy-adapter';
import {readFile} from 'node:fs/promises';
import packs from '../public/strategy/packs.json';
const base=()=>scenarioRequest(catalog.scenarios[0]);
describe('versioned river solve boundary',()=>{
 it('rejects a one-chip pot before invoking the native adapter',()=>{const r=base();r.pot=1;expect(()=>validateSolveRequest(r)).toThrow();r.pot=2;expect(validateSolveRequest(r).pot).toBe(2)});
 it.each(catalog.scenarios.map(s=>[s.id,s] as const))('accepts original weighted scenario %s',(_id,s)=>{expect(scenarioRequest(s).players).toHaveLength(2)});
 it('rejects duplicate boards, blocked ranges and impossible assignments',()=>{for(const edit of [(r:any)=>r.board[1]=r.board[0],(r:any)=>r.players[0].combinations[0].cards[0]=r.board[0],(r:any)=>r.players[1].combinations=r.players[0].combinations=[{cards:['As','Ah'],weight:1}]]){const r=base();edit(r);expect(()=>validateSolveRequest(r)).toThrow()}});
 it('rejects hostile unknown fields, NaN, oversized inputs and unsupported scope',()=>{for(const edit of [(r:any)=>r.shell='calc.exe',(r:any)=>r.players[0].combinations[0].weight=NaN,(r:any)=>r.pot=Infinity,(r:any)=>r.players.push(r.players[0]),(r:any)=>r.board.pop(),(r:any)=>r.budget.iterations=1e9,(r:any)=>r.budget.threads=12,(r:any)=>r.informationScope='live-deck',(r:any)=>r.tree.maxRaises=5]){const r=base();edit(r);expect(()=>validateSolveRequest(r)).toThrow()}});
 it('requires a displayed hand in its explicit range',()=>{const r=base();r.learner.cards=['As','Ah'];expect(()=>validateSolveRequest(r)).toThrow()});
 it('preserves relative weights and explicitly removes zero-weight combinations at native boundary',()=>{const r=base();r.players[0].combinations[0].weight=0;const native=nativeSolveRequest(r);expect(native.ranges[0]).toHaveLength(r.players[0].combinations.length-1);const positive=r.players[0].combinations.filter(c=>c.weight>0);expect(native.ranges[0][0].weight/native.ranges[0][1].weight).toBeCloseTo(positive[0].weight/positive[1].weight,12)});
 it('hashes tree, ranges, engine precision and revisions but not transport IDs',async()=>{const r=base(),s=structuredClone(r);s.requestId='another';s.analysisRevision++;expect(await solveHash(s)).toBe(await solveHash(r));s.pot++;expect(await solveHash(s)).not.toBe(await solveHash(r));s.pot--;s.budget.iterations++;expect(await solveHash(s)).not.toBe(await solveHash(r))});
 it('rejects duplicate reversed combinations and short raises outside the model',()=>{const r=base();r.players[0].combinations.push({...r.players[0].combinations[0],cards:[...r.players[0].combinations[0].cards].reverse()});expect(()=>validateSolveRequest(r)).toThrow();const s=base();s.tree={betSizes:[50],raiseTo:[70],maxRaises:1};s.effectiveStack=70;expect(()=>validateSolveRequest(s)).toThrow()});
 it.each(['missing-node','duplicate-hand','false-verification','illegal-action'])('rejects forged self-checksummed pack: %s',async variant=>{const p=structuredClone(packs[0]) as any;if(variant==='missing-node')p.result.nodes=p.result.nodes.slice(0,1);if(variant==='duplicate-hand')p.result.nodes[0].hands[1]=p.result.nodes[0].hands[0];if(variant==='false-verification'){p.verification.gap=123;p.verification.value=-999}if(variant==='illegal-action')p.result.nodes[0].actions[0]='RAISE 9999';const {checksum:_,...body}=p;p.checksum=await digest(body);await expect(validatePack(p)).rejects.toThrow()});
 it('rejects tiny weight ratios explicitly and incompatible single combos',()=>{const r=base();r.players[0].combinations[0].weight=1e-30;expect(()=>validateSolveRequest(r)).toThrow(/Weight ratios/);const s=base();s.players[1].combinations=[{cards:['As','Ah'],weight:1}];s.players[0].combinations.push({cards:['As','Kh'],weight:1});expect(()=>validateSolveRequest(s)).toThrow(/compatible opponent/)});
});
describe('real installed Java execution (not a mock)',()=>{
 it('verifies fixed artifacts, solves a weighted information-set model and returns attributed strategies',async()=>{expect((await javaAvailability()).available).toBe(true);const r=base();r.budget.iterations=2000;const result=await runJavaSolver(r,{signal:new AbortController().signal,onProgress:()=>{}});expect(result.inputHash).toBe(await solveHash(r));expect(result.nodes[0].hands.length).toBe(r.players[0].combinations.length);expect(result.metric!.value).toBeLessThan(2);expect(result.trace.length).toBeGreaterThan(1);expect(Math.abs(result.rootValues[0]+result.rootValues[1])).toBeLessThan(1e-5);validateSolveResult(result,r);expect(()=>decisionRegret(result,'root',r.learner.cards,'BET 777')).toThrow(/Out of model/);const body={schemaVersion:1 as const,id:'real-java-test',version:1,title:'Real test solve',explanation:'A bounded development fixture.',request:r,result,verification:{method:'Solver reported; independent oracle covered separately',gap:result.metric!.value,value:result.rootValues[0],tolerance:0.001}};const pack={...body,checksum:await digest(body)};expect((await validatePack(pack)).id).toBe(body.id);pack.title='Tampered';await expect(validatePack(pack)).rejects.toThrow(/checksum/);},20000);
 it('cancels an owned JVM job without completing a result',async()=>{const c=new AbortController(),r=base();r.budget.iterations=20000;const promise=runJavaSolver(r,{signal:c.signal,onProgress:()=>c.abort()});setTimeout(()=>c.abort(),1200);await expect(promise).rejects.toThrow(/cancel/);},20000);
 it('rejects malformed and mismatched native results',async()=>{const r=base();const raw=JSON.parse(await readFile('engine-adapters/java/example-result.json','utf8'));raw.upstreamRevision='fake';await expect(canonicalSolveResult(raw,r,100)).rejects.toThrow();});
 it('never describes an interrupted result as a finished budget even when its gap meets target',async()=>{const q=JSON.parse(await readFile('engine-adapters/java/example-request.json','utf8')),raw=JSON.parse(await readFile('engine-adapters/java/example-result.json','utf8'));const r=scenarioRequest({request:q,hero:{actor:0,cards:q.ranges[0][0].cards}});r.targetGap=10000;for(const status of ['PARTIAL','TIMEOUT']){const result=await canonicalSolveResult({...raw,status},r,100);expect(result.status).toBe('PARTIAL');expect(result.completionReason).toContain('before completing');expect(result.completionReason).not.toContain('gap meets target')}});
});
