import {test,expect,type Page} from '@playwright/test';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
const screenshots='artifacts/solver/screenshots';
async function capture(page:Page,name:string){await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:screenshots+'/'+name+'.png',fullPage:true,animations:'disabled'})}
test.beforeEach(async({context})=>{await context.route('**/*',r=>{const u=new URL(r.request().url());return ['localhost','127.0.0.1','[::1]'].includes(u.hostname)||['blob:','data:'].includes(u.protocol)?r.continue():r.abort('blockedbyclient')});await mkdir(screenshots,{recursive:true})});
async function enter(page:Page){await page.goto('./');await page.getByRole('button',{name:'Explore first',exact:true}).click();await page.getByRole('button',{name:'Strategy Lab Advanced',exact:false}).click();await expect(page.getByTestId('strategy-study')).toBeVisible()}
test('six actual saved solutions offline; decisions, pack round-trip, hostile import and independent preview notebook',async({page})=>{
 const network:string[]=[];page.on('request',r=>network.push(r.url()));await enter(page);const choices=page.getByRole('combobox',{name:'Choose a scenario',exact:true});await expect(choices.locator('option:not([disabled])')).toHaveCount(6);
 for(let i=0;i<6;i++){await choices.selectOption({index:i+1});await expect(page.getByTestId('strategy-quality')).toContainText('Complete');await page.getByRole('button',{name:'Show strategy and explanation',exact:true}).click();await expect(page.getByTestId('strategy-answer')).toContainText('Action EV');await page.getByRole('button',{name:'Hide strategy',exact:true}).click()}
 await choices.selectOption({index:1});await page.getByTestId('strategy-study').getByRole('button',{name:'Check',exact:true}).click();await expect(page.getByTestId('strategy-answer')).toContainText('EV difference');
 const downloading=page.waitForEvent('download');await page.getByRole('button',{name:'Export study pack',exact:true}).click();const download=await downloading,path=await download.path();const raw=await readFile(path!,'utf8');expect(JSON.parse(raw).result.nodes.length).toBeGreaterThan(3);await page.getByLabel('Import study pack',{exact:true}).setInputFiles({name:'pack.json',mimeType:'application/json',buffer:Buffer.from(raw)});await expect(page.getByTestId('strategy-lab')).toContainText('Imported verification statements');
 const bad=JSON.parse(raw);bad.title='<script>alert(1)</script>';await page.getByLabel('Import study pack',{exact:true}).setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(bad))});await expect(page.getByRole('alert')).toContainText('Invalid pack metadata');
 expect(network.some(u=>u.includes('/api/'))).toBe(false);expect(network.every(u=>new URL(u).hostname==='localhost')).toBe(true);await page.reload();await page.getByRole('button',{name:'Strategy Lab Advanced',exact:false}).click();await expect(page.getByRole('combobox',{name:'Choose a scenario',exact:true}).locator('option:not([disabled])')).toHaveCount(6);
});
test('readable light/dark, 200% text, RTL/narrow, keyboard and edits invalidate the matching answer',async({page})=>{
 await enter(page);await page.getByRole('button',{name:'Show strategy and explanation',exact:true}).click();await capture(page,'strategy-light');
 await page.getByRole('button',{name:'Appearance',exact:true}).click();await page.getByRole('button',{name:'Dark',exact:true}).click();await page.keyboard.press('Escape');await capture(page,'strategy-dark');
 await page.getByRole('button',{name:'Appearance',exact:true}).click();for(let i=0;i<5;i++)await page.getByRole('button',{name:'Increase text size',exact:true}).click();await page.keyboard.press('Escape');await capture(page,'strategy-text-200');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
 await page.getByRole('button',{name:'Appearance',exact:true}).click();await page.getByRole('button',{name:'Reset appearance',exact:true}).click();await page.keyboard.press('Escape');await page.setViewportSize({width:430,height:900});await page.getByLabel('Language',{exact:true}).selectOption('ar');await expect(page.locator('html')).toHaveAttribute('dir','rtl');await expect(page.getByTestId('strategy-lab')).toContainText('English');await capture(page,'strategy-rtl');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
 await page.getByLabel('Language',{exact:true}).selectOption('en');await page.getByText('Edit a river scenario',{exact:true}).click();await page.getByLabel('Starting pot',{exact:true}).fill('101');await page.getByRole('button',{name:'Apply scenario edits',exact:true}).click();await expect(page.getByTestId('strategy-study')).toHaveCount(0);await expect(page.getByTestId('strategy-lab')).toContainText('Scenario edits applied');
});
test('authenticated built staging page executes JVM, cancels, rejects stale answers and reports service unavailable',async({page,context})=>{
 const base='http://127.0.0.1:4322',email=`solver-ui-${Date.now()}@example.test`,password='isolated-test-only-12345';
 const post=async(path:string,body:any)=>context.request.post(base+path,{headers:{Origin:base},data:body});
 expect((await post('/api/auth/sign-up/email',{email,name:'River learner',password,adultAccepted:true})).ok()).toBe(true);
 const mails=await(await context.request.get(base+'/api/dev/mail?email='+encodeURIComponent(email))).json();const list=Array.isArray(mails)?mails:mails.items??mails.messages;expect(list?.length).toBeGreaterThan(0);await context.request.get(list[0].url);
 expect((await post('/api/auth/sign-in/email',{email,password})).ok()).toBe(true);
 await page.goto(base+'/holdem-lab/');await page.getByRole('button',{name:'Explore first',exact:true}).click();await page.getByRole('button',{name:'Strategy Lab Advanced',exact:false}).click();await expect(page.getByText('Ready',{exact:true})).toBeVisible();await page.getByLabel('I permit this bounded calculation on the configured local solver.').check();
 const start=Date.now();await page.getByRole('button',{name:'Solve locally',exact:true}).click();await expect(page.getByTestId('strategy-lab')).toContainText('Fresh local result');await expect(page.getByTestId('strategy-quality')).toContainText('Complete');const latency=Date.now()-start;await capture(page,'strategy-live-jvm');
 await page.getByLabel('I permit this bounded calculation on the configured local solver.').check();await page.getByRole('button',{name:'Solve locally',exact:true}).click();await page.getByRole('button',{name:'Cancel solve',exact:true}).click();await expect(page.getByTestId('strategy-lab')).toContainText('Calculation cancelled');await expect(page.getByRole('button',{name:'Solve locally',exact:true})).toBeEnabled();
 await context.route('**/api/strategy/health',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({available:false,reason:'Test-owned unavailable service response',location:'local-jvm',engine:'Java',limits:{jobs:1,iterations:20000,timeMs:15000,memoryMiB:512}})}));await page.getByRole('button',{name:'Check local solver',exact:true}).click();await expect(page.getByRole('button',{name:'Solve locally',exact:true})).toBeDisabled();await expect(page.getByTestId('strategy-study')).toBeVisible();
 await writeFile('artifacts/solver/browser-live-solve.json',JSON.stringify({observedAt:new Date().toISOString(),actualJVM:true,totalUILatencyMs:latency,browser:context.browser()?.version(),network:'Only loopback allowed',unavailableTransport:'Explicit test-owned HTTP fixture; actual JVM used for solve/cancel'},null,2));
});
