import {describe,it,expect} from 'vitest';
import {createPlatform} from '../server/app';
import {mountStrategyRoutes} from '../server/strategy-routes';
import {StrategyJobs,type SolverRunner} from '../server/strategy-jobs';
import {DatabaseSync} from 'node:sqlite';
import {scenarioRequest} from '../src/strategy/scenario';
import scenarios from '../fixtures/strategy/scenarios.json';
const base='http://127.0.0.1:4320';
const request=()=>scenarioRequest(scenarios.scenarios[0]);
const blocked:SolverRunner=(_r,{signal})=>new Promise((_resolve,reject)=>{signal.addEventListener('abort',()=>reject(Error('cancelled')),{once:true})});
const pause=(ms=15)=>new Promise(r=>setTimeout(r,ms));
describe('persistent solver queue contracts (controlled transport)',()=>{
 it('deduplicates retries, protects ownership, bounds queue and cancels running/queued jobs',async()=>{const db=new DatabaseSync(':memory:'),jobs=new StrategyJobs(db,blocked);const r=request(),a=await jobs.submit('a',r);expect((await jobs.submit('a',r)).id).toBe(a.id);await expect(jobs.submit('a',{...r,pot:r.pot+1})).rejects.toThrow('idempotency_conflict');expect(()=>jobs.get(a.id,'b')).toThrow('not_found');await expect(jobs.submit('a',request())).rejects.toThrow('one_active');await pause();expect(jobs.get(a.id,'a').state).toBe('running');for(const owner of ['b','c','d'])await jobs.submit(owner,request());await expect(jobs.submit('e',request())).rejects.toThrow('queue_full');expect(jobs.cancel(a.id,'a').state).toBe('cancelled');jobs.stop();await pause();db.close()});
 it('marks unfinished jobs failed on restart and never resumes falsely',async()=>{const db=new DatabaseSync(':memory:'),jobs=new StrategyJobs(db,blocked),job=await jobs.submit('a',request());await pause();jobs.cancel(job.id,'a');await pause();db.prepare("UPDATE pok_strategy_job SET state='running' WHERE id=?").run(job.id);const restored=new StrategyJobs(db,blocked);expect(restored.get(job.id,'a')).toMatchObject({state:'failed',error:'server_restarted_restart_only'});jobs.stop();restored.stop();await pause();db.close()});
 it('enforces hourly budget atomically and deletes only requested private records',async()=>{const db=new DatabaseSync(':memory:'),jobs=new StrategyJobs(db,blocked);for(let n=0;n<12;n++){const j=await jobs.submit('a',request());jobs.cancel(j.id,'a')}await expect(jobs.submit('a',request())).rejects.toThrow('budget');const b=await jobs.submit('b',request());jobs.deleteOwner('a');expect(jobs.get(b.id,'b').state).toBe('queued');jobs.stop();await pause();db.close()});
 it('rejects malformed result without committing a completed answer',async()=>{const db=new DatabaseSync(':memory:'),jobs=new StrategyJobs(db,async()=>({status:'COMPLETE'} as any)),j=await jobs.submit('a',request());await pause(80);expect(jobs.get(j.id,'a')).toMatchObject({state:'failed',result:null});jobs.stop();await pause();db.close()});
 it('retains anonymous quota counts after account deletion and prunes private expired results during operation',async()=>{const db=new DatabaseSync(':memory:');let now=Date.now();const jobs=new StrategyJobs(db,blocked,()=>now),a=await jobs.submit('a',request());jobs.cancel(a.id,'a');jobs.deleteOwner('a');expect((db.prepare('SELECT count(*) n FROM pok_strategy_usage WHERE user_id IS NULL').get() as any).n).toBe(1);const b=await jobs.submit('b',request());jobs.cancel(b.id,'b');now+=8*86400000;await jobs.submit('c',request());expect(()=>jobs.get(b.id,'b')).toThrow('not_found');expect((db.prepare('SELECT count(*) n FROM pok_strategy_usage').get() as any).n).toBe(1);jobs.stop();await pause();db.close()});
});
describe('real SQLite / BetterAuth solver route security, controlled runner',()=>{
 it('enforces session, origin, CSRF, IDOR, owner-only diagnostics and immediate revocation',async()=>{let jobs!:StrategyJobs;const p=await createPlatform({dbPath:':memory:',baseURL:base,secret:'isolated-solver-auth-test-secret-123456789',mode:'test',testMail:true,configure:(app,c)=>{jobs=mountStrategyRoutes(app,c,blocked)}});
 const call=(path:string,method='GET',body?:unknown,cookie='',csrf='',origin=base)=>p.app.request(base+path,{method,headers:{cookie,Origin:origin,'Content-Type':'application/json','X-POK-CSRF':csrf},...(method==='GET'?{}:{body:JSON.stringify(body??{})})});
 const member=async(email:string)=>{await call('/api/auth/sign-up/email','POST',{email,name:'Solver tester',password:'isolated-only-test-password',adultAccepted:true});await p.app.request(p.mailSink.find(m=>m.to===email)!.url);const login=await call('/api/auth/sign-in/email','POST',{email,password:'isolated-only-test-password'});const cookie=login.headers.getSetCookie().map(x=>x.split(';')[0]).join('; ');const me=await(await call('/api/me','GET',undefined,cookie)).json();return {cookie,csrf:me.csrf,id:me.user.id}};
 try{expect((await call('/api/strategy/jobs','POST',request())).status).toBe(401);const a=await member('solver-a@example.test'),b=await member('solver-b@example.test');expect((await call('/api/strategy/jobs','POST',request(),a.cookie,'bad')).status).toBe(403);expect((await call('/api/strategy/jobs','POST',request(),a.cookie,a.csrf,'https://untrusted.invalid')).status).toBe(403);expect((await p.app.request('http://evil.invalid/api/strategy/health',{headers:{cookie:a.cookie}})).status).toBe(403);
 const reply=await call('/api/strategy/jobs','POST',request(),a.cookie,a.csrf);expect(reply.status).toBe(202);const job=await reply.json();expect((await call('/api/strategy/jobs/'+job.id,'GET',undefined,b.cookie)).status).toBe(404);expect((await call('/api/strategy/jobs/'+job.id+'/cancel','POST',{},b.cookie,b.csrf)).status).toBe(404);expect((await call('/api/strategy/admin/health','GET',undefined,a.cookie)).status).toBe(403);
 p.db.prepare("UPDATE pok_profile SET role='owner' WHERE user_id=?").run(a.id);expect((await call('/api/strategy/admin/health','GET',undefined,a.cookie)).status).toBe(200);await call('/api/auth/revoke-sessions','POST',{},a.cookie,a.csrf);expect((await call('/api/strategy/jobs/'+job.id,'GET',undefined,a.cookie)).status).toBe(401);
 }finally{jobs.stop();await pause();p.close()}
 });
});
