import { spawn, type ChildProcessWithoutNullStreams } from 'node:child_process';
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { randomBytes, createHash } from 'node:crypto';
import assert from 'node:assert/strict';
import { performance } from 'node:perf_hooks';
import { parseCards, shuffledDeck, cardText } from '../../src/cards';
import { referenceEvaluate } from '../../src/evaluator';

const root=fileURLToPath(new URL('../../',import.meta.url));
const runtime=JSON.parse(await readFile(root+'.pok-strategy/runtime.json','utf8'));
const java=runtime.javaPath as string;
const shell=runtime.guardShell as string;
const jar=root+'.solver-tools/java-build/pok-river-solver.jar';
const classpath=jar+';'+root+'.solver-tools/java-deps/*';
function collect(child:ChildProcessWithoutNullStreams,limit=2_500_000){let stdout='',stderr='',bytes=0;const closed=new Promise<{code:number|null;stdout:string;stderr:string}>(resolve=>{child.stdout.on('data',b=>{bytes+=b.length;if(bytes>limit)child.kill();else stdout+=b.toString()});child.stderr.on('data',b=>{if(stderr.length<16000)stderr+=b.toString()});child.on('close',code=>resolve({code,stdout,stderr}));});return closed;}
function javaChild(token:string){return spawn(java,['-Xms32m','-Xmx256m','-XX:MaxMetaspaceSize=128m','-XX:ReservedCodeCacheSize=64m','-XX:ActiveProcessorCount=1','-XX:+UseSerialGC','-Djava.awt.headless=true','-Dpok.ownerToken='+token,'-cp',classpath,'pok.solver.PokRiverMain'],{cwd:root+'.solver-tools/java-build',shell:false,windowsHide:true});}
async function attach(child:ChildProcessWithoutNullStreams,token:string){const guard=spawn(shell,['-NoProfile','-File',root+'engine-adapters/java/Guard-Solver.ps1','-ChildPid',String(child.pid),'-OwnerToken',token],{shell:false,windowsHide:true});const closed=collect(guard);const ready=await new Promise<any>((resolve,reject)=>{let buffer='';const timer=setTimeout(()=>{guard.kill();reject(Error('guard_timeout'))},8000);guard.stdout.on('data',chunk=>{buffer+=chunk;const line=buffer.split('\n').find(l=>l.includes('"type":"ready"'));if(line){clearTimeout(timer);resolve(JSON.parse(line));}});guard.on('close',()=>{clearTimeout(timer);reject(Error('guard_failed:'+buffer))});});assert.equal(ready.memoryLimitBytes,536870912);assert.equal(ready.killOnClose,true);return {guard,closed};}
async function run(input:unknown,guarded=false){const token=randomBytes(32).toString('hex'),child=javaChild(token),closed=collect(child);const timeout=setTimeout(()=>child.kill(),19000);let guard:Awaited<ReturnType<typeof attach>>|undefined;try{if(guarded)guard=await attach(child,token);child.stdin.end(typeof input==='string'?input:JSON.stringify(input));const result=await closed;if(guard){guard.guard.stdin.end();const g=await guard.closed;assert.equal(g.code,0);const measured=JSON.parse(g.stdout.trim().split('\n').at(-1)!);assert(measured.peakProcessCommittedBytes>0);guard=undefined;}const frames=result.stdout.trim().split('\n').map(x=>JSON.parse(x));return {result:frames.at(-1),frames,code:result.code,stderr:result.stderr};}finally{clearTimeout(timeout);child.kill();guard?.guard.kill();}}
const evidence:any={schemaVersion:1,checkedUtc:new Date().toISOString(),tests:[],limits:{heapMiB:256,metaspaceMiB:128,codeCacheMiB:64,osProcessCommittedMiB:512,computeThreads:1}};
async function test(name:string,fn:()=>Promise<void>){const t=performance.now();await fn();evidence.tests.push({name,status:'PASS',elapsedMs:performance.now()-t});}
const example=JSON.parse(await readFile(root+'engine-adapters/java/example-request.json','utf8'));
await test('actual JVM info and queried OS job bounds',async()=>{const a=await run({schema:1,op:'info'},true);assert.equal(a.code,0);assert.equal(a.result.engine,'TexasHoldemSolverJava');});
await test('closing owner guard terminates only attached waiting JVM',async()=>{const token=randomBytes(32).toString('hex'),child=javaChild(token),closed=collect(child),guard=await attach(child,token);const timer=setTimeout(()=>child.kill(),3000);guard.guard.stdin.end();const result=await closed;clearTimeout(timer);await guard.closed;assert.equal(result.stdout,'');assert(!child.stdin.writableEnded);});
await test('mismatched ownership token cannot attach to the child',async()=>{const child=javaChild(randomBytes(32).toString('hex')),closed=collect(child);const bad=spawn(shell,['-NoProfile','-File',root+'engine-adapters/java/Guard-Solver.ps1','-ChildPid',String(child.pid),'-OwnerToken',randomBytes(32).toString('hex')],{shell:false,windowsHide:true}),guard=await collect(bad);assert.equal(guard.code,2);assert(guard.stdout.includes('child_ownership_unverified'));child.stdin.end(JSON.stringify({schema:1,op:'info'}));assert.equal((await closed).code,0);});
await test('real weighted river and finite normalized complete policies',async()=>{const a=await run(example,true);assert.equal(a.result.ok,true);assert.equal(a.result.iterations,5000);assert.equal(a.result.compatibleAssignments,16);for(const n of a.result.nodes.filter((n:any)=>n.kind==='ACTION'))for(const h of n.policies){assert(Math.abs(h.probabilities.reduce((a:number,b:number)=>a+b,0)-1)<1e-10);assert(h.informationSetReach>=0&&h.informationSetReach<=1);assert(h.actionEvChips.every(Number.isFinite));}assert(Math.abs(a.result.profileEvChips[0]+a.result.profileEvChips[1])<1e-10);await writeFile(root+'engine-adapters/java/example-result.json',JSON.stringify(a.result)+'\n');});
await test('all nine categories, wheel, kickers, board ties and 10000 generated hands match independent POK reference',async()=>{const specials=['As Kd Qh Jc 9s','As Ad Qh Jc 9s','As Ad Qh Qc 9s','As Ad Ah Jc 9s','As 2d 3h 4c 5s','As Js 8s 5s 2s','As Ad Ah Jc Js','As Ad Ah Ac Js','As Ks Qs Js Ts','Ac Kc Qc Jc Tc','As Ad Qh Jc 8s'].map(parseCards);const hands=[...specials,...Array.from({length:10000},(_,i)=>shuffledDeck(61701+i).slice(0,5+i%3))];const ranks:number[]=[];for(let start=0;start<hands.length;start+=2000){const a=await run({schema:1,op:'evaluate',hands:hands.slice(start,start+2000).map(h=>h.map(cardText))});assert.equal(a.code,0);ranks.push(...a.result.ranks);}assert.deepEqual(ranks,hands.map(referenceEvaluate));await writeFile(root+'artifacts/java-rank-corpus.json',JSON.stringify({schemaVersion:1,seed:61701,hands:hands.map((h,i)=>({cards:h.map(cardText),javaScore:ranks[i]}))}));});
await test('all hands playing the royal board produce zero centered profile value',async()=>{const a=await run({...example,board:['As','Ks','Qs','Js','Ts'],ranges:[[{cards:['2c','3d'],weight:1},{cards:['4c','5d'],weight:.3}],[{cards:['6c','7d'],weight:1},{cards:['8c','9d'],weight:.5}]],iterations:2000});assert(a.result.nashConvChips>=-1e-4);assert(Math.abs(a.result.profileEvChips[0])<.05);assert(a.result.nodes.length===9);});
await test('duplicates, excessive depth, paths, weights, impossible cards and oversized inputs fail closed',async()=>{const invalid:any[]=[{...example,path:'C:\\private'},{...example,board:['2c','2c','Jh','9s','Tc']},{...example,ranges:[[{cards:['As','Ah'],weight:-1}],example.ranges[1]]},{...example,ranges:[[{cards:['As','Ah'],weight:1}],[{cards:['As','Kh'],weight:1}]]},{...example,iterations:20001},'{"schema":1,"schema":1,"op":"info"}','['.repeat(20)+']'.repeat(20),' '.repeat(131073),'{"schema":1,"op":"info"} {"extra":1}'];for(const request of invalid){const a=await run(request);assert.equal(a.code,2);assert.equal(a.result.ok,false);}});
await test('bounded deadline produces no completed strategy answer',async()=>{const r={...example,iterations:20000,deadlineMs:100,betSizes:[25,50],raiseTo:[150],maxRaises:1};const a=await run(r);assert.equal(a.code,2);assert.equal(a.result.ok,false);assert.equal(a.result.code,'deadline_exceeded');});
evidence.jarSha256=createHash('sha256').update(await readFile(jar)).digest('hex');evidence.passed=evidence.tests.length;
await writeFile(root+'engine-adapters/java/VERIFICATION.json',JSON.stringify(evidence,null,2)+'\n');console.log(JSON.stringify(evidence,null,2));
