import { Hono, type Context } from 'hono';
import {bodyLimit} from 'hono/body-limit';
import { DatabaseSync } from 'node:sqlite';
import { createHash, randomBytes, randomUUID, timingSafeEqual } from 'node:crypto';
import { readFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import { betterAuth } from 'better-auth';
import { getMigrations } from 'better-auth/db/migration';
import { twoFactor, genericOAuth } from 'better-auth/plugins';
import { APIError } from 'better-auth/api';
import { cleanName, scanMessage, seedDictionary, validateDictionary, type DictionaryEntry } from './moderation';
import { countries, providerRegistry, socialOptions, snapchatIdentity, googleNonceBinding, type ProviderSettings } from './providers';
import { defaults, validateData } from '../src/storage';
import {validateAppearance} from '../src/appearance';
import {isLocale,type Locale} from '../src/locales/metadata';
import {supportedLocales,getLocaleMetadata,translationCoverage} from '../src/i18n';

export type Mail = {to:string;purpose:'verify'|'reset'|'delete';url:string;createdAt:number;locale?:Locale};
export type PlatformConfig={dbPath:string;baseURL:string;secret:string;mode:'development'|'test'|'production';testMail?:boolean;sendMail?:(mail:Mail)=>Promise<void>;providers?:ProviderSettings;now?:()=>number;onAccountDeleted?:(id:string,db:DatabaseSync)=>void;configure?:(app:Hono,context:PlatformContext)=>void};
type Row=Record<string,any>;
export type PlatformContext={db:DatabaseSync;auth:{handler:(request:Request)=>Promise<Response>;api:{getSession:(input:{headers:Headers})=>Promise<any>}};requireUser:(c:Context,permission?:Permission)=>Promise<Row>;audit:(actor:string|null,target:string|null,action:string,reason:string,expiry?:number|null)=>void};
type Permission='moderate'|'support'|'content'|'configure'|'audit'|'users';
const permissions:Record<string,Permission[]>={owner:['moderate','support','content','configure','audit','users'],administrator:['moderate','support','content','configure','audit','users'],moderator:['moderate','content'],support:['support'],editor:['content'],member:[]};
class HttpError extends Error {constructor(public status:number,public code:string){super(code)}}
function assert(value:unknown,code='invalid_input',status=400):asserts value {if(!value)throw new HttpError(status,code)}
function str(v:unknown,max=2000,min=1){assert(typeof v==='string'&&v.trim().length>=min&&v.length<=max);assert(!/[<>\u0000-\u0008]/.test(v),'plain_text_only');return v.trim()}
function jsonSafe(value:unknown,max=1048576){const text=JSON.stringify(value);assert(text&&text.length<=max,'payload_too_large',413);assert(!/"(?:__proto__|constructor|prototype)"\s*:|<\/?(?:script|iframe|img|html)|javascript:/i.test(text),'unsafe_payload');return text}
const isWrite=(method:string)=>!['GET','HEAD','OPTIONS'].includes(method);
export async function createPlatform(config:PlatformConfig){
 const origin=new URL(config.baseURL).origin;const host=new URL(origin).hostname;const local=['localhost','127.0.0.1','[::1]'].includes(host);
 if(config.secret.length<32)throw Error('A dedicated authentication secret of at least 32 characters is required.');
 if(config.mode==='production'&&(config.testMail||!config.sendMail||new URL(origin).protocol!=='https:'))throw Error('Production requires HTTPS and real mail; the test sink is forbidden.');
 if(config.mode!=='production'&&!local)throw Error('Development and test editions must use a loopback origin.');
 if(config.dbPath!==':memory:')mkdirSync(dirname(config.dbPath),{recursive:true});const db=new DatabaseSync(config.dbPath);db.exec('PRAGMA foreign_keys=ON; PRAGMA journal_mode=WAL; PRAGMA busy_timeout=5000;');
 const now=config.now||Date.now;const mailSink:Mail[]=[];
 const deliver=async(mail:Mail)=>{if(schemaReady){const row=db.prepare('SELECT locale FROM user WHERE email=?').get(mail.to) as Row|undefined;if(row&&isLocale(row.locale))mail.locale=row.locale;}if(config.testMail){mailSink.push(mail);if(mailSink.length>200)mailSink.shift();}else if(config.sendMail){await config.sendMail(mail)}else throw Error('Mail transport is not configured');};
 let schemaReady=false;
 const auth=betterAuth({appName:'Poker Odds Knowledge',baseURL:origin,basePath:'/api/auth',secret:config.secret,database:db,trustedOrigins:[origin],
  logger:{disabled:true},rateLimit:{enabled:true,storage:'database',window:60,max:60,customRules:{'/sign-in/email':{window:60,max:10},'/sign-in/social':{window:60,max:10},'/sign-up/email':{window:60,max:5},'/request-password-reset':{window:60,max:5}}},
  advanced:{cookiePrefix:'pok',useSecureCookies:config.mode==='production',defaultCookieAttributes:{sameSite:'lax',httpOnly:true}},
  emailAndPassword:{enabled:true,minPasswordLength:12,maxPasswordLength:128,requireEmailVerification:true,autoSignIn:false,revokeSessionsOnPasswordReset:true,resetPasswordTokenExpiresIn:900,sendResetPassword:async({user,url})=>deliver({to:user.email,purpose:'reset',url,createdAt:now()})},
  emailVerification:{sendOnSignUp:true,expiresIn:1800,autoSignInAfterVerification:false,sendVerificationEmail:async({user,url})=>deliver({to:user.email,purpose:'verify',url,createdAt:now()})},
  session:{expiresIn:60*60*24*7,updateAge:60*60,freshAge:600,cookieCache:{enabled:false}},
  account:{encryptOAuthTokens:true,accountLinking:{enabled:true,disableImplicitLinking:true,trustedProviders:['snapchat'],allowDifferentEmails:true,allowUnlinkingAll:false}},
  user:{additionalFields:{locale:{type:'string',required:false,defaultValue:'en',input:true},adultAcceptedAt:{type:'number',required:false,defaultValue:0,input:false},adultPolicyVersion:{type:'string',required:false,defaultValue:'2026-09-30-v1',input:false}},deleteUser:{enabled:true,sendDeleteAccountVerification:async({user,url})=>deliver({to:user.email,purpose:'delete',url,createdAt:now()}),beforeDelete:async user=>{if(schemaReady){const p=db.prepare('SELECT role FROM pok_profile WHERE user_id=?').get(user.id) as Row|undefined;if(p?.role==='owner'&&(db.prepare("SELECT count(*) n FROM pok_profile WHERE role='owner'").get() as Row).n<=1)throw new APIError('FORBIDDEN',{message:'last_owner_protected'});db.prepare("UPDATE pok_content SET title='',body='[Account deleted]',hidden=1 WHERE author_id=?").run(user.id);config.onAccountDeleted?.(user.id,db);}},afterDelete:async user=>{audit(user.id,user.id,'account.delete','Account deletion confirmed');}}},
  databaseHooks:{user:{create:{before:async user=>({data:{...user,name:cleanName(user.name),locale:isLocale((user as Row).locale)?(user as Row).locale:'en',adultAcceptedAt:now(),adultPolicyVersion:'2026-09-30-v1'}})},update:{before:async user=>({data:{...user,...(user.name?{name:cleanName(user.name)}:{})}})}}},
  socialProviders:socialOptions(config.providers||{}),
  plugins:[twoFactor({issuer:'Poker Odds Knowledge'}),genericOAuth({config:config.providers?.snapchat?.approved&&config.providers.snapchat.clientId&&config.providers.snapchat.clientSecret?[{providerId:'snapchat',clientId:config.providers.snapchat.clientId,clientSecret:config.providers.snapchat.clientSecret,authorizationUrl:'https://accounts.snapchat.com/accounts/oauth2/auth',tokenUrl:'https://accounts.snapchat.com/accounts/oauth2/token',scopes:['https://auth.snapchat.com/oauth2/api/user.display_name','https://auth.snapchat.com/oauth2/api/user.external_id'],pkce:true,disableImplicitSignUp:true,disableSignUp:true,getUserInfo:async tokens=>{const identity=await snapchatIdentity(tokens.accessToken!);const linked=db.prepare('SELECT u.email,u.emailVerified FROM account a JOIN user u ON u.id=a.userId WHERE a.providerId=? AND a.accountId=?').get('snapchat',identity.id) as Row|undefined;return linked?{...identity,email:linked.email,emailVerified:linked.emailVerified===1}:identity}}]:[]}),googleNonceBinding()]
 });
 await (await getMigrations(auth.options)).runMigrations();
 db.exec(readFileSync(new URL('./migrations/001-platform.sql',import.meta.url),'utf8'));schemaReady=true;
 if(!(db.prepare('SELECT 1 FROM pok_dictionary LIMIT 1').get()))db.prepare('INSERT INTO pok_dictionary VALUES(1,?,1,NULL,?)').run(JSON.stringify(seedDictionary),now());
 const audit=(actor:string|null,target:string|null,action:string,reason:string,expiry:number|null=null)=>{db.prepare('INSERT INTO pok_audit(actor_id,target_id,action,reason,expires_at,created_at) VALUES(?,?,?,?,?,?)').run(actor,target,action,reason,expiry,now());};
 const notify=(user:string,kind:string,target:string,body:string)=>db.prepare('INSERT INTO pok_notification VALUES(?,?,?,?,?,0,?)').run(randomUUID(),user,kind,target,body,now());
 const restrictions=(id:string)=>db.prepare('SELECT id,kind,reason,evidence_id,expires_at,created_at FROM pok_sanction WHERE target_id=? AND revoked_at IS NULL AND (expires_at IS NULL OR expires_at>?)').all(id,now()) as Row[];
 const profile=(id:string)=>{db.prepare('INSERT OR IGNORE INTO pok_profile(user_id,adult_accepted_at) SELECT id,adultAcceptedAt FROM user WHERE id=?').run(id);return db.prepare('SELECT * FROM pok_profile WHERE user_id=?').get(id) as Row};
 const requireUser=async(c:Context,permission?:Permission)=>{const session=await auth.api.getSession({headers:c.req.raw.headers});assert(session,'authentication_required',401);const p=profile(session.user.id);const r=restrictions(session.user.id);
  assert(!r.some(s=>['suspend','ban'].includes(s.kind)),'account_restricted',403);
  if(permission){assert(permissions[p.role]?.includes(permission),'permission_denied',403);if(config.mode==='production')assert((session.user as Row).twoFactorEnabled===true&&db.prepare('SELECT 1 FROM pok_mfa_session WHERE session_id=?').get(session.session.id),'administrator_mfa_required',403);}
  if(isWrite(c.req.method)) {const row=db.prepare('SELECT token FROM pok_csrf WHERE session_id=?').get(session.session.id) as Row|undefined;const token=c.req.header('x-pok-csrf')||'';assert(row&&token.length===row.token.length&&timingSafeEqual(Buffer.from(token),Buffer.from(row.token)),'csrf_invalid',403);}
  return {...session.user,profile:p,session:session.session,restrictions:r};
 };
 const fresh=(user:Row)=>assert(now()-new Date(user.session.createdAt).getTime()<600000,'reauthentication_required',403);
 const postAllowed=(user:Row)=>assert(!user.restrictions.some((r:Row)=>r.kind==='mute'),'posting_restricted',403);
 const dictionary=()=>JSON.parse((db.prepare('SELECT payload FROM pok_dictionary WHERE active=1 ORDER BY version DESC LIMIT 1').get() as Row).payload) as DictionaryEntry[];
 const ownsContent=(user:Row,row:Row)=>row.author_id===user.id;
 const canRead=(user:Row,row:Row)=>!['feedback','feedback-reply'].includes(row.kind)||ownsContent(user,row)||permissions[user.profile.role].includes('support')||!!(row.parent_id&&((db.prepare('SELECT author_id FROM pok_content WHERE id=?').get(row.parent_id) as Row)?.author_id===user.id));
 const app=new Hono();const limits=new Map<string,{count:number;start:number}>();const previews=new Map<string,{user:string;hash:string;expires:number}>();app.use('/api/*',bodyLimit({maxSize:1100000,onError:c=>c.json({error:'payload_too_large'},413)}));
 app.use('*',async(c,next)=>{c.header('X-Content-Type-Options','nosniff');c.header('Referrer-Policy','no-referrer');c.header('X-Frame-Options','DENY');c.header('Permissions-Policy','camera=(), microphone=(), geolocation=()');c.header('Content-Security-Policy',"default-src 'self'; script-src 'self' 'wasm-unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self'; worker-src 'self'; object-src 'none'; base-uri 'none'; frame-ancestors 'none'; form-action 'self'");if(config.mode==='production')c.header('Strict-Transport-Security','max-age=31536000');
  if(c.req.path.startsWith('/api/')){c.header('Cache-Control','no-store');const requestURL=new URL(c.req.url);assert(requestURL.origin===origin||(config.mode==='production'&&requestURL.host===new URL(origin).host&&c.req.header('x-forwarded-proto')==='https'),'host_not_allowed',403);if(isWrite(c.req.method)){assert(c.req.header('origin')===origin,'origin_not_allowed',403);assert(c.req.header('content-type')?.startsWith('application/json'),'json_required',415);const raw=await c.req.text();assert(raw.length<=1100000,'payload_too_large',413);try{JSON.parse(raw)}catch{throw new HttpError(400,'invalid_json')}}}
  await next();
 });
 app.onError((error,c)=>{if(error instanceof HttpError)return c.json({error:error.code},error.status as any);return c.json({error:'request_failed'},500)});
 app.get('/api/status',c=>{const defaults=db.prepare("SELECT payload FROM pok_setting WHERE key='appearance'").get() as Row|undefined;return c.json({product:'Poker Odds Knowledge',online:true,mode:config.mode,adultOnly:true,mail:config.testMail?'LOCAL_TEST_SINK':config.sendMail?'configured':'NOT_CONFIGURED',providers:providerRegistry(config.providers),countries,ai:'disabled-until-configured-and-budgeted',database:'SQLite',appearanceDefaults:defaults?validateAppearance(JSON.parse(defaults.payload)):null})});
 app.on(['GET','POST'],'/api/auth/*',async c=>{
  const path=c.req.path;let request=c.req.raw;
  if(c.req.method==='POST') {let body=await c.req.json();for(const key of ['callbackURL','errorCallbackURL','newUserCallbackURL','redirectTo'])if(body[key]!==undefined){assert(typeof body[key]==='string');let url:URL;try{url=new URL(body[key],origin)}catch{throw new HttpError(400,'redirect_invalid')}assert(url.origin===origin&&!url.username&&!url.password,'redirect_invalid');}if(path.endsWith('/sign-up/email')){assert(body.adultAccepted===true,'adult_policy_required');body={...body,name:cleanName(str(body.name,60))};}if(path.endsWith('/sign-in/social')){assert(body.idToken===undefined,'authorization_code_only');if(body.requestSignUp===true)assert(body.adultAccepted===true,'adult_policy_required');}request=new Request(c.req.url,{method:'POST',headers:c.req.raw.headers,body:JSON.stringify(body)});
   if(['/link-social','/link','/unlink-account','/delete-user'].some(x=>path.endsWith(x))){const s=await auth.api.getSession({headers:c.req.raw.headers});assert(s,'authentication_required',401);assert(now()-new Date(s.session.createdAt).getTime()<600000,'reauthentication_required',403);}
  }
  const response=await auth.handler(request);
  if(response.ok&&['/two-factor/verify-totp','/two-factor/verify-backup-code','/two-factor/verify-otp'].some(p=>path.endsWith(p))){const headers=new Headers(c.req.raw.headers);const cookies=new Map((headers.get('cookie')||'').split(';').filter(Boolean).map(part=>{const at=part.indexOf('=');return [part.slice(0,at).trim(),part.slice(at+1)]}));for(const cookie of response.headers.getSetCookie()){const part=cookie.split(';')[0],at=part.indexOf('=');cookies.set(part.slice(0,at),part.slice(at+1))}headers.set('cookie',[...cookies].map(([k,v])=>`${k}=${v}`).join('; '));const verified=await auth.api.getSession({headers});if(verified&&(verified.user as Row).twoFactorEnabled)db.prepare('INSERT OR REPLACE INTO pok_mfa_session VALUES(?,?)').run(verified.session.id,now());}
  if(path.endsWith('/sign-in/email')&&!response.ok&&response.status!==429)return c.json({error:'authentication_failed'},401);
  if(path.endsWith('/sign-up/email')&&response.ok)return c.json({status:'verification_requested'});
  return response;
 });
 if(config.testMail&&config.mode!=='production')app.get('/api/dev/mail',c=>{const email=c.req.query('email');assert(email&&email.length<254);return c.json({warning:'Isolated local test mail. Not real email delivery.',messages:mailSink.filter(m=>m.to===email).map(m=>({...m}))})});
 app.get('/api/me',async c=>{const s=await auth.api.getSession({headers:c.req.raw.headers});assert(s,'authentication_required',401);const u={...s.user,session:s.session,profile:profile(s.user.id),restrictions:restrictions(s.user.id)};let csrf=db.prepare('SELECT token FROM pok_csrf WHERE session_id=?').get(u.session.id) as Row|undefined;if(!csrf){csrf={token:randomBytes(32).toString('hex')};db.prepare('INSERT INTO pok_csrf VALUES(?,?)').run(u.session.id,csrf.token)}return c.json({user:{id:u.id,name:u.name,email:u.email,role:u.profile.role,twoFactorEnabled:u.twoFactorEnabled||false},profile:u.profile,csrf:csrf.token,restrictions:u.restrictions})});
 app.use('/api/*',async(c,next)=>{if(isWrite(c.req.method)&&!c.req.path.startsWith('/api/auth/')){const session=await auth.api.getSession({headers:c.req.raw.headers});const key=session?.user.id||'anonymous';const item=limits.get(key);if(!item||now()-item.start>60000)limits.set(key,{count:1,start:now()});else{item.count++;assert(item.count<=45,'rate_limited',429)}if(limits.size>10000)limits.clear();}await next()});
 app.patch('/api/profile',async c=>{const u=await requireUser(c),b=await c.req.json();const name=cleanName(str(b.name||u.name,60));assert(!b.country||countries.includes(b.country),'country_invalid');assert(isLocale(b.locale),'locale_invalid');db.prepare('UPDATE user SET name=?,locale=?,updatedAt=? WHERE id=?').run(name,b.locale,now(),u.id);db.prepare('UPDATE pok_profile SET country=?,show_country=?,locale=?,adult_accepted_at=COALESCE(adult_accepted_at,?) WHERE user_id=?').run(b.country||null,b.showCountry===true?1:0,b.locale,now(),u.id);audit(u.id,u.id,'profile.update','Member changed optional profile');return c.json({ok:true})});
 app.get('/api/content',async c=>{const u=await requireUser(c);const kind=c.req.query('kind')||'question';assert(['chat','question','answer','feedback','feedback-reply'].includes(kind));const before=c.req.query('before')||`${Number.MAX_SAFE_INTEGER}:~`,split=before.indexOf(':'),cursor=Number(split<0?before:before.slice(0,split)),cursorId=split<0?'':before.slice(split+1),search=(c.req.query('q')||'').slice(0,100),parent=c.req.query('parentId');assert(Number.isFinite(cursor)&&cursorId.length<=80);
  const privateKind=['feedback','feedback-reply'].includes(kind),staff=permissions[u.profile.role].includes('support');const privacy=privateKind&&!staff?'AND (c.author_id=? OR EXISTS(SELECT 1 FROM pok_content parent WHERE parent.id=c.parent_id AND parent.author_id=?))':'';
  let rows=db.prepare(`SELECT c.*,u.name,p.country,p.show_country FROM pok_content c LEFT JOIN user u ON c.author_id=u.id LEFT JOIN pok_profile p ON p.user_id=u.id WHERE c.kind=? AND c.hidden=0 AND (c.created_at<? OR (c.created_at=? AND c.id<?)) AND (c.body LIKE ? OR c.title LIKE ?) ${parent?'AND c.parent_id=?':''} ${privacy} AND NOT EXISTS(SELECT 1 FROM pok_block b WHERE b.user_id=? AND b.target_id=c.author_id) ORDER BY c.created_at DESC,c.id DESC LIMIT 51`).all(kind,cursor,cursor,cursorId,`%${search}%`,`%${search}%`,...(parent?[parent]:[]),...(privacy?[u.id,u.id]:[]),u.id) as Row[];
  rows=rows.filter(r=>canRead(u,r)).map(r=>({...r,name:r.name||'Deleted member',country:r.show_country?r.country:null,show_country:undefined}));return c.json({items:rows.slice(0,50).reverse(),next:rows.length>50?`${rows[49].created_at}:${rows[49].id}`:null})});
 app.post('/api/content',async c=>{const u=await requireUser(c);postAllowed(u);const b=await c.req.json();assert(['chat','question','answer','feedback','feedback-reply'].includes(b.kind));const body=str(b.body);const title=b.kind==='question'||b.kind==='feedback'?str(b.title,120):'';const category=b.category||'general';assert(['general','math','rules','accessibility','bug','learning'].includes(category));let parent:Row|undefined;
  if(['answer','feedback-reply'].includes(b.kind)){parent=db.prepare('SELECT * FROM pok_content WHERE id=?').get(str(b.parentId,80)) as Row|undefined;assert(parent&&canRead(u,parent),'not_found',404);assert(parent.kind===(b.kind==='answer'?'question':'feedback'),'parent_invalid');if(b.kind==='feedback-reply')assert(ownsContent(u,parent)||permissions[u.profile.role].includes('support'),'permission_denied',403)}
  const id=randomUUID(),timestamp=now();db.prepare('INSERT INTO pok_content(id,author_id,kind,parent_id,title,body,category,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)').run(id,u.id,b.kind,parent?.id||null,title,body,category,timestamp,timestamp);
  const signals=scanMessage(body,dictionary());if(signals.length)db.prepare('INSERT INTO pok_report VALUES(?,NULL,?,?,\'open\',?)').run(randomUUID(),id,`Dictionary signals: ${signals.slice(0,10).map(s=>`${s.entryId}/${s.locale}/${s.category}/${s.severity}/context=${s.contextual}/${s.review}`).join('; ')}. ${signals.length} total; human review required`,timestamp);
  if(parent&&parent.author_id&&parent.author_id!==u.id)notify(parent.author_id,'reply',parent.id,'A reply is available.');audit(u.id,id,'content.create',b.kind);return c.json({id,status:'persisted'},201)});
 app.patch('/api/content/:id',async c=>{const u=await requireUser(c);postAllowed(u);const row=db.prepare('SELECT * FROM pok_content WHERE id=?').get(c.req.param('id')) as Row|undefined;assert(row&&ownsContent(u,row),'not_found',404);assert(now()-row.created_at<1800000,'edit_window_closed');const b=await c.req.json();db.prepare('UPDATE pok_content SET body=?,updated_at=? WHERE id=?').run(str(b.body),now(),row.id);audit(u.id,row.id,'content.edit','Author edit');return c.json({ok:true})});
 app.delete('/api/content/:id',async c=>{const u=await requireUser(c);const row=db.prepare('SELECT * FROM pok_content WHERE id=?').get(c.req.param('id')) as Row|undefined;assert(row&&ownsContent(u,row),'not_found',404);db.prepare('UPDATE pok_content SET hidden=1,body=?,updated_at=? WHERE id=?').run('[Deleted by author]',now(),row.id);audit(u.id,row.id,'content.delete','Author removal');return c.json({ok:true})});
 app.post('/api/content/:id/resolve',async c=>{const u=await requireUser(c);const row=db.prepare('SELECT * FROM pok_content WHERE id=?').get(c.req.param('id')) as Row|undefined;assert(row&&canRead(u,row),'not_found',404);assert(ownsContent(u,row)||permissions[u.profile.role].includes(row.kind==='feedback'?'support':'content'),'permission_denied',403);db.prepare("UPDATE pok_content SET status='resolved',updated_at=? WHERE id=?").run(now(),row.id);audit(u.id,row.id,'content.resolve','Marked resolved');return c.json({ok:true})});
 app.post('/api/reports',async c=>{const u=await requireUser(c),b=await c.req.json();const row=db.prepare('SELECT * FROM pok_content WHERE id=?').get(str(b.contentId,80)) as Row|undefined;assert(row&&canRead(u,row),'not_found',404);const id=randomUUID();db.prepare('INSERT INTO pok_report VALUES(?,?,?,?,\'open\',?)').run(id,u.id,row.id,str(b.reason,500),now());return c.json({id},201)});
 app.get('/api/blocks',async c=>{const u=await requireUser(c);return c.json({items:db.prepare('SELECT target_id FROM pok_block WHERE user_id=?').all(u.id)})});
 app.post('/api/blocks',async c=>{const u=await requireUser(c),b=await c.req.json();assert(typeof b.targetId==='string'&&b.targetId!==u.id&&db.prepare('SELECT 1 FROM user WHERE id=?').get(b.targetId),'target_invalid');if(b.blocked)db.prepare('INSERT OR IGNORE INTO pok_block VALUES(?,?)').run(u.id,b.targetId);else db.prepare('DELETE FROM pok_block WHERE user_id=? AND target_id=?').run(u.id,b.targetId);return c.json({ok:true})});
 app.get('/api/notifications',async c=>{const u=await requireUser(c);return c.json({items:db.prepare('SELECT * FROM pok_notification WHERE user_id=? ORDER BY created_at DESC LIMIT 100').all(u.id)})});
 app.post('/api/notifications/read',async c=>{const u=await requireUser(c);db.prepare('UPDATE pok_notification SET seen=1 WHERE user_id=?').run(u.id);return c.json({ok:true})});
 app.get('/api/sync',async c=>{const u=await requireUser(c),row=db.prepare('SELECT * FROM pok_sync WHERE user_id=?').get(u.id) as Row|undefined;return c.json(row?{revision:row.revision,payload:JSON.parse(row.payload),updatedAt:row.updated_at}:{revision:0,payload:null})});
 app.put('/api/sync',async c=>{
  const u=await requireUser(c),b=await c.req.json();assert(b.consent===true,'explicit_sync_consent_required');assert(Number.isInteger(b.revision)&&b.revision>=0,'revision_invalid');assert(b.payload&&typeof b.payload==='object'&&!Array.isArray(b.payload));const allowed=['settings','attempts','hands','appearance'];assert(Object.keys(b.payload).every(k=>allowed.includes(k)),'sync_fields_invalid');jsonSafe(b.payload);
  let checked:Row;try{const base=defaults();checked=validateData({...base,...b.payload,settings:{...base.settings,...b.payload.settings}})}catch{throw new HttpError(400,'study_payload_invalid')}
  if(b.payload.appearance!==undefined){const appearance=validateAppearance(b.payload.appearance);assert(b.payload.appearance&&Object.keys(b.payload.appearance).every(k=>k in appearance)&&Object.entries(appearance).every(([k,v])=>b.payload.appearance[k]===v),'appearance_invalid');checked.appearance=appearance;}
  const payload=jsonSafe(Object.fromEntries(Object.keys(b.payload).map(k=>[k,checked[k]])));db.exec('BEGIN IMMEDIATE');try{const old=db.prepare('SELECT revision FROM pok_sync WHERE user_id=?').get(u.id) as Row|undefined;assert((old?.revision||0)===b.revision,'sync_conflict',409);db.prepare('INSERT INTO pok_sync VALUES(?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET revision=excluded.revision,payload=excluded.payload,updated_at=excluded.updated_at').run(u.id,b.revision+1,payload,now());db.exec('COMMIT')}catch(e){db.exec('ROLLBACK');throw e}return c.json({revision:b.revision+1})
 });
 app.delete('/api/sync',async c=>{const u=await requireUser(c);db.prepare('DELETE FROM pok_sync WHERE user_id=?').run(u.id);return c.json({ok:true})});
 app.get('/api/account/export',async c=>{const u=await requireUser(c);const sync=db.prepare('SELECT revision,payload,updated_at FROM pok_sync WHERE user_id=?').get(u.id);return c.json({schema:1,product:'Poker Odds Knowledge',exportedAt:now(),profile:{id:u.id,name:u.name,email:u.email,...u.profile},sync,content:db.prepare('SELECT * FROM pok_content WHERE author_id=?').all(u.id),notifications:db.prepare('SELECT * FROM pok_notification WHERE user_id=?').all(u.id),sanctions:u.restrictions,appeals:db.prepare('SELECT * FROM pok_appeal WHERE user_id=?').all(u.id)})});
 // Appeals remain available to suspended members, without permitting other community operations.
 app.post('/api/appeals',async c=>{const session=await auth.api.getSession({headers:c.req.raw.headers});assert(session,'authentication_required',401);const token=db.prepare('SELECT token FROM pok_csrf WHERE session_id=?').get(session.session.id) as Row|undefined;assert(token&&c.req.header('x-pok-csrf')===token.token,'csrf_invalid',403);const b=await c.req.json(),row=db.prepare('SELECT id FROM pok_sanction WHERE id=? AND target_id=?').get(str(b.sanctionId,80),session.user.id);assert(row,'not_found',404);const id=randomUUID();db.prepare('INSERT INTO pok_appeal VALUES(?,?,?,?,\'open\',?)').run(id,b.sanctionId,session.user.id,str(b.body,1000),now());audit(session.user.id,b.sanctionId,'sanction.appeal','Appeal submitted');return c.json({id},201)});
 app.get('/api/admin/:section',async c=>{const section=c.req.param('section');const map:Record<string,Permission>={users:'users',reports:'moderate',chat:'moderate',questions:'content',feedback:'support',dictionary:'content',audit:'audit',providers:'configure',appearance:'configure',languages:'content',appeals:'moderate'};assert(map[section],'not_found',404);await requireUser(c,map[section]);const offset=Math.max(0,Math.min(100000,Number(c.req.query('offset')||0))),q=(c.req.query('q')||'').slice(0,100);assert(Number.isInteger(offset));
  if(section==='providers')return c.json({items:providerRegistry(config.providers)});
  if(section==='dictionary')return c.json({items:db.prepare('SELECT * FROM pok_dictionary ORDER BY version DESC LIMIT 20').all()});
  if(section==='languages')return c.json({items:supportedLocales.map(locale=>({...translationCoverage(locale),...getLocaleMetadata(locale),moderationDraftEntries:dictionary().filter(e=>e.locale===locale).length}))});
  if(section==='appearance')return c.json({items:db.prepare('SELECT * FROM pok_setting WHERE key=?').all(section)});
  if(section==='users')return c.json({items:db.prepare('SELECT u.id,u.name,u.email,u.emailVerified,u.twoFactorEnabled,p.role,p.country,p.show_country FROM user u LEFT JOIN pok_profile p ON p.user_id=u.id WHERE u.name LIKE ? ORDER BY u.createdAt DESC LIMIT 50 OFFSET ?').all(`%${q}%`,offset)});
  if(section==='audit')return c.json({items:db.prepare('SELECT * FROM pok_audit ORDER BY id DESC LIMIT 50 OFFSET ?').all(offset)});
  if(section==='reports')return c.json({items:db.prepare('SELECT r.*,c.body,c.author_id FROM pok_report r LEFT JOIN pok_content c ON r.content_id=c.id ORDER BY r.created_at DESC LIMIT 50 OFFSET ?').all(offset)});
  if(section==='appeals')return c.json({items:db.prepare('SELECT * FROM pok_appeal ORDER BY created_at DESC LIMIT 50 OFFSET ?').all(offset)});
  return c.json({items:db.prepare('SELECT c.*,u.name FROM pok_content c LEFT JOIN user u ON c.author_id=u.id WHERE c.kind=? AND (c.body LIKE ? OR c.title LIKE ?) ORDER BY c.created_at DESC LIMIT 50 OFFSET ?').all(section==='questions'?'question':section,`%${q}%`,`%${q}%`,offset)});
 });
 app.post('/api/admin/sanctions',async c=>{const u=await requireUser(c,'moderate');fresh(u);const b=await c.req.json(),target=str(b.targetId,80),p=profile(target);assert(db.prepare('SELECT 1 FROM user WHERE id=?').get(target),'not_found',404);assert(target!==u.id&&p.role!=='owner'&&(!['administrator','moderator'].includes(p.role)||u.profile.role==='owner'),'protected_role',403);assert(['warn','mute','suspend','ban','revoke'].includes(b.kind));const reason=str(b.reason,500);const expiry=b.kind==='mute'||b.kind==='suspend'?Number(b.expiresAt):null;assert(expiry===null||Number.isFinite(expiry)&&expiry>now()&&expiry<=now()+30*86400000,'expiry_invalid');
  if(b.kind==='revoke'){assert(typeof b.sanctionId==='string');db.prepare('UPDATE pok_sanction SET revoked_at=? WHERE id=? AND target_id=?').run(now(),b.sanctionId,target);db.prepare("UPDATE pok_appeal SET status='resolved' WHERE sanction_id=?").run(b.sanctionId);audit(u.id,target,'sanction.revoke',reason);notify(target,'moderation',b.sanctionId,'A restriction was reversed.');return c.json({ok:true})}
  const id=randomUUID();db.prepare('INSERT INTO pok_sanction VALUES(?,?,?,?,?,?,?,NULL,?)').run(id,target,u.id,b.kind,reason,b.evidenceId?str(b.evidenceId,80):null,expiry,now());audit(u.id,target,`sanction.${b.kind}`,reason,expiry);notify(target,'moderation',id,reason);return c.json({id},201)});
 app.patch('/api/admin/content/:id',async c=>{const u=await requireUser(c,'moderate'),b=await c.req.json();assert(db.prepare('SELECT 1 FROM pok_content WHERE id=?').get(c.req.param('id')),'not_found',404);const reason=str(b.reason,500);db.prepare('UPDATE pok_content SET hidden=?,updated_at=? WHERE id=?').run(b.hidden===true?1:0,now(),c.req.param('id'));db.prepare("UPDATE pok_report SET status='reviewed' WHERE content_id=?").run(c.req.param('id'));audit(u.id,c.req.param('id'),b.hidden?'content.hide':'content.restore',reason);return c.json({ok:true})});
 app.post('/api/admin/roles',async c=>{const u=await requireUser(c,'users');fresh(u);assert(u.profile.role==='owner','owner_required',403);const b=await c.req.json();assert(Object.keys(permissions).includes(b.role));const p=profile(str(b.targetId,80));if(p.role==='owner'&&b.role!=='owner')assert((db.prepare("SELECT count(*) n FROM pok_profile WHERE role='owner'").get() as Row).n>1,'last_owner_protected');db.prepare('UPDATE pok_profile SET role=? WHERE user_id=?').run(b.role,b.targetId);audit(u.id,b.targetId,'role.change',str(b.reason,500));return c.json({ok:true})});
 app.post('/api/admin/dictionary/preview',async c=>{const u=await requireUser(c,'content');const b=await c.req.json(),entries=validateDictionary(b.entries);assert(Array.isArray(b.samples)&&b.samples.length>0&&b.samples.length<=50);const previewToken=randomBytes(32).toString('hex');for(const [key,p] of previews)if(p.expires<now())previews.delete(key);assert(previews.size<1000,'preview_limit',429);previews.set(previewToken,{user:u.id,hash:createHash('sha256').update(jsonSafe(entries)).digest('hex'),expires:now()+600000});return c.json({results:b.samples.map((s:unknown)=>({text:str(s,2000),signals:scanMessage(s as string,entries)})),previewToken})});
 app.post('/api/admin/dictionary',async c=>{const u=await requireUser(c,'content');fresh(u);const b=await c.req.json(),entries=validateDictionary(b.entries);const preview=previews.get(b.previewToken);assert(preview&&preview.user===u.id&&preview.expires>now()&&preview.hash===createHash('sha256').update(jsonSafe(entries)).digest('hex'),'preview_required');previews.delete(b.previewToken);const version=(db.prepare('SELECT max(version) v FROM pok_dictionary').get() as Row).v+1;db.exec('BEGIN IMMEDIATE');try{db.prepare('UPDATE pok_dictionary SET active=0').run();db.prepare('INSERT INTO pok_dictionary VALUES(?,?,1,?,?)').run(version,JSON.stringify(entries),u.id,now());audit(u.id,String(version),'dictionary.activate',str(b.reason,500));db.exec('COMMIT')}catch(e){db.exec('ROLLBACK');throw e}return c.json({version})});
 app.post('/api/admin/dictionary/rollback',async c=>{const u=await requireUser(c,'content');fresh(u);const b=await c.req.json();assert(Number.isInteger(b.version)&&db.prepare('SELECT 1 FROM pok_dictionary WHERE version=?').get(b.version),'version_invalid');db.exec('BEGIN IMMEDIATE');try{db.prepare('UPDATE pok_dictionary SET active=0').run();db.prepare('UPDATE pok_dictionary SET active=1 WHERE version=?').run(b.version);audit(u.id,String(b.version),'dictionary.rollback',str(b.reason,500));db.exec('COMMIT')}catch(e){db.exec('ROLLBACK');throw e}return c.json({ok:true})});
 app.put('/api/admin/appearance',async c=>{const u=await requireUser(c,'configure');fresh(u);const b=await c.req.json();const payload=jsonSafe(validateAppearance(b.defaults),4000);db.prepare("INSERT INTO pok_setting VALUES('appearance',?,?) ON CONFLICT(key) DO UPDATE SET payload=excluded.payload,updated_at=excluded.updated_at").run(payload,now());audit(u.id,null,'appearance.defaults',str(b.reason,500));return c.json({ok:true})});
 const context={db,auth,requireUser,audit};config.configure?.(app,context);
 return {app,db,auth,mailSink,requireUser,audit,close:()=>db.close()};
}
