import {spawn} from 'node:child_process';
import {readFile} from 'node:fs/promises';
import {createHash,randomBytes} from 'node:crypto';
import {resolve,delimiter,basename} from 'node:path';
import {fileURLToPath} from 'node:url';
import {validateSolveRequest,validateSolveResult,solveHash,SOLVER_ID,SOLVER_REVISION,SOLVER_ADAPTER,type SolveRequest,type SolveResult} from '../src/strategy/contract';
const root=fileURLToPath(new URL('../',import.meta.url));
const jar=resolve(root,'.solver-tools/java-build/pok-river-solver.jar');
const dependencyNames=['fastjson2-2.0.65.jar','jackson-core-2.22.3.jar','jackson-databind-2.22.3.jar','jackson-annotations-2.22.jar'];
const checksum=(data:Buffer)=>createHash('sha256').update(data).digest('hex');
type Runtime={javaPath:string;javaSha256:string;guardShell:string;guardShellSha256:string};
export function validGuardReady(frame:unknown):boolean {const f=frame as any;return !!f&&Object.keys(f).sort().join(',')==='killOnClose,memoryLimitBytes,type'&&f.type==='ready'&&f.memoryLimitBytes===536870912&&f.killOnClose===true}
export function validSolverProgress(frame:any,request:SolveRequest,last:number):boolean {return frame?.type==='progress'&&Number.isSafeInteger(frame.iterations)&&frame.iterations>last&&frame.iterations<=request.budget.iterations&&frame.target===request.budget.iterations&&typeof frame.gap==='number'&&Number.isFinite(frame.gap)&&frame.gap>=-0.001&&frame.gap<=request.pot+2*request.effectiveStack+0.001}
async function runtime():Promise<Runtime>{const r=JSON.parse(await readFile(resolve(root,'.pok-strategy/runtime.json'),'utf8'));if(basename(r.javaPath).toLowerCase()!=='java.exe'||basename(r.guardShell).toLowerCase()!=='pwsh.exe'||checksum(await readFile(r.javaPath))!==r.javaSha256||checksum(await readFile(r.guardShell))!==r.guardShellSha256)throw Error('runtime_not_verified');return r}
export async function javaAvailability(){try{await runtime();const manifest=JSON.parse(await readFile(resolve(root,'.solver-tools/java-build/build-manifest.json'),'utf8'));if(manifest.upstreamRevision!==SOLVER_REVISION||checksum(await readFile(jar))!==manifest.sha256)throw Error('build_integrity_failed');for(const name of dependencyNames){const entry=manifest.dependencyHashes.find((d:any)=>d.coordinate.endsWith('/'+name.replace(/\.jar$/,'')));if(!entry||checksum(await readFile(resolve(root,'.solver-tools/java-deps',name)))!==entry.sha256)throw Error('dependency_integrity_failed')}await readFile(resolve(root,'engine-adapters/java/Guard-Solver.ps1'));return {available:true,reason:'Verified local JVM, pinned JAR and dependency hashes; explicit job permission required.'}}catch{return {available:false,reason:'Local solver is not built, verified, or configured. Use bundled study packs.'}}}
export function nativeSolveRequest(r:SolveRequest){return {schema:1,op:'solve',board:r.board,dead:r.dead,ranges:r.players.map(p=>{const max=Math.max(...p.combinations.map(c=>c.weight));return p.combinations.filter(c=>c.weight>0).map(c=>({...c,weight:c.weight/max}))}),pot:r.pot,effectiveStack:r.effectiveStack,betSizes:r.tree.betSizes,raiseTo:r.tree.raiseTo,maxRaises:r.tree.maxRaises,iterations:r.budget.iterations,deadlineMs:r.budget.timeMs}}
export async function canonicalSolveResult(raw:any,request:SolveRequest,elapsedMs:number):Promise<SolveResult>{
 if(raw?.type!=='result'||!raw.ok||raw.upstreamRevision!==SOLVER_REVISION||raw.engine!=='TexasHoldemSolverJava'||!['COMPLETE','PARTIAL','TIMEOUT'].includes(raw.status)||raw.iterations>request.budget.iterations)throw Error('malformed_solver_output');
 const cardKey=(cards:string[])=>[...cards].sort().join('');const normalized=nativeSolveRequest(request);
 if(raw.pot!==request.pot||raw.effectiveStack!==request.effectiveStack||cardKey(raw.board)!==cardKey(request.board)||cardKey(raw.dead)!==cardKey(request.dead)||raw.computeThreads!==1||raw.adapterVersion!=='pok-java-river-1'||!Array.isArray(raw.ranges)||raw.ranges.length!==2)throw Error('native_model_mismatch');
 for(let seat=0;seat<2;seat++){if(raw.ranges[seat].length!==normalized.ranges[seat].length)throw Error('native_range_mismatch');const seen=new Set<string>();for(const c of raw.ranges[seat]){const k=cardKey(c.cards),expected=normalized.ranges[seat].find(h=>cardKey(h.cards)===k);if(seen.has(k)||!expected||!Number.isFinite(c.weight)||Math.abs(c.weight-expected.weight)>1e-6)throw Error('native_weight_mismatch');seen.add(k)}}
 const hash=await solveHash(request),metric=raw.nashConvChips;const result:SolveResult={schemaVersion:1,requestId:request.requestId,analysisRevision:request.analysisRevision,inputHash:hash,cacheKey:`${SOLVER_ID}:${SOLVER_ADAPTER}:${hash}`,engineId:SOLVER_ID,upstreamRevision:SOLVER_REVISION,adapterVersion:SOLVER_ADAPTER,location:'local-jvm',status:metric<=request.targetGap&&raw.status==='COMPLETE'?'COMPLETE':'PARTIAL',completionReason:raw.status!=='COMPLETE'?'Solver stopped before completing the requested budget; this is a partial result.':metric<=request.targetGap?'Requested iteration budget finished and reported gap meets target.':'Budget finished before the requested gap target; study with uncertainty.',method:'DISCOUNTED CFR',iterations:raw.iterations,elapsedMs,
 nodes:raw.nodes.filter((n:any)=>n.kind==='ACTION').map((n:any)=>({path:n.id,actor:n.actor,actions:n.actions.map((a:any)=>a.label),hands:n.policies.map((h:any)=>({cards:h.cards,probabilities:h.probabilities,actionEV:h.actionEvChips,reach:h.informationSetReach}))})),rootValues:raw.profileEvChips,bestResponseValues:raw.upstreamBestResponseValues,
 metric:{name:'NashConv',value:Math.max(0,metric),unit:'chips',definition:'BR0(average policy1) + BR1(average policy0); centered zero-sum chips. Half is two-player exploitability. Relative percent = half / initial pot * 100. Only this restricted tree and weighted model.',exploitabilityHalf:Math.max(0,metric)/2},trace:raw.trace.filter((p:any)=>Number.isFinite(p.gap)).map((p:any)=>({iteration:p.iterations,gap:Math.max(0,p.gap)})),reproducibility:'Deterministic single-thread river traversal, no chance sampling/seed. Float rounding is runtime-dependent.',limitations:[...raw.limitations,'Weights are proportionally normalized per seat, then represented as upstream float values; tiny numeric differences are expected.','Action EV uses average-policy continuation, relative to an equal split of the initial pot; past bets are not charged again.','Zero-reach nodes use declared initial opponent range fallback. A global gap is not a per-hand error bound.','External Java CFR traversal/trainable/best response; adapter tree, range boundary and independent five-card comparator.']};return validateSolveResult(result,request);
}
export async function runJavaSolver(input:SolveRequest,options:{signal:AbortSignal;onProgress:(p:{iteration:number;gap:number|null})=>void}):Promise<SolveResult>{
 const request=validateSolveRequest(input);if(options.signal.aborted)throw Error('cancelled');if(!(await javaAvailability()).available)throw Error('solver_unavailable');const config=await runtime(),start=performance.now(),ownerToken=randomBytes(32).toString('hex');
 return new Promise((resolveResult,reject)=>{
  const child=spawn(config.javaPath,['-Xms32m','-Xmx256m','-XX:MaxMetaspaceSize=128m','-XX:ReservedCodeCacheSize=64m','-Xss512k','-XX:ActiveProcessorCount=1','-XX:+UseSerialGC','-Djava.awt.headless=true','-Dpok.ownerToken='+ownerToken,'-cp',[jar,...dependencyNames.map(n=>resolve(root,'.solver-tools/java-deps',n))].join(delimiter),'pok.solver.PokRiverMain'],{shell:false,windowsHide:true,cwd:root,stdio:['pipe','pipe','pipe']});
  let guard:ReturnType<typeof spawn>|undefined,closed=false,failure='',output='',bytes=0,errors=0,lastIteration=0,final:any;const stop=(reason:string)=>{failure||=reason;child.kill();guard?.kill()};const cancel=()=>stop('cancelled');options.signal.addEventListener('abort',cancel,{once:true});const timer=setTimeout(()=>stop('solver_timeout'),request.budget.timeMs+1500);
  child.on('spawn',()=>{if(options.signal.aborted){stop('cancelled');return}guard=spawn(config.guardShell,['-NoProfile','-NonInteractive','-File',resolve(root,'engine-adapters/java/Guard-Solver.ps1'),'-ChildPid',String(child.pid),'-OwnerToken',ownerToken],{shell:false,windowsHide:true,cwd:root,stdio:['pipe','pipe','pipe']});let guardText='',guardReady=false;guard.stdout!.on('data',data=>{guardText+=data.toString();if(guardText.length>1000){stop('memory_guard_output');return}let boundary;while((boundary=guardText.indexOf('\n'))>=0){const line=guardText.slice(0,boundary);guardText=guardText.slice(boundary+1);try{const frame=JSON.parse(line);if(!guardReady&&validGuardReady(frame)){guardReady=true;child.stdin.end(JSON.stringify(nativeSolveRequest(request)))}else if(!(closed&&frame.type==='closed'))stop('memory_guard_invalid_frame')}catch{stop('memory_guard_invalid_frame')}}});guard.stderr!.on('data',()=>{stop('memory_guard_error')});guard.on('error',()=>stop('memory_guard_failed'));guard.on('exit',code=>{if(!closed)stop(code===0?'memory_guard_closed':'memory_guard_failed')})});
  child.stdout.setEncoding('utf8');child.stdout.on('data',(chunk:string)=>{bytes+=Buffer.byteLength(chunk);if(bytes>2_000_000){stop('solver_output_limit');return}output+=chunk;let end;while((end=output.indexOf('\n'))>=0){const line=output.slice(0,end);output=output.slice(end+1);if(!line.trim())continue;try{const frame=JSON.parse(line);if(frame.type==='result'){if(final)throw Error();final=frame}else if(frame.type==='progress'&&!final){if(!validSolverProgress(frame,request,lastIteration))throw Error('invalid_progress');lastIteration=frame.iterations;options.onProgress({iteration:frame.iterations,gap:Math.max(0,frame.gap)})}else throw Error()}catch{stop('invalid_solver_frame')}}});
  child.stderr.on('data',chunk=>{errors+=chunk.length;if(errors>16384)stop('solver_stderr_limit')});child.stdin.on('error',()=>{});child.on('error',()=>{failure||='solver_spawn_failed'});
  child.on('close',async code=>{closed=true;clearTimeout(timer);options.signal.removeEventListener('abort',cancel);guard?.stdin?.end();if(failure||code!==0||output.trim()||!final){reject(Error(failure||'solver_process_failed'));return}try{resolveResult(await canonicalSolveResult(final,request,performance.now()-start))}catch{reject(Error('solver_result_validation_failed'))}});
 });
}
