import fs from 'node:fs';
const rows=`
en|Verify your email|Reset your password|Confirm account deletion|Use this single-purpose link|If you did not request this action, ignore this message. Do not share this link.|Translation drafts are not linguistically reviewed. Some advanced details and online features use English fallback.
ro|Verifică adresa de e-mail|Resetează parola|Confirmă ștergerea contului|Folosește acest link destinat unei singure acțiuni|Dacă nu ai cerut această acțiune, ignoră mesajul. Nu distribui acest link.|Traduceri fără revizuire lingvistică independentă. Unele detalii avansate și funcții online folosesc engleza.
de|E-Mail-Adresse bestätigen|Passwort zurücksetzen|Kontolöschung bestätigen|Verwende diesen Link nur für diese Aktion|Falls du diese Aktion nicht angefordert hast, ignoriere die Nachricht. Teile diesen Link nicht.|Maschineller Übersetzungsentwurf ohne sprachliche Prüfung. Einige erweiterte Details und Onlinefunktionen erscheinen auf Englisch.
fr|Vérifier votre adresse e-mail|Réinitialiser votre mot de passe|Confirmer la suppression du compte|Utilisez ce lien réservé à cette action|Si vous n’avez pas demandé cette action, ignorez ce message. Ne partagez pas ce lien.|Traduction automatique non relue linguistiquement. Certains détails avancés et fonctions en ligne restent en anglais.
es|Verifica tu correo electrónico|Restablece tu contraseña|Confirma la eliminación de la cuenta|Usa este enlace exclusivo para esta acción|Si no solicitaste esta acción, ignora este mensaje. No compartas este enlace.|Traducción automática sin revisión lingüística. Algunos detalles avanzados y funciones en línea usan inglés como respaldo.
pt|Verificar o endereço de e-mail|Repor a palavra-passe|Confirmar a eliminação da conta|Use esta ligação destinada apenas a esta ação|Se não pediu esta ação, ignore a mensagem. Não partilhe esta ligação.|Tradução automática sem revisão linguística. Alguns detalhes avançados e funções online usam inglês como alternativa.
it|Verifica il tuo indirizzo e-mail|Reimposta la password|Conferma l’eliminazione dell’account|Usa questo collegamento riservato a questa azione|Se non hai richiesto questa azione, ignora il messaggio. Non condividere questo collegamento.|Traduzione automatica senza revisione linguistica. Alcuni dettagli avanzati e funzioni online restano in inglese.
nl|Verifieer je e-mailadres|Stel je wachtwoord opnieuw in|Bevestig verwijdering van je account|Gebruik deze link uitsluitend voor deze actie|Als je deze actie niet hebt aangevraagd, negeer dit bericht. Deel deze link niet.|Machinale vertaling zonder taalkundige controle. Sommige geavanceerde details en onlinefuncties vallen terug op Engels.
sv|Bekräfta din e-postadress|Återställ ditt lösenord|Bekräfta kontoborttagning|Använd denna länk endast för denna åtgärd|Om du inte begärde åtgärden, ignorera meddelandet. Dela inte länken.|Maskinöversatt utkast utan språkgranskning. Vissa avancerade detaljer och onlinefunktioner visas på engelska.
da|Bekræft din e-mailadresse|Nulstil din adgangskode|Bekræft sletning af konto|Brug dette link kun til denne handling|Hvis du ikke bad om handlingen, så ignorér beskeden. Del ikke dette link.|Maskinoversat udkast uden sproglig gennemgang. Visse avancerede detaljer og onlinefunktioner vises på engelsk.
nb|Bekreft e-postadressen din|Tilbakestill passordet ditt|Bekreft sletting av konto|Bruk denne lenken bare til denne handlingen|Hvis du ikke ba om handlingen, ignorer meldingen. Ikke del denne lenken.|Maskinoversatt utkast uten språkvurdering. Noen avanserte detaljer og nettfunksjoner vises på engelsk.
fi|Vahvista sähköpostiosoitteesi|Vaihda salasanasi|Vahvista tilin poistaminen|Käytä tätä linkkiä vain tähän toimintoon|Jos et pyytänyt toimintoa, jätä viesti huomiotta. Älä jaa tätä linkkiä.|Konekäännöstä ei ole kielentarkistettu. Osa lisätiedoista ja verkkotoiminnoista näytetään englanniksi.
pl|Potwierdź adres e-mail|Zresetuj hasło|Potwierdź usunięcie konta|Użyj tego odnośnika tylko do tej czynności|Jeśli nie zlecono tej czynności, zignoruj wiadomość. Nie udostępniaj odnośnika.|Tłumaczenie maszynowe bez weryfikacji językowej. Niektóre szczegóły zaawansowane i funkcje online używają angielskiego.
cs|Ověřte e-mailovou adresu|Obnovte heslo|Potvrďte smazání účtu|Použijte tento odkaz jen pro tuto akci|Pokud jste akci nepožadovali, zprávu ignorujte. Tento odkaz nesdílejte.|Strojový překlad bez jazykové kontroly. Některé pokročilé údaje a online funkce používají angličtinu.
sk|Overte e-mailovú adresu|Obnovte heslo|Potvrďte odstránenie účtu|Použite tento odkaz iba na túto akciu|Ak ste akciu nežiadali, správu ignorujte. Tento odkaz nezdieľajte.|Strojový preklad bez jazykovej kontroly. Niektoré pokročilé údaje a online funkcie používajú angličtinu.
hu|E-mail-cím megerősítése|Jelszó visszaállítása|Fióktörlés megerősítése|Ezt a hivatkozást csak ehhez a művelethez használd|Ha nem kérted a műveletet, hagyd figyelmen kívül az üzenetet. Ne oszd meg a hivatkozást.|Gépi fordítás nyelvi ellenőrzés nélkül. Egyes haladó részletek és online funkciók angolul jelennek meg.
sl|Potrdi e-poštni naslov|Ponastavi geslo|Potrdi izbris računa|To povezavo uporabi samo za to dejanje|Če dejanja nisi zahteval, prezri sporočilo. Povezave ne deli.|Strojni prevod brez jezikovnega pregleda. Nekatere napredne podrobnosti in spletne funkcije so v angleščini.
hr|Potvrdi adresu e-pošte|Ponovno postavi lozinku|Potvrdi brisanje računa|Upotrijebi ovu poveznicu samo za ovu radnju|Ako nisi zatražio ovu radnju, zanemari poruku. Nemoj dijeliti poveznicu.|Strojni prijevod bez jezične provjere. Neki napredni detalji i mrežne funkcije koriste engleski.
sr|Потврди адресу е-поште|Поново постави лозинку|Потврди брисање налога|Употреби ову везу само за ову радњу|Ако ниси тражио ову радњу, занемари поруку. Немој делити везу.|Машински превод без језичке провере. Неки напредни детаљи и мрежне функције користе енглески.
bg|Потвърди имейл адреса|Нулирай паролата|Потвърди изтриването на профила|Използвай тази връзка само за това действие|Ако не си поискал действието, пренебрегни съобщението. Не споделяй връзката.|Машинен превод без езикова проверка. Някои разширени подробности и онлайн функции са на английски.
el|Επαλήθευση ηλεκτρονικού ταχυδρομείου|Επαναφορά κωδικού πρόσβασης|Επιβεβαίωση διαγραφής λογαριασμού|Χρησιμοποίησε αυτόν τον σύνδεσμο μόνο για αυτή την ενέργεια|Αν δεν ζήτησες την ενέργεια, αγνόησε το μήνυμα. Μην κοινοποιήσεις τον σύνδεσμο.|Μηχανική μετάφραση χωρίς γλωσσικό έλεγχο. Ορισμένες προχωρημένες λεπτομέρειες και διαδικτυακές λειτουργίες είναι στα αγγλικά.
tr|E-posta adresini doğrula|Parolanı sıfırla|Hesap silmeyi onayla|Bu bağlantıyı yalnızca bu işlem için kullan|Bu işlemi sen istemediysen mesajı yok say. Bu bağlantıyı paylaşma.|Dil incelemesi yapılmamış makine çevirisi. Bazı gelişmiş ayrıntılar ve çevrimiçi özellikler İngilizce gösterilir.
uk|Підтвердьте електронну адресу|Скиньте пароль|Підтвердьте видалення облікового запису|Використайте це посилання лише для цієї дії|Якщо ви не запитували дію, ігноруйте повідомлення. Не передавайте посилання.|Машинний переклад без мовної перевірки. Деякі розширені деталі й онлайн-функції подано англійською.
ru|Подтвердите электронную почту|Сбросьте пароль|Подтвердите удаление аккаунта|Используйте эту ссылку только для этого действия|Если вы не запрашивали действие, проигнорируйте сообщение. Не передавайте ссылку.|Машинный перевод без языковой проверки. Некоторые расширенные сведения и онлайн-функции представлены на английском.
ar|تحقق من بريدك الإلكتروني|أعد تعيين كلمة المرور|أكد حذف الحساب|استخدم هذا الرابط المخصص لهذا الإجراء فقط|إذا لم تطلب هذا الإجراء فتجاهل الرسالة. لا تشارك هذا الرابط.|ترجمة آلية دون مراجعة لغوية. بعض التفاصيل المتقدمة والميزات عبر الإنترنت تستخدم الإنجليزية عند غياب الترجمة.
he|אימות כתובת הדואר האלקטרוני|איפוס הסיסמה|אישור מחיקת החשבון|השתמשו בקישור זה רק לפעולה זו|אם לא ביקשתם פעולה זו, התעלמו מההודעה. אל תשתפו קישור זה.|תרגום מכונה ללא בדיקה לשונית. חלק מהפרטים המתקדמים והתכונות המקוונות מוצגים באנגלית בהיעדר תרגום.
fa|تأیید نشانی ایمیل|بازنشانی گذرواژه|تأیید حذف حساب|این پیوند را فقط برای همین کار به‌کار ببرید|اگر این کار را درخواست نکردید پیام را نادیده بگیرید. این پیوند را به اشتراک نگذارید.|ترجمه ماشینی بدون بازبینی زبانی. بعضی جزئیات پیشرفته و امکانات آنلاین در نبود ترجمه به انگلیسی نمایش داده می‌شوند.
hi|ईमेल सत्यापित करें|पासवर्ड रीसेट करें|खाता मिटाने की पुष्टि करें|इस लिंक का उपयोग केवल इसी काम के लिए करें|यदि आपने यह काम नहीं माँगा तो संदेश अनदेखा करें। यह लिंक साझा न करें।|मशीनी अनुवाद की भाषाई समीक्षा नहीं हुई। कुछ उन्नत विवरण और ऑनलाइन सुविधाएँ अंग्रेज़ी में दिखाई जाती हैं।
bn|ইমেইল যাচাই করুন|পাসওয়ার্ড রিসেট করুন|অ্যাকাউন্ট মোছা নিশ্চিত করুন|শুধু এই কাজের জন্য এই লিংক ব্যবহার করুন|আপনি এই কাজ না চাইলে বার্তাটি উপেক্ষা করুন। এই লিংক ভাগ করবেন না।|যান্ত্রিক অনুবাদের ভাষাগত পর্যালোচনা হয়নি। কিছু উন্নত তথ্য ওঅনলাইন সুবিধা ইংরেজিতে দেখানো হয়।
ur|ای میل کی تصدیق کریں|پاس ورڈ ری سیٹ کریں|اکاؤنٹ حذف کرنے کی تصدیق کریں|یہ ربط صرف اسی کام کے لیے استعمال کریں|اگر آپ نے یہ کام نہیں مانگا تو پیغام نظرانداز کریں۔ یہ ربط دوسروں کو نہ دیں۔|مشینی ترجمے کا لسانی جائزہ نہیں ہوا۔ کچھ جدید تفصیلات اور آن لائن سہولتیں انگریزی میں دکھائی جاتی ہیں۔
ta|மின்னஞ்சலை உறுதிசெய்யவும்|கடவுச்சொல்லை மீட்டமைக்கவும்|கணக்கு நீக்கத்தை உறுதிசெய்யவும்|இந்த இணைப்பை இந்தச் செயலுக்கு மட்டும் பயன்படுத்தவும்|இந்தச் செயலை நீங்கள் கோரவில்லை என்றால் செய்தியைப் புறக்கணிக்கவும். இணைப்பைப் பகிர வேண்டாம்.|இயந்திர மொழிபெயர்ப்பு மொழியியல் ஆய்வு பெறவில்லை. சில மேம்பட்ட விவரங்களும் இணைய அம்சங்களும் ஆங்கிலத்தில் காட்டப்படும்.
te|ఇమెయిల్ నిర్ధారించండి|పాస్‌వర్డ్ రీసెట్ చేయండి|ఖాతా తొలగింపు నిర్ధారించండి|ఈ లింకును ఈ పని కోసం మాత్రమే వాడండి|ఈ పనిని మీరు అడగకపోతే సందేశాన్ని పట్టించుకోవద్దు. ఈ లింకు పంచుకోవద్దు.|యంత్ర అనువాదానికి భాషా సమీక్ష జరగలేదు. కొన్ని అధునాతన వివరాలు, ఆన్‌లైన్ సౌకర్యాలు ఆంగ్లంలో కనిపిస్తాయి.
mr|ईमेल पडताळा|पासवर्ड रीसेट करा|खाते हटवण्याची पुष्टी करा|हा दुवा फक्त या कृतीसाठी वापरा|तुम्ही ही कृती मागितली नसल्यास संदेश दुर्लक्षित करा. हा दुवा शेअर करू नका.|यंत्रानुवादाची भाषिक तपासणी झालेली नाही. काही प्रगत माहिती वऑनलाइन सुविधा इंग्रजीत दिसतात.
th|ยืนยันอีเมลของคุณ|รีเซ็ตรหัสผ่าน|ยืนยันการลบบัญชี|ใช้ลิงก์นี้สำหรับการดำเนินการนี้เท่านั้น|หากคุณไม่ได้ขอให้ทำรายการนี้ ให้ละเว้นข้อความ อย่าแชร์ลิงก์นี้|คำแปลด้วยเครื่องยังไม่ผ่านการตรวจภาษา รายละเอียดขั้นสูงและคุณสมบัติออนไลน์บางส่วนแสดงเป็นภาษาอังกฤษเมื่อยังไม่มีคำแปล
vi|Xác minh email|Đặt lại mật khẩu|Xác nhận xóa tài khoản|Chỉ dùng liên kết này cho hành động này|Nếu bạn không yêu cầu hành động này, hãy bỏ qua thư. Không chia sẻ liên kết này.|Bản dịch máy chưa được duyệt ngôn ngữ. Một số chi tiết nâng cao và tính năng trực tuyến dùng tiếng Anh khi thiếu bản dịch.
id|Verifikasi email Anda|Atur ulang kata sandi|Konfirmasi penghapusan akun|Gunakan tautan ini hanya untuk tindakan ini|Jika Anda tidak meminta tindakan ini, abaikan pesan. Jangan bagikan tautan ini.|Terjemahan mesin belum ditinjau secara linguistik. Beberapa rincian lanjut dan fitur daring memakai bahasa Inggris sebagai cadangan.
ms|Sahkan e-mel anda|Tetapkan semula kata laluan|Sahkan pemadaman akaun|Gunakan pautan ini hanya untuk tindakan ini|Jika anda tidak meminta tindakan ini, abaikan mesej. Jangan kongsi pautan ini.|Terjemahan mesin belum disemak bahasanya. Sesetengah butiran lanjutan dan ciri dalam talian menggunakan bahasa Inggeris sebagai sandaran.
ja|メールアドレスを確認|パスワードをリセット|アカウント削除を確認|このリンクはこの操作だけに使用してください|この操作を依頼していない場合は、この通知を無視してください。リンクを共有しないでください。|機械翻訳は言語専門家による確認を受けていません。一部の詳細設定やオンライン機能は未翻訳のため英語で表示されます。
ko|이메일 인증|비밀번호 재설정|계정 삭제 확인|이 링크는 해당 작업에만 사용하세요|이 작업을 요청하지 않았다면 메시지를 무시하세요. 이 링크를 공유하지 마세요.|기계 번역은 언어 검토를 받지 않았습니다. 일부 고급 정보와 온라인 기능은 번역이 없어 영어로 표시됩니다.
zh-Hans|验证电子邮件|重设密码|确认删除账户|此链接仅用于本项操作|如果你没有请求此操作，请忽略这封邮件。不要分享此链接。|机器翻译尚未经语言审核。部分高级说明和在线功能在缺少译文时显示英文。
sw|Thibitisha barua pepe yako|Weka upya nenosiri|Thibitisha kufuta akaunti|Tumia kiungo hiki kwa hatua hii pekee|Ikiwa hukuomba hatua hii, puuza ujumbe. Usishiriki kiungo hiki.|Tafsiri ya mashine haijakaguliwa kiisimu. Baadhi ya maelezo ya juu na vipengele vya mtandaoni hutumia Kiingereza pale tafsiri inapokosekana.
`.trim().split('\n');
const mail={},notices={};
for(const row of rows){const[locale,verify,reset,remove,instruction,security,notice]=row.split('|');if(!notice)throw Error(locale);mail[locale]={'mail.verify.subject':verify,'mail.reset.subject':reset,'mail.delete.subject':remove,'mail.verify.body':`${verify}. ${instruction}: {{url}}`,'mail.reset.body':`${reset}. ${instruction}: {{url}}`,'mail.delete.body':`${remove}. ${instruction}: {{url}}`,'mail.security':security};notices[locale]=notice;}
fs.writeFileSync('src/locales/mail.json',JSON.stringify(mail,null,2)+'\n');
fs.writeFileSync('src/locales/notices.json',JSON.stringify(notices,null,2)+'\n');
