import {useRef,useState} from 'react';
import {lessons,gradeLesson} from './lessons';
import {t,tr,formatNumber,type Locale} from './i18n';
import {words} from './components';
import type {Attempt,Mode} from './storage';

export default function Drills({locale,mode,onAttempt}:{locale:Locale;mode:Mode;onAttempt:(a:Attempt)=>Promise<void>}){
  const [index,setIndex]=useState(0),[input,setInput]=useState(''),[submitted,setSubmitted]=useState(false),[shown,setShown]=useState(mode==='learn'),[error,setError]=useState('');const submitting=useRef(false);const generation=useRef(0);
  const lesson=lessons[index];const grade=submitted?gradeLesson(lesson,Number(input)):null;
  async function submit(){if(submitting.current||submitted)return;setError('');if(!input.trim()||!Number.isFinite(Number(input))){setError(words(locale,'Enter a finite number.','Introdu un număr finit.'));return;}submitting.current=true;const run=generation.current;try{const g=gradeLesson(lesson,Number(input));await onAttempt({id:crypto.randomUUID(),lessonId:lesson.id,version:lesson.version,answer:Number(input),correct:g.correct,errorType:g.errorType??'none',timestamp:new Date().toISOString()});if(run===generation.current){setSubmitted(true);setShown(true)}}catch(e){setError((e as Error).message)}finally{submitting.current=false}}
  function choose(i:number){generation.current++;setIndex(i);setInput('');setSubmitted(false);setShown(mode==='learn');setError('')}
  return <div className="drills-layout"><aside className="panel curriculum"><span className="eyebrow">{words(locale,'THE REASONING PATH','CALEA RAȚIONAMENTULUI')}</span><h2>{tr(locale,'drillsCount',{count:lessons.length})}</h2><p>{words(locale,'Small questions. Transferable skills.','Întrebări scurte. Abilități transferabile.')}</p><div className="lesson-list">{lessons.map((l,i)=><button key={l.id} className={i===index?'selected':''} onClick={()=>choose(i)}><span>{String(i+1).padStart(2,'0')}</span><div><b>{l.title[locale]}</b><small>{l.topic}</small></div></button>)}</div></aside>
  <section className="panel drill-card" data-testid="drill-card"><div className="section-heading"><span className="eyebrow">{words(locale,'DRILL','EXERCIȚIU')} {String(index+1).padStart(2,'0')} / {lessons.length}</span><span className="badge">{lesson.method}</span></div><h1>{lesson.title[locale]}</h1><p className="drill-prompt">{lesson.prompt[locale]}</p><div className="info-set"><span className="eyebrow">{words(locale,'GIVEN AT THE DECISION','DATELE DECIZIEI')}</span><dl>{Object.entries(lesson.information).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{Array.isArray(v)?v.join(', '):v}</dd></div>)}</dl></div>
    <form onSubmit={e=>{e.preventDefault();void submit()}}><label>{t(locale,'answer')} · {lesson.unit}<input aria-label="Drill answer" type="number" step="any" value={input} disabled={submitted} onChange={e=>setInput(e.target.value)}/></label><div className="button-row"><button className="primary" type="submit" disabled={submitted}>{t(locale,'submit')}</button><button type="button" onClick={()=>choose((index+1)%lessons.length)}>{t(locale,'next')} →</button><button type="button" onClick={()=>choose(index)}>{t(locale,'replay')}</button></div></form>
    {error&&<p role="alert" className="error">{error}</p>}{grade&&<p role="status" className={grade.correct?'success':'notice'}>{grade.correct?'✓ ':''}{t(locale,grade.correct?'correct':'tryAgain')} · {grade.errorType}</p>}
    {shown?<div className="lesson-explanation" data-testid="drill-explanation"><span className="eyebrow">{t(locale,'explanation')}</span><h2><bdi>{formatNumber(locale,lesson.answer,{maximumFractionDigits:4})} {lesson.unit}</bdi></h2><p>{lesson.explanation[locale].includes("\n")?<><bdi dir="ltr">{lesson.explanation[locale].split("\n")[0]}</bdi><br/>{lesson.explanation[locale].split("\n").slice(1).join("\n")}</>:lesson.explanation[locale]}</p><p className="muted">{lesson.id} · v{lesson.version} · {words(locale,'Tolerance','Toleranță')}: ±{lesson.tolerance} {lesson.unit}</p></div>:<p className="notice">{words(locale,'Guess first: the worked answer appears after you submit. A correct calculation can still lose a hand.','Răspunde întâi: explicația apare după trimitere. Un calcul corect poate pierde mâna.')}</p>}
    <details><summary>{words(locale,'Prerequisites & replay record','Cerințe anterioare și date pentru reluare')}</summary><p>{lesson.prerequisites.join(', ')||words(locale,'Start here.','Începe aici.')}</p><pre dir="ltr">{JSON.stringify(lesson.replay,null,2)}</pre></details>
  </section></div>
}

