import {supportedLocales,tr,type Locale} from './i18n';
export type LocalText = Record<Locale, string>;
export type Lesson = {
  id: string; version: 1; topic: string; title: LocalText; prompt: LocalText;
  answer: number; tolerance: number; unit: '%' | 'chips' | 'count' | 'rank' | 'seat';
  explanation: LocalText; prerequisites: string[]; information: Record<string, string | number | number[]>;
  gradeType: 'exact-number' | 'numeric-tolerance';
  method: 'EXACT' | 'APPROXIMATION' | 'ASSUMPTION-DEPENDENT';
  replay: { kind: 'calculation'; lessonId: string; version: 1; inputs: Record<string, string | number | number[]> };
};
const text = (en: string, ro: string): LocalText => ({ en, ro }) as LocalText;
function lesson(id: string, topic: string, title: LocalText, prompt: LocalText, answer: number,
  unit: Lesson['unit'], explanation: LocalText, information: Lesson['information'],
  prerequisites: string[] = [], method: Lesson['method'] = 'EXACT', tolerance = unit === '%' ? 0.05 : 0): Lesson {
  for(const locale of supportedLocales){if(locale==='en'||locale==='ro')continue;title[locale]=tr(locale,`lessons.${id}.title`);prompt[locale]=tr(locale,`lessons.${id}.prompt`);explanation[locale]=tr(locale,`lessons.${id}.explanation`);}
  return { id, version: 1, topic, title, prompt, answer, tolerance, unit, explanation, prerequisites, information,
    method, gradeType: tolerance ? 'numeric-tolerance' : 'exact-number', replay: { kind: 'calculation', lessonId: id, version: 1, inputs: { ...information } } };
}
export const lessons: Lesson[] = [
  lesson('HIL-001', 'rankings', text('Five cards decide', 'Cinci cărți decid'),
    text('In Hold’em, how many cards form your final ranked hand?', 'În Hold’em, câte cărți alcătuiesc mâna finală evaluată?'), 5, 'count',
    text('Exactly five. Choose the strongest five from your two hole cards and five board cards; you may use zero, one or two hole cards. Seven cards are available, but seven are not ranked as a hand.', 'Exact cinci. Alegi cele mai bune cinci dintre cele două cărți proprii și cele cinci comune; poți folosi zero, una sau două cărți proprii. Sunt disponibile șapte, dar mâna evaluată are cinci.'), { rule: 'best 5 of 7' }),
  lesson('HIL-002', 'rankings', text('The low ace', 'Asul mic'),
    text('A♣ 2♦ 3♥ 4♠ 5♣ is a straight. What is its highest rank? Enter 2–14; ace = 14.', 'A♣ 2♦ 3♥ 4♠ 5♣ este o chintă. Care este rangul maxim al chintei? Scrie 2–14; as = 14.'), 5, 'rank',
    text('This is a five-high straight, called a wheel. The ace acts below the deuce here. It does not make an ace-high straight; Q-K-A-2-3 is not a straight.', 'Este o chintă până la cinci. Asul este sub doi în această combinație. Nu este o chintă până la as; Q-K-A-2-3 nu este chintă.'), { cards: 'Ac 2d 3h 4s 5c' }, ['HIL-001']),
  lesson('HIL-003', 'kickers', text('One pair, next card', 'O pereche, următoarea carte'),
    text('Board: K♣ K♦ 7♥ 4♠ 2♣. Seat 1: A♥ Q♥. Seat 2: A♠ J♠. Which seat wins?', 'Masă: K♣ K♦ 7♥ 4♠ 2♣. Locul 1: A♥ Q♥. Locul 2: A♠ J♠. Ce loc câștigă?'), 1, 'seat',
    text('Both have K-K-A. The next kicker is Q versus J, so seat 1 wins with K-K-A-Q-7. The shared ace does not make the hands equal.', 'Amândoi au K-K-A. Următorul kicker este Q față de J, deci locul 1 câștigă cu K-K-A-Q-7. Asul comun nu face mâinile egale.'), { board: 'Kc Kd 7h 4s 2c', seat1: 'Ah Qh', seat2: 'As Js' }, ['HIL-001']),
  lesson('HIL-004', 'ties', text('The board belongs to everyone', 'Masa aparține tuturor'),
    text('The board is A♠ K♠ Q♠ J♠ T♠. Three players reach showdown. What percentage of the pot is each player entitled to before integer odd-chip allocation?', 'Cărțile comune sunt A♠ K♠ Q♠ J♠ T♠. Trei jucători ajung la showdown. Ce procent din pot revine fiecăruia înainte de repartizarea jetonului indivizibil?'), 100 / 3, '%',
    text('All play the same royal flush on the board: each has 1/3 = 33.333…% equity. Hole-card rank and suit cannot break this tie. Integer odd chips follow the published table rule.', 'Toți folosesc aceeași chintă roială de pe masă: fiecare are 1/3 = 33,333…% echitate. Rangul sau culoarea cărților proprii nu departajează egalitatea. Jetoanele indivizibile urmează regula mesei.'), { board: 'As Ks Qs Js Ts', players: 3 }, ['HIL-001']),
  lesson('HIL-005', 'outs', text('Count the suit', 'Numără culoarea'),
    text('You see four hearts among your two cards and the flop. No other cards are known. How many hearts remain as flush target cards?', 'Vezi patru inimi roșii între cărțile tale și flop. Nu cunoști alte cărți. Câte inimi roșii rămân drept cărți țintă pentru culoare?'), 9, 'count',
    text('There are 13 hearts in a deck, so 13 − 4 = 9 target cards. These are target outs, not guaranteed winning outs: a paired board or a stronger flush can matter.', 'Pachetul conține 13 inimi roșii, deci 13 − 4 = 9 cărți țintă. Sunt outs pentru țintă, nu câștiguri garantate: o masă pereche sau o culoare mai mare poate conta.'), { suitTotal: 13, suitKnown: 4 }),
  lesson('HIL-006', 'draw-probability', text('One card from the flop', 'O carte după flop'),
    text('There are 47 unknown cards and 9 fixed target outs. What is the probability of hitting a target on the next card? Enter a percentage.', 'Sunt 47 de cărți necunoscute și 9 outs fixe. Care este probabilitatea de a nimeri o țintă cu următoarea carte? Scrie procentul.'), 900 / 47, '%',
    text('9/47 × 100 = 19.1489…%. The denominator is the unknown-card count at this decision. This is a target-hit probability, not automatically the probability of winning.', '9/47 × 100 = 19,1489…%. Numitorul este numărul cărților necunoscute în această decizie. Este probabilitatea de a nimeri o țintă, nu automat probabilitatea de câștig.'), { unknown: 47, outs: 9, draws: 1 }, ['HIL-005']),
  lesson('HIL-007', 'draw-probability', text('Two chances without replacement', 'Două șanse fără înlocuire'),
    text('With 47 unknown cards and 9 fixed targets, you will see two cards without further decisions. What is the chance of at least one target, in percent?', 'Cu 47 de cărți necunoscute și 9 ținte fixe, vei vedea două cărți fără alte decizii. Care este șansa de a obține cel puțin o țintă, în procente?'), (1 - 38 * 37 / (47 * 46)) * 100, '%',
    text('Subtract missing twice from 1: 1 − C(38,2)/C(47,2) = 378/1081 = 34.9676…%. Adding 9/47 twice double-counts some outcomes and ignores removal. Fixed targets and two cards seen are required.', 'Scazi ratarea de două ori din 1: 1 − C(38,2)/C(47,2) = 378/1081 = 34,9676…%. Adunarea lui 9/47 de două ori numără dublu unele rezultate și ignoră eliminarea cărților. Se presupun ținte fixe și două cărți văzute.'), { unknown: 47, outs: 9, draws: 2 }, ['HIL-006']),
  lesson('HIL-008', 'draw-probability', text('The turn changes the denominator', 'Turnul schimbă numitorul'),
    text('On the turn, 46 cards are unknown and 9 target outs are still available. What is the river target-hit percentage?', 'Pe turn sunt 46 de cărți necunoscute și încă 9 outs disponibile. Care este probabilitatea procentuală de a nimeri ținta pe river?'), 900 / 46, '%',
    text('9/46 × 100 = 19.5652…%. Use the current information set. Reusing 47 after seeing the turn would include a card that is now known.', '9/46 × 100 = 19,5652…%. Folosești informațiile actuale. Numitorul 47 ar include o carte deja cunoscută după turn.'), { unknown: 46, outs: 9, draws: 1 }, ['HIL-006']),
  lesson('HIL-009', 'approximation', text('A mental shortcut has a label', 'Scurtătura mentală are o etichetă'),
    text('Using the approximate rule of four, what percentage do 9 flop outs suggest for seeing two cards?', 'Folosind regula aproximativă a lui patru, ce procent sugerează 9 outs pe flop pentru două cărți?'), 36, '%',
    text('9 × 4 = 36%, an APPROXIMATION. The fixed-target exact value is about 34.97%. The shortcut is not an equity solver and assumes two cards will be seen.', '9 × 4 = 36%, o APROXIMARE. Valoarea exactă pentru ținte fixe este aproximativ 34,97%. Scurtătura nu este un solver de echitate și presupune că vei vedea două cărți.'), { outs: 9, multiplier: 4 }, ['HIL-007'], 'APPROXIMATION'),
  lesson('HIL-010', 'combinations', text('All starting hands', 'Toate mâinile inițiale'),
    text('How many unordered two-card combinations can be drawn from 52 distinct cards?', 'Câte combinații neordonate de două cărți se pot forma din 52 de cărți distincte?'), 1326, 'count',
    text('C(52,2) = 52 × 51 / 2 = 1326. Divide by two because A♠K♣ and K♣A♠ are the same hand. The 169 grid cells are hand classes, not concrete combinations.', 'C(52,2) = 52 × 51 / 2 = 1326. Împarți la doi deoarece A♠K♣ și K♣A♠ reprezintă aceeași mână. Cele 169 de celule sunt clase, nu combinații concrete.'), { deck: 52, choose: 2 }),
  lesson('HIL-011', 'combinations', text('Pocket pairs', 'Perechi în mână'),
    text('Before any blockers, how many concrete combinations belong to QQ?', 'Înainte de cărți blocante, câte combinații concrete aparțin clasei QQ?'), 6, 'count',
    text('Choose two of four queens: C(4,2) = 6. Four is the number of queens, not the number of pairs.', 'Alegi două dintre cele patru dame: C(4,2) = 6. Patru este numărul damelor, nu al perechilor.'), { ranksAvailable: 4, choose: 2 }, ['HIL-010']),
  lesson('HIL-012', 'combinations', text('Suited combinations', 'Combinații de aceeași culoare'),
    text('Before blockers, how many concrete combinations belong to AKs, where s means suited?', 'Înainte de blocante, câte combinații concrete aparțin AKs, unde s înseamnă aceeași culoare?'), 4, 'count',
    text('One suited ace-king per suit gives 4. AKs excludes the 12 offsuit combinations; AK without a suffix includes both in HIL notation.', 'Câte un as-popă din fiecare culoare înseamnă 4. AKs exclude cele 12 combinații de culori diferite; AK fără sufix le include pe ambele în notația HIL.'), { suits: 4 }, ['HIL-010']),
  lesson('HIL-013', 'combinations', text('Offsuit combinations', 'Combinații de culori diferite'),
    text('Before blockers, how many combinations belong to AKo, where o means offsuit?', 'Înainte de blocante, câte combinații aparțin AKo, unde o înseamnă culori diferite?'), 12, 'count',
    text('Each of four aces can pair with three kings of another suit: 4 × 3 = 12. The four suited hands are excluded.', 'Fiecare dintre cei patru ași se poate combina cu trei popi de altă culoare: 4 × 3 = 12. Cele patru mâini de aceeași culoare sunt excluse.'), { firstRankCards: 4, otherSuitCards: 3 }, ['HIL-012']),
  lesson('HIL-014', 'blockers', text('Your ace removes possibilities', 'Asul tău elimină posibilități'),
    text('You hold A♠ 7♦. No other aces are known. How many AA combinations remain for an opponent?', 'Ai A♠ 7♦. Nu cunoști alți ași. Câte combinații AA rămân pentru un adversar?'), 3, 'count',
    text('Only three aces remain available: C(3,2) = 3. Remove known cards before normalizing range weights. Do not remove simulator-only hidden cards.', 'Rămân disponibili doar trei ași: C(3,2) = 3. Elimini cărțile cunoscute înainte să normalizezi ponderile. Nu elimini cărți secrete cunoscute doar simulatorului.'), { hero: 'As 7d', acesAvailable: 3 }, ['HIL-011']),
  lesson('HIL-015', 'enumeration', text('Every fixed-hand flop runout', 'Fiecare continuare după flop'),
    text('Both two-card hands and three flop cards are known, with no other known dead cards. How many unordered turn/river runouts exist?', 'Cunoști ambele mâini de două cărți și cele trei cărți de flop, fără alte cărți moarte cunoscute. Câte continuări turn/river neordonate există?'), 990, 'count',
    text('52 − 2 − 2 − 3 = 45 available cards. C(45,2) = 990. This unordered count works for terminal showdown equity, where turn/river order does not change the final hand; street decisions need order.', '52 − 2 − 2 − 3 = 45 cărți disponibile. C(45,2) = 990. Numărarea neordonată funcționează pentru echitatea finală, unde ordinea nu schimbă mâna; deciziile pe străzi necesită ordine.'), { known: 7, unknown: 45, choose: 2 }, ['HIL-010']),
  lesson('HIL-016', 'pot-odds', text('The price of this call', 'Prețul acestei plăți'),
    text('The pot was 60. Opponent bets 20, so the current pot P is 80 and your additional call C is 20. With one pot and no further betting, what equity percentage breaks even?', 'Potul era 60. Adversarul pariază 20: potul actual P este 80, iar plata ta suplimentară C este 20. Cu un singur pot și fără alte pariuri, ce echitate procentuală atinge pragul de rentabilitate?'), 20, '%',
    text('C/(P+C) = 20/(80+20) = 20%. Your call makes the final pot 100. Using 20/80 omits your call from the prize. Past contributions are sunk and must not be charged again.', 'C/(P+C) = 20/(80+20) = 20%. Plata ta face potul final 100. Raportul 20/80 omite plata ta din premiu. Contribuțiile trecute sunt deja angajate și nu se scad din nou.'), { potBeforeBet: 60, opponentBet: 20, P: 80, C: 20 }),
  lesson('HIL-017', 'terminal-ev', text('Expected chips from calling', 'Jetoanele așteptate din plată'),
    text('Current pot P = 80, additional call C = 20, equity E = 25%. No rake or future betting; one eligible pot. What is EV(call) relative to folding now?', 'Pot actual P = 80, plată suplimentară C = 20, echitate E = 25%. Fără comision sau pariuri viitoare; un singur pot eligibil. Care este EV(plată) față de renunțarea acum?'), 5, 'chips',
    text('EV = E(P+C) − C = 0.25 × 100 − 20 = +5 chips. This is an expectation over outcomes, not a promise of profit on this hand. Do not subtract earlier contributions again.', 'EV = E(P+C) − C = 0,25 × 100 − 20 = +5 jetoane. Este o medie a rezultatelor, nu promisiunea unui câștig în această mână. Nu scazi din nou contribuțiile anterioare.'), { P: 80, C: 20, E: 0.25 }, ['HIL-016']),
  lesson('HIL-018', 'terminal-ev', text('Below the threshold', 'Sub prag'),
    text('Use P = 80 and C = 20 again, but equity is 15%. With no future betting, what is EV(call)?', 'Folosește din nou P = 80 și C = 20, dar echitatea este 15%. Fără pariuri viitoare, care este EV(plată)?'), -5, 'chips',
    text('0.15 × (80+20) − 20 = −5 chips relative to folding. A later lucky card would not change the correctness of this calculation at the decision.', '0,15 × (80+20) − 20 = −5 jetoane față de renunțare. O carte norocoasă ulterioară nu schimbă corectitudinea calculului la momentul deciziei.'), { P: 80, C: 20, E: 0.15 }, ['HIL-017']),
  lesson('HIL-019', 'bluff', text('A bluff with no fallback', 'Un bluff fără șansă la showdown'),
    text('Pot before your bluff P0 = 100; your bet B = 50. Assume zero equity when called and no future decisions. What fold percentage breaks even?', 'Pot înainte de bluff P0 = 100; pariul tău B = 50. Presupune zero echitate când ești plătit și fără decizii viitoare. Ce procent de renunțări atinge pragul?'), 100 / 3, '%',
    text('Set F×100 − (1−F)×50 = 0, giving F = 50/(100+50) = 1/3. More than 33.333…% folds gives positive EV. This is a break-even model, not a claim that the opponent folds that often.', 'Impunem F×100 − (1−F)×50 = 0: F = 50/(100+50) = 1/3. Peste 33,333…% renunțări dau EV pozitiv. Modelul nu susține că adversarul renunță atât de des.'), { P0: 100, B: 50, equityWhenCalled: 0 }, [], 'ASSUMPTION-DEPENDENT'),
  lesson('HIL-020', 'bluff', text('Put a fold assumption to work', 'Folosește o ipoteză de renunțare'),
    text('P0 = 100, B = 50, assumed fold probability F = 40%, zero equity if called. What is bluff EV in chips?', 'P0 = 100, B = 50, probabilitate presupusă de renunțare F = 40%, zero echitate dacă ești plătit. Care este EV al bluffului în jetoane?'), 10, 'chips',
    text('EV = 0.4×100 − 0.6×50 = 40 − 30 = +10. The fold frequency is an assumption. Showdown equity cannot substitute for that assumption.', 'EV = 0,4×100 − 0,6×50 = 40 − 30 = +10. Frecvența renunțărilor este o ipoteză. Echitatea la showdown nu poate înlocui această ipoteză.'), { P0: 100, B: 50, F: 0.4 }, ['HIL-019'], 'ASSUMPTION-DEPENDENT'),
  lesson('HIL-021', 'equity', text('Ties are fractional wins', 'Egalitățile dau cote fracționare'),
    text('In 100 equally likely outcomes you win alone 30 times, tie with one opponent 20 times, and lose 50 times. What is equity as a percentage?', 'Din 100 de rezultate la fel de probabile, câștigi singur de 30 ori, împarți cu un adversar de 20 ori și pierzi de 50 ori. Care este echitatea procentuală?'), 40, '%',
    text('(30×1 + 20×1/2 + 50×0)/100 = 40%. Win frequency is 30%, tie frequency 20%, loss frequency 50%. Counting each tie as a full win would overstate equity.', '(30×1 + 20×1/2 + 50×0)/100 = 40%. Frecvența câștigurilor este 30%, a egalităților 20%, a pierderilor 50%. O egalitate nu este un câștig întreg.'), { wins: 30, twoWayTies: 20, losses: 50, outcomes: 100 }, ['HIL-004']),
  lesson('HIL-022', 'effective-stack', text('The smaller stack sets the contest', 'Stack-ul mai mic limitează confruntarea'),
    text('Before posting blinds in a heads-up hand, one player has 240 chips and the other has 90. What is the effective stack?', 'Înainte de blinduri, într-o mână cu doi jucători, unul are 240 de jetoane și celălalt 90. Care este stack-ul efectiv?'), 90, 'chips',
    text('min(240,90) = 90 chips per player can be contested against each other. The larger stack cannot win more than the smaller opponent owns in this hand.', 'min(240,90) = 90 de jetoane per jucător se pot disputa între ei. Stack-ul mai mare nu poate câștiga mai mult decât deține adversarul mai mic în această mână.'), { stack1: 240, stack2: 90 }),
  lesson('HIL-023', 'position', text('Heads-up changes the blinds', 'Blindurile cu doi jucători'),
    text('Heads-up: seat 1 is button/small blind; seat 2 is big blind. Both can act. Which seat acts first preflop?', 'Doi jucători: locul 1 este buton/blind mic; locul 2 este blind mare. Ambii pot acționa. Cine acționează primul preflop?'), 1, 'seat',
    text('Button/small blind acts first preflop, then last after the flop. Position changes the information available when deciding, but does not itself supply an exact action strategy.', 'Butonul/blindul mic acționează primul preflop și ultimul după flop. Poziția schimbă informațiile disponibile, fără a furniza singură o strategie exactă.'), { button: 1, smallBlind: 1, bigBlind: 2, street: 'preflop' }),
  lesson('HIL-024', 'implied-odds', text('A future payment is an assumption', 'O plată viitoare este o ipoteză'),
    text('Toy model: P = 80, C = 20, hit probability 10%. On a hit you always win and collect an extra 100 from the opponent; on a miss you lose with no more payment. What is call EV?', 'Model simplificat: P = 80, C = 20, șansă de reușită 10%. La reușită câștigi mereu și primești încă 100 de la adversar; la ratare pierzi fără altă plată. Care este EV al plății?'), 0, 'chips',
    text('0.10×(80+20+100) − 20 = 0. Future opponent payment is conditional on hitting and winning. Real opponents may not pay, targets may be dirty, and your future contributions must also be accounted for.', '0,10×(80+20+100) − 20 = 0. Plata viitoare a adversarului este condiționată de reușită și câștig. Adversarii reali pot refuza plata, țintele pot fi murdare, iar contribuțiile tale viitoare trebuie incluse.'), { P: 80, C: 20, hit: 0.1, futureOpponentPayment: 100 }, ['HIL-017'], 'ASSUMPTION-DEPENDENT'),
  lesson('HIL-025', 'reverse-implied-odds', text('A costly second-best hand', 'O mână inferioară costisitoare'),
    text('In a toy model, a call has baseline EV +5 chips. Separately, 10% of all outcomes cost an extra 80 chips when a second-best hand pays later. What is adjusted EV?', 'Într-un model simplificat, o plată are EV de bază +5 jetoane. Separat, 10% din toate rezultatele costă încă 80 când o mână inferioară plătește ulterior. Care este EV ajustat?'), -3, 'chips',
    text('5 − 0.10×80 = −3 chips. This reverse-implied-odds term is a supplied assumption, not something raw showdown equity predicts. Do not count the same future loss twice.', '5 − 0,10×80 = −3 jetoane. Această componentă de cote implicite inverse este o ipoteză dată, nu ceva prezis de echitatea brută. Nu numeri aceeași pierdere viitoare de două ori.'), { baselineEV: 5, extraLossProbability: 0.1, extraLoss: 80 }, ['HIL-024'], 'ASSUMPTION-DEPENDENT'),
  lesson('HIL-026', 'side-pots', text('Eligibility comes before equity', 'Eligibilitatea precede echitatea'),
    text('Three players commit 30, 80 and 80 chips. The player with 30 is all-in. How many chips are in the main pot all three can win?', 'Trei jucători contribuie cu 30, 80 și 80 de jetoane. Cel cu 30 este all-in. Câte jetoane sunt în potul principal pentru care sunt eligibili toți trei?'), 90, 'chips',
    text('3×30 = 90 in the main pot; 2×50 = 100 in the side pot. The short stack has no claim on that side pot. A single win percentage cannot describe both eligibility sets.', '3×30 = 90 în potul principal; 2×50 = 100 în potul lateral. Stack-ul mic nu poate câștiga potul lateral. Un singur procent de câștig nu descrie ambele grupuri eligibile.'), { contributions: [30, 80, 80] }, ['HIL-021']),
  lesson('HIL-027', 'ranges', text('Weights apply to combinations', 'Ponderile se aplică combinațiilor'),
    text('An unblocked range has AA at weight 100% and KK at weight 50%, with all other hands excluded. What percentage of its normalized probability is AA?', 'Un interval fără blocante are AA cu pondere 100% și KK cu pondere 50%; celelalte mâini sunt excluse. Ce procent din probabilitatea normalizată aparține AA?'), 200 / 3, '%',
    text('AA contributes 6×1 = 6 weight units; KK contributes 6×0.5 = 3. AA probability is 6/(6+3) = 66.666…%. A cell weight is not itself its final probability.', 'AA contribuie cu 6×1 = 6 unități; KK cu 6×0,5 = 3. Probabilitatea AA este 6/(6+3) = 66,666…%. Ponderea unei celule nu este direct probabilitatea finală.'), { AAcombinations: 6, AAweight: 1, KKcombinations: 6, KKweight: 0.5 }, ['HIL-011']),
  lesson('HIL-028', 'outs', text('Overlapping target sets', 'Ținte care se suprapun'),
    text('A study hand has 9 flush target cards and 8 straight target cards. Exactly 2 cards belong to both sets. How many distinct targets are there?', 'O mână de studiu are 9 cărți țintă pentru culoare și 8 pentru chintă. Exact 2 cărți aparțin ambelor mulțimi. Câte ținte distincte există?'), 15, 'count',
    text('9 + 8 − 2 = 15 by inclusion-exclusion. Adding 9 and 8 without subtracting the overlap counts two cards twice. Distinct targets are still not necessarily clean winning outs.', '9 + 8 − 2 = 15 prin includere-excludere. Dacă aduni 9 și 8 fără să scazi suprapunerea, numeri două cărți de două ori. Țintele distincte nu sunt neapărat outs curate pentru câștig.'), { flushTargets: 9, straightTargets: 8, overlap: 2 }, ['HIL-005']),
];

export type GradeResult = { correct: boolean; errorType: string | null; expected: number; difference: number | null };
export function gradeLesson(item: Lesson, input: number | string): GradeResult {
  const clean = typeof input === 'string' ? input.trim().replace(',', '.') : input;
  const value = clean === '' ? NaN : Number(clean);
  if (!Number.isFinite(value)) return { correct: false, errorType: 'invalid-number', expected: item.answer, difference: null };
  const difference = Math.abs(value - item.answer);
  const correct = difference <= item.tolerance + 1e-10;
  return { correct, errorType: correct ? null : item.topic, expected: item.answer, difference };
}
