// Translation source, stable keys. Catalog coverage reports distinguish fallbacks.
export const platformEnglish={
 learning:'Learning',community:'Community',account:'Account',help:'Help',faq:'Offline FAQ',faqHelp:'Answers drawn from the 28 original calculation lessons. Available without an account or internet.',search:'Search',guest:'Guest Play',appearance:'Appearance',
 offlineTitle:'Your offline learning notebook',offlineOnline:'Accounts and community belong to the optional online edition. Guest play, odds and lessons remain available here without signing in.',onlineLaunch:'Open the online edition with the POK launcher.',
 adult:'I am 18 or older and accept the adult educational beta community policy.',privacy:'Only information you explicitly submit is sent. Local hands and progress stay in your browser until you choose to synchronize them.',
 email:'Email',password:'Password',name:'Display name',register:'Create account',login:'Sign in',logout:'Sign out',forgot:'Reset password',newPassword:'New password',verifyHelp:'Check your email to verify your account. Test mail is not real email delivery.',genericSent:'If this address is eligible, a message has been sent.',genericLogin:'Sign-in failed. Check your credentials and verification status.',
 moreProviders:'More sign-in options',providers:'Login providers',country:'Country/region (optional)',showAll:'Show all available providers',noProviders:'No external provider is configured. Email remains available.',providerUnavailable:'Not enabled: provider credentials, approval and live verification are separate steps.',neutral:'No country selected',showCountry:'Show my self-selected country',selfSelected:'Self-selected country; not verified nationality',save:'Save',cancel:'Cancel',close:'Close',loading:'Loading…',retry:'Retry',
 questions:'Questions',chat:'Study room',feedback:'Feedback',coach:'Ask AI coach',ask:'Ask a question',sendFeedback:'Send feedback',title:'Title',body:'Message',category:'Category',general:'General',math:'Mathematics',rules:'Rules',accessibility:'Accessibility',bug:'Bug',send:'Send',ticket:'Saved ticket',empty:'No items yet.',reply:'Reply',replies:'Replies',resolve:'Mark resolved',resolved:'Resolved',edit:'Edit',remove:'Delete',report:'Report',reason:'Reason',block:'Mute this member',unblock:'Unmute',older:'Older items',refresh:'Refresh',
 notifications:'Notifications',markRead:'Mark as read',profile:'Profile',exportAccount:'Export account data',deleteAccount:'Request account deletion',deleteHelp:'Deletion requires an email confirmation. Back up your account first. Your offline notebook is separate.',revoke:'Revoke other sessions',security:'Account security',mfaEnable:'Enable authenticator MFA',mfaCode:'Authenticator code',mfaVerify:'Verify MFA',mfaHelp:'Keep the recovery codes private. Production administrative access requires MFA.',
 sync:'Optional synchronization',syncHelp:'Choose what to upload. Nothing is merged automatically. Downloads are reviewed before replacing the local notebook.',syncSettings:'Theme and language',syncProgress:'Drill progress',syncHands:'Selected completed hands',upload:'Upload selected data',download:'Download for review',syncConflict:'The server copy changed. Download and review it before retrying; your local notebook is intact.',clearSync:'Delete synchronized copy',
 control:'Control panel',users:'Users',reports:'Reports / Chat',languages:'Languages',defaults:'Appearance defaults',usage:'AI usage',audit:'Audit history',dictionary:'Moderation dictionary',appeals:'Appeals',role:'Role',target:'Target user ID',duration:'Duration (hours)',warn:'Warn',mute:'Temporarily mute',suspend:'Temporarily suspend',ban:'Ban account',revokeSanction:'Reverse restriction',hide:'Hide message',restore:'Restore message',evidence:'Evidence item ID',apply:'Apply with reason',preview:'Preview samples',activate:'Activate reviewed version',rollback:'Restore version',samples:'Sample messages, one per line',
 coachConsent:'I consent to sending this question and selected lesson/calculation to OpenAI. No private table state is included.',coachQuestion:'Question for POK AI Coach',coachDisabled:'Cloud coach is disabled until an authorized key, supported-location policy and nonzero budget are configured.',coachLabel:'Model-generated explanation. Calculations and grades remain deterministic.',stop:'Stop',deleteChat:'Delete private coach history',lesson:'Approved lesson context',none:'None',cloudDisclosure:'Cloud context: your typed question and selected lesson only. Never paste hidden cards, private messages or sensitive information.',
 localMail:'Local test mailbox',localMailHelp:'Isolated development sink. Messages stay on this loopback server; no actual email is sent.',openMail:'Read test mail',confirmAction:'Confirm this action?',done:'Saved.',error:'The request could not be completed.',
 appeal:'Appeal a restriction',appealHelp:'Provide context for a human review. A community mute does not delete your study progress.',blocked:'Online access is restricted. Your offline lessons remain available.',
 dictionaryHelp:'Signals require context and human review. Dictionary matches never automatically ban a member.',draftTranslation:'Machine-drafted translations have not received independent linguistic review.',
};
