import {useEffect,useRef,useState} from 'react';
import {tr,formatDate,getLocaleMetadata,supportedLocales,type Locale} from './i18n';
import {api,APIError,downloadJSON,streamCoach,type Member,type PlatformStatus,type ContentItem} from './platform-api';
import type {SavedData} from './storage';
import {defaults,validateData} from './storage';
import {useAppearance,type Appearance} from './appearance';
import {lessons} from './lessons';
import FAQ from './FAQ';
declare const __POK_ONLINE__:boolean;
export const onlineEdition=__POK_ONLINE__;
type Area='community'|'account'|'help';
type Tab='questions'|'chat'|'feedback'|'coach'|'faq'|'account'|'control';
export default function Platform({locale,area,data,onImport}:{locale:Locale;area:Area;data:SavedData;onImport:(data:SavedData,appearance?:Appearance)=>void}){
 const [tab,setTab]=useState<Tab>(area==='account'?'account':area==='help'?'faq':'questions');
 const [status,setStatus]=useState<PlatformStatus|null>(null),[me,setMe]=useState<Member|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(false),[notifications,setNotifications]=useState<any[]>([]);
 const identity=useRef<string|null>(null),generation=useRef(0);const t=(key:string)=>tr(locale,`platform.${key}`);
 useEffect(()=>{setTab(area==='account'?'account':area==='help'?'faq':'questions')},[area]);
 const report=(e:unknown)=>setError(e instanceof APIError?`${t('error')} (${e.code})`:t('error'));
 async function refresh(){if(!onlineEdition)return;const token=++generation.current;setLoading(true);try{const s=await api<PlatformStatus>('/api/status');if(token!==generation.current)return;setStatus(s);let member:Member|null=null;try{member=await api<Member>('/api/me')}catch(e){if(!(e instanceof APIError&&[401,403].includes(e.status)))throw e}if(token!==generation.current)return;identity.current=member?.user.id??null;setMe(member);window.dispatchEvent(new Event('pok-profile-change'));if(member){const n=await api('/api/notifications');if(token===generation.current)setNotifications(n.items)}else setNotifications([])}catch(e){if(token===generation.current)report(e)}finally{if(token===generation.current)setLoading(false)}}
 useEffect(()=>{void refresh();const channel=onlineEdition?new BroadcastChannel('pok:account-change'):null;if(channel)channel.onmessage=()=>{setMe(null);setNotifications([]);void refresh()};return()=>{generation.current++;channel?.close()}},[]);
 async function work(fn:()=>Promise<unknown>,message=t('done')){setError('');setNotice('');setLoading(true);try{await fn();setNotice(message)}catch(e){report(e)}finally{setLoading(false)}}
 async function logout(){await work(async()=>{await api('/api/auth/sign-out','POST',{});generation.current++;setMe(null);setNotifications([]);identity.current=null;window.dispatchEvent(new Event('pok-profile-change'));const c=new BroadcastChannel('pok:account-change');c.postMessage('logout');c.close();setTab('account')})}
 if(!onlineEdition&&tab!=='faq')return <section className="panel"><h2>{t('offlineTitle')}</h2><p>{t('offlineOnline')}</p><p>{t('onlineLaunch')}</p><button onClick={()=>setTab('faq')}>{t('faq')}</button></section>;
 return <div className="platform-page"><nav className="button-row" aria-label="Help and community">{(['faq','questions','feedback','chat','coach','account'] as Tab[]).map(k=><button key={k} aria-current={tab===k?'page':undefined} className={tab===k?'primary':''} onClick={()=>{setTab(k);setError('');setNotice('')}}>{t(k)}</button>)}{me&&me.user.role!=='member'&&<button onClick={()=>setTab('control')}>{t('control')}</button>}</nav>
 {loading&&<p role="status">{t('loading')}</p>}{error&&<p className="error" role="alert">{error}<button onClick={()=>void refresh()}>{t('retry')}</button></p>}{notice&&<p className="notice" role="status">{notice}</p>}
 {tab==='faq'?<FAQ locale={locale}/>:!status?<section className="panel"><p>{t('offlineOnline')}</p><button onClick={()=>void refresh()}>{t('retry')}</button></section>:!me?<AccountEntry locale={locale} status={status} onLogin={refresh} report={report}/>:<>
 <div className="member-strip"><bdi>{me.user.name}</bdi><span>{me.user.role}</span><button onClick={logout}>{t('logout')}</button></div>
 {me.restrictions.map(r=><details className="notice" key={r.id}><summary>{r.kind}: {r.reason}</summary><form onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);void work(()=>api('/api/appeals','POST',{sanctionId:r.id,body:form.get('appeal')},me.csrf))}}><label>{t('appeal')}<textarea name="appeal" required maxLength={1000}/></label><button>{t('send')}</button></form></details>)}
 {tab==='account'&&<AccountSettings key={me.user.id} locale={locale} status={status} me={me} data={data} onImport={onImport} onRefresh={refresh} work={work}/>}
 {(['questions','chat','feedback'] as Tab[]).includes(tab)&&<Community key={`${me.user.id}:${tab}`} locale={locale} kind={tab==='questions'?'question':tab as 'chat'|'feedback'} me={me} work={work}/>}
 {tab==='coach'&&<Coach key={me.user.id} locale={locale} me={me} work={work}/>}
 {tab==='control'&&<ControlPanel key={me.user.id} locale={locale} me={me} work={work}/>}
 {notifications.length>0&&<details className="panel"><summary>{t('notifications')} ({notifications.filter(n=>!n.seen).length})</summary>{notifications.map(n=><p key={n.id}>{n.body} <bdi>{n.target_id}</bdi></p>)}<button onClick={()=>void work(async()=>{await api('/api/notifications/read','POST',{},me.csrf);setNotifications(n=>n.map(x=>({...x,seen:1})))})}>{t('markRead')}</button></details>}
 </> }</div>
}
function AccountEntry({locale,status,onLogin,report}:{locale:Locale;status:PlatformStatus;onLogin:()=>Promise<void>;report:(e:unknown)=>void}){
 const t=(k:string)=>tr(locale,`platform.${k}`),[mode,setMode]=useState<'login'|'register'|'forgot'>('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[adult,setAdult]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[country,setCountry]=useState(''),[mail,setMail]=useState<any[]>([]),[mfa,setMfa]=useState(false),[code,setCode]=useState('');
 async function submit(){setBusy(true);setMessage('');try{if(mfa){await api('/api/auth/two-factor/verify-totp','POST',{code});await onLogin();return}if(mode==='register'){await api('/api/auth/sign-up/email','POST',{email,password,name,locale,adultAccepted:adult,callbackURL:location.origin+'/holdem-lab/'});setMessage(t('verifyHelp'));setPassword('')}else if(mode==='forgot'){await api('/api/auth/request-password-reset','POST',{email,redirectTo:location.origin+'/holdem-lab/'});setMessage(t('genericSent'))}else{const result=await api('/api/auth/sign-in/email','POST',{email,password});if(result.twoFactorRedirect){setMfa(true);return}setPassword('');const c=new BroadcastChannel('pok:account-change');c.postMessage('login');c.close();await onLogin()}}catch{setMessage(mode==='login'?t('genericLogin'):t('genericSent'))}finally{setBusy(false)}}
 const resetToken=new URLSearchParams(location.search).get('token');
 return <div className="two-column"><section className="panel"><h2>{t(mode)}</h2><p>{t('privacy')}</p>{resetToken?<form onSubmit={e=>{e.preventDefault();void api('/api/auth/reset-password','POST',{token:resetToken,newPassword:password}).then(()=>{history.replaceState(null,'',location.pathname);setMessage(t('done'));setPassword('')}).catch(report)}}><label>{t('newPassword')}<input type="password" required minLength={12} autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button>{t('save')}</button></form>:<form onSubmit={e=>{e.preventDefault();void submit()}}>
 {mfa?<label>{t('mfaCode')}<input autoComplete="one-time-code" value={code} onChange={e=>setCode(e.target.value)}/></label>:<><label>{t('email')}<input type="email" required autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label>{mode==='register'&&<label>{t('name')}<input required maxLength={60} autoComplete="nickname" value={name} onChange={e=>setName(e.target.value)}/></label>}{mode!=='forgot'&&<label>{t('password')}<input type="password" required minLength={12} maxLength={128} autoComplete={mode==='register'?'new-password':'current-password'} value={password} onChange={e=>setPassword(e.target.value)}/></label>}{mode==='register'&&<label className="check-label"><input type="checkbox" required checked={adult} onChange={e=>setAdult(e.target.checked)}/>{t('adult')}</label>}</>}
 <button className="primary" disabled={busy}>{t(mfa?'mfaVerify':mode)}</button></form>}{message&&<p role="status">{message}</p>}<div className="button-row">{(['login','register','forgot'] as const).filter(m=>m!==mode).map(m=><button key={m} onClick={()=>{setMode(m);setMfa(false);setMessage('')}}>{t(m)}</button>)}</div></section>
 <section className="panel"><h2>{t('providers')}</h2>{status.providers.filter(p=>p.enabled&&['google','facebook'].includes(p.id)).map(p=><button key={p.id} onClick={()=>void api('/api/auth/sign-in/social','POST',{provider:p.id,requestSignUp:mode==='register',adultAccepted:adult,locale,callbackURL:location.origin+'/holdem-lab/'}).then(r=>{if(r.url)location.assign(r.url)}).catch(report)}>{p.name}</button>)}<details><summary>{t('moreProviders')}</summary><label>{t('country')}<input list="country-options" value={country} onChange={e=>setCountry(e.target.value)}/><datalist id="country-options">{status.countries.map(c=><option key={c} value={c}>{new Intl.DisplayNames([locale],{type:'region'}).of(c)}</option>)}</datalist></label><button onClick={()=>setCountry('')}>{t('showAll')}</button>{status.providers.filter(p=>p.enabled&&p.id!=='snapchat').map(p=><button key={p.id} onClick={()=>void api('/api/auth/sign-in/social','POST',{provider:p.id,requestSignUp:mode==='register',adultAccepted:adult,locale,callbackURL:location.origin+'/holdem-lab/'}).then(r=>{if(r.url)location.assign(r.url)}).catch(report)}>{p.name}</button>)}{!status.providers.some(p=>p.enabled)&&<p>{t('noProviders')}</p>}<p>{t('providerUnavailable')}</p>{status.providers.filter(p=>!p.enabled).map(p=><p key={p.id}><b>{p.name}</b> · {p.support}</p>)}</details>
 {status.mail==='LOCAL_TEST_SINK'&&<details><summary>{t('localMail')}</summary><p>{t('localMailHelp')}</p><button disabled={!email} onClick={()=>void api('/api/dev/mail?email='+encodeURIComponent(email)).then(r=>setMail(r.messages)).catch(report)}>{t('openMail')}</button>{mail.map((m,i)=><p key={i}><a href={m.url}>{m.purpose}</a></p>)}</details>}</section></div>
}
type Work=(fn:()=>Promise<unknown>,message?:string)=>Promise<void>;
function AccountSettings({locale,status,me,data,onImport,onRefresh,work}:{locale:Locale;status:PlatformStatus;me:Member;data:SavedData;onImport:(d:SavedData,appearance?:Appearance)=>void;onRefresh:()=>Promise<void>;work:Work}){
 const t=(k:string)=>tr(locale,`platform.${k}`),{appearance}=useAppearance(),[name,setName]=useState(me.user.name),[country,setCountry]=useState(me.profile.country??''),[show,setShow]=useState(!!me.profile.show_country),[password,setPassword]=useState(''),[mfa,setMfa]=useState<any>(null),[code,setCode]=useState(''),[sync,setSync]=useState<any>(null),[include,setInclude]=useState({settings:true,attempts:false,hands:false}),[selected,setSelected]=useState<string[]>([]),[deleteConfirm,setDeleteConfirm]=useState(false),[mail,setMail]=useState<any[]>([]),[linked,setLinked]=useState<any[]>([]);
 return <div className="two-column"><section className="panel"><h2>{t('profile')}</h2><form onSubmit={e=>{e.preventDefault();void work(async()=>{await api('/api/profile','PATCH',{name,country,showCountry:show,locale},me.csrf);await onRefresh()})}}><label>{t('name')}<input value={name} maxLength={60} onChange={e=>setName(e.target.value)}/></label><label>{t('country')}<select value={country} onChange={e=>setCountry(e.target.value)}><option value="">{t('neutral')}</option>{status.countries.map(c=><option value={c} key={c}>{new Intl.DisplayNames([locale],{type:'region'}).of(c)} ({c})</option>)}</select></label><label className="check-label"><input type="checkbox" checked={show} onChange={e=>setShow(e.target.checked)}/>{t('showCountry')}</label><p>{t('selfSelected')}</p><button>{t('save')}</button></form>
 <details><summary>{t('security')}</summary><button onClick={()=>void work(()=>api('/api/auth/revoke-other-sessions','POST',{}))}>{t('revoke')}</button><label>{t('password')}<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button onClick={()=>void work(async()=>{setMfa(await api('/api/auth/two-factor/enable','POST',{password}));setPassword('')})}>{t('mfaEnable')}</button>{mfa&&<><p>{t('mfaHelp')}</p><p><bdi>{mfa.totpURI}</bdi></p><pre>{mfa.backupCodes?.join('\n')}</pre><label>{t('mfaCode')}<input value={code} onChange={e=>setCode(e.target.value)}/></label><button onClick={()=>void work(async()=>{await api('/api/auth/two-factor/verify-totp','POST',{code});setMfa(null);setCode('');await onRefresh()})}>{t('mfaVerify')}</button></>}
 {status.providers.filter(p=>p.enabled).map(p=><button key={p.id} onClick={()=>void work(async()=>{const r=await api('/api/auth/link-social','POST',{provider:p.id,providerId:p.id,callbackURL:location.origin+'/holdem-lab/'});if(r.url)location.assign(r.url)})}>Link {p.name}</button>)}
 <button onClick={()=>void work(async()=>setLinked(await api('/api/auth/list-accounts')))}>Linked accounts</button>{linked.map(a=><button key={a.id} onClick={()=>void work(async()=>{await api('/api/auth/unlink-account','POST',{providerId:a.providerId,accountId:a.accountId});setLinked(await api('/api/auth/list-accounts'))})}>Unlink {a.providerId}</button>)}</details><button onClick={()=>void work(async()=>downloadJSON(await api('/api/account/export'),'POK-account.json'))}>{t('exportAccount')}</button><details><summary>{t('deleteAccount')}</summary><p>{t('deleteHelp')}</p><label className="check-label"><input type="checkbox" checked={deleteConfirm} onChange={e=>setDeleteConfirm(e.target.checked)}/>{t('confirmAction')}</label><button className="danger" disabled={!deleteConfirm} onClick={()=>void work(()=>api('/api/auth/delete-user','POST',{callbackURL:location.origin+'/holdem-lab/'}),t('genericSent'))}>{t('deleteAccount')}</button></details>{status.mail==='LOCAL_TEST_SINK'&&<details><summary>{t('localMail')}</summary><p>{t('localMailHelp')}</p><button onClick={()=>void work(async()=>setMail((await api('/api/dev/mail?email='+encodeURIComponent(me.user.email))).messages))}>{t('openMail')}</button>{mail.map((m,i)=><p key={i}><a href={m.url}>{m.purpose}</a></p>)}</details>}</section>
 <section className="panel"><h2>{t('sync')}</h2><p>{t('syncHelp')}</p>{(['settings','attempts','hands'] as const).map(k=><label className="check-label" key={k}><input type="checkbox" checked={include[k]} onChange={e=>setInclude({...include,[k]:e.target.checked})}/>{t(k==='settings'?'syncSettings':k==='attempts'?'syncProgress':'syncHands')}</label>)}{include.hands&&<div className="hand-picker">{data.hands.map(h=><label key={h.id} className="check-label"><input type="checkbox" checked={selected.includes(h.id)} onChange={e=>setSelected(e.target.checked?[...selected,h.id]:selected.filter(id=>id!==h.id))}/><bdi>{h.id.slice(0,16)} · {h.street}</bdi></label>)}</div>}
 <button onClick={()=>void work(async()=>{const remote=await api('/api/sync');setSync(remote);downloadJSON(remote,'POK-sync-review.json')})}>{t('download')}</button><button onClick={()=>void work(async()=>{const current=sync??await api('/api/sync');const payload={...(include.settings?{settings:data.settings,appearance}:{}),...(include.attempts?{attempts:data.attempts}:{}),...(include.hands?{hands:data.hands.filter(h=>selected.includes(h.id))}:{})};const r=await api('/api/sync','PUT',{consent:true,revision:current.revision,payload},me.csrf);setSync({...r,payload})})}>{t('upload')}</button>
 {sync?.payload&&<details><summary>{t('download')}</summary><p>Revision {sync.revision} · {sync.payload.hands?.length??0} hands · {sync.payload.attempts?.length??0} attempts</p><button onClick={()=>{const candidate=validateData({...defaults(),...data,...sync.payload,settings:{...data.settings,...sync.payload.settings},hand:data.hand});onImport(candidate,sync.payload.appearance)}}>{tr(locale,'import')}</button></details>}
 <button onClick={()=>void work(async()=>{await api('/api/sync','DELETE',{},me.csrf);setSync(null)})}>{t('clearSync')}</button></section></div>
}
function Community({locale,kind,me,work}:{locale:Locale;kind:'question'|'chat'|'feedback';me:Member;work:Work}){
 const t=(k:string)=>tr(locale,`platform.${k}`),[items,setItems]=useState<ContentItem[]>([]),[body,setBody]=useState(''),[title,setTitle]=useState(''),[category,setCategory]=useState('general'),[query,setQuery]=useState(''),[next,setNext]=useState<number|null>(null),[thread,setThread]=useState<ContentItem|null>(null),[replies,setReplies]=useState<ContentItem[]>([]),[reply,setReply]=useState(''),[reportItem,setReportItem]=useState<ContentItem|null>(null),[reason,setReason]=useState(''),[ticketId,setTicketId]=useState(''),[editing,setEditing]=useState<string|null>(null),[editText,setEditText]=useState('');
 const seq=useRef(0);async function load(before?:number){const token=++seq.current;const r=await api(`/api/content?kind=${kind}&q=${encodeURIComponent(query)}${before?'&before='+before:''}`);if(token!==seq.current)return;setItems(r.items);setNext(r.next)}
 useEffect(()=>{void work(()=>load());const interval=kind==='chat'?setInterval(()=>void work(()=>load(),''),5000):undefined;return()=>{seq.current++;clearInterval(interval)}},[kind,query]);
 async function openThread(item:ContentItem){setThread(item);const r=await api(`/api/content?kind=${kind==='feedback'?'feedback-reply':'answer'}&parentId=${encodeURIComponent(item.id)}`);setReplies(r.items)}
 const render=(item:ContentItem)=><article className="community-item" key={item.id}><div className="row-between"><strong><bdi>{item.name}</bdi></strong><time>{formatDate(locale,new Date(item.created_at))}</time></div>{item.country&&<span tabIndex={0} title={t('selfSelected')} className="country-badge"><img src={`/holdem-lab/flags/${item.country.toLowerCase()}.svg`} alt=""/><bdi>{item.country}</bdi> · {new Intl.DisplayNames([locale],{type:'region'}).of(item.country)}</span>}{item.title&&<h3>{item.title}</h3>}<p className="user-text" dir="auto">{item.body}</p>{item.status==='resolved'&&<span className="badge">✓ {t('resolved')}</span>}{editing===item.id?<form onSubmit={e=>{e.preventDefault();void work(async()=>{await api('/api/content/'+item.id,'PATCH',{body:editText},me.csrf);setEditing(null);await load()})}}><textarea value={editText} onChange={e=>setEditText(e.target.value)} required maxLength={2000}/><button>{t('save')}</button><button type="button" onClick={()=>setEditing(null)}>{t('cancel')}</button></form>:<div className="button-row">{kind!=='chat'&&!item.parent_id&&<button onClick={()=>void work(()=>openThread(item),'')}>{t('replies')}</button>}{item.author_id===me.user.id?<><button onClick={()=>{setEditing(item.id);setEditText(item.body)}}>{t('edit')}</button><button onClick={()=>void work(async()=>{await api('/api/content/'+item.id,'DELETE',{},me.csrf);await load()})}>{t('remove')}</button>{kind!=='chat'&&<button onClick={()=>void work(async()=>{await api('/api/content/'+item.id+'/resolve','POST',{},me.csrf);await load()})}>{t('resolve')}</button>}</>:<><button onClick={()=>{setReportItem(item);setReason('')}}>{t('report')}</button><button onClick={()=>void work(async()=>{await api('/api/blocks','POST',{targetId:item.author_id,blocked:true},me.csrf);await load()})}>{t('block')}</button></>}</div>}</article>;
 return <section className="panel"><h2>{t(kind==='question'?'questions':kind)}</h2><p>{kind==='chat'?'Moderated study discussion · human-versus-bots practice is separate.':t('privacy')}</p><label>{t('search')}<input type="search" value={query} onChange={e=>setQuery(e.target.value)}/></label><button onClick={()=>void work(()=>load(),'')}>{t('refresh')}</button><form onSubmit={e=>{e.preventDefault();void work(async()=>{const r=await api('/api/content','POST',{kind,title,body,category},me.csrf);setBody('');setTitle('');setTicketId(r.id);await load();return r},t('ticket'))}}>{kind!=='chat'&&<><label>{t('title')}<input required maxLength={120} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>{t('category')}<select value={category} onChange={e=>setCategory(e.target.value)}>{['general','math','rules','accessibility','bug'].map(k=><option key={k} value={k}>{t(k)}</option>)}</select></label></>}<label>{t('body')}<textarea value={body} required maxLength={2000} onChange={e=>setBody(e.target.value)}/></label><button className="primary">{t('send')}</button></form>
 <div aria-live="polite">{ticketId&&<p>{t('ticket')}: <bdi>{ticketId}</bdi></p>}{items.length?items.map(render):<p>{t('empty')}</p>}</div>{next&&<button onClick={()=>void work(()=>load(next),'')}>{t('older')}</button>}
 {thread&&<section className="panel thread"><div className="row-between"><h3>{thread.title}</h3><button onClick={()=>setThread(null)}>{t('close')}</button></div>{replies.map(render)}<form onSubmit={e=>{e.preventDefault();void work(async()=>{await api('/api/content','POST',{kind:kind==='feedback'?'feedback-reply':'answer',parentId:thread.id,body:reply},me.csrf);setReply('');await openThread(thread)})}}><label>{t('reply')}<textarea required maxLength={2000} value={reply} onChange={e=>setReply(e.target.value)}/></label><button>{t('send')}</button></form></section>}
 {reportItem&&<section className="panel"><h3>{t('report')}</h3><form onSubmit={e=>{e.preventDefault();void work(async()=>{await api('/api/reports','POST',{contentId:reportItem.id,reason},me.csrf);setReportItem(null)})}}><label>{t('reason')}<textarea required maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label><button>{t('send')}</button><button type="button" onClick={()=>setReportItem(null)}>{t('cancel')}</button></form></section>}
 <details><summary>{t('unblock')}</summary><button onClick={()=>void work(async()=>{const r=await api('/api/blocks');for(const b of r.items)await api('/api/blocks','POST',{targetId:b.target_id,blocked:false},me.csrf);await load()})}>{t('unblock')} · all</button></details></section>
}
function Coach({locale,me,work}:{locale:Locale;me:Member;work:Work}){
 const t=(k:string)=>tr(locale,`platform.${k}`),[status,setStatus]=useState<any>(null),[question,setQuestion]=useState(''),[lessonId,setLessonId]=useState(''),[consent,setConsent]=useState(false),[answer,setAnswer]=useState(''),[running,setRunning]=useState(false);const controller=useRef<AbortController|null>(null);
 useEffect(()=>{void work(async()=>setStatus(await api('/api/coach/status')),'');return()=>controller.current?.abort()},[]);
 return <section className="panel"><h2>POK AI Coach</h2><p>{t('coachLabel')}</p><p>{t('cloudDisclosure')}</p>{(!status?.enabled||!status?.configured)&&<p className="notice">{t('coachDisabled')}</p>}<form onSubmit={e=>{e.preventDefault();void work(async()=>{controller.current=new AbortController();setRunning(true);setAnswer('');try{await streamCoach({question,consent,...(lessonId?{lessonId}:{})},me.csrf,controller.current.signal,setAnswer)}finally{setRunning(false)}})}}><label>{t('lesson')}<select value={lessonId} onChange={e=>setLessonId(e.target.value)}><option value="">{t('none')}</option>{lessons.map(l=><option key={l.id} value={l.id}>{tr(locale,`lessons.${l.id}.title`)}</option>)}</select></label><label>{t('coachQuestion')}<textarea maxLength={2000} required value={question} onChange={e=>setQuestion(e.target.value)}/></label><label className="check-label"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>{t('coachConsent')}</label><button disabled={!consent||running||!status?.enabled||!status?.configured}>{t('send')}</button>{running&&<button type="button" onClick={()=>{controller.current?.abort();void api('/api/coach/cancel','POST',{},me.csrf)}}>{t('stop')}</button>}</form>{answer&&<p className="coach-answer user-text" dir="auto">{answer}</p>}<div className="button-row"><button onClick={()=>void work(async()=>downloadJSON(await api('/api/coach/history'),'POK-coach-history.json'))}>{t('exportAccount')}</button><button onClick={()=>void work(async()=>{await api('/api/coach/history','DELETE',{},me.csrf);setAnswer('')})}>{t('deleteChat')}</button></div></section>
}
function ControlPanel({locale,me,work}:{locale:Locale;me:Member;work:Work}){
 const t=(k:string)=>tr(locale,`platform.${k}`),{appearance}=useAppearance(),[section,setSection]=useState(me.user.role==='moderator'?'reports':me.user.role==='editor'?'questions':'feedback'),[items,setItems]=useState<any[]>([]),[query,setQuery]=useState(''),[offset,setOffset]=useState(0),[target,setTarget]=useState(''),[kind,setKind]=useState('warn'),[reason,setReason]=useState(''),[hours,setHours]=useState(24),[evidence,setEvidence]=useState(''),[sanction,setSanction]=useState(''),[response,setResponse]=useState(''),[selected,setSelected]=useState<any>(null),[entries,setEntries]=useState('[]'),[samples,setSamples]=useState(''),[preview,setPreview]=useState<any>(null),[newRole,setNewRole]=useState('member');
 const sections=me.user.role==='support'?['feedback']:me.user.role==='editor'?['questions','languages','dictionary']:me.user.role==='moderator'?['reports','chat','questions','dictionary','appeals']:['users','reports','chat','questions','feedback','languages','appearance','providers','ai','audit','dictionary','appeals'];
 if(me.user.role==='owner')sections.push('engines');
 async function load(){const r=await api(section==='engines'?'/api/strategy/admin/health':section==='ai'?'/api/coach/admin/usage':`/api/admin/${section}?q=${encodeURIComponent(query)}&offset=${offset}`);setItems(r.items??r);if(section==='dictionary'&&r.items?.[0])setEntries(r.items[0].payload)}
 useEffect(()=>{void work(()=>load(),'')},[section,query,offset]);
 return <section className="panel"><h2>{t('control')}</h2><label>{t('control')}<select value={section} onChange={e=>{setSection(e.target.value);setOffset(0);setSelected(null)}}>{sections.map(s=><option key={s} value={s}>{s==='engines'?'Strategy engine health':t(s==='appearance'?'defaults':s==='ai'?'usage':s)}</option>)}</select></label><label>{t('search')}<input value={query} onChange={e=>setQuery(e.target.value)}/></label><button onClick={()=>void work(()=>load(),'')}>{t('refresh')}</button>
 {section==='languages'?<div>{supportedLocales.map(c=><p key={c}>{getLocaleMetadata(c).nativeName} · {t('draftTranslation')}</p>)}</div>:section==='appearance'?<button onClick={()=>void work(()=>api('/api/admin/appearance','PUT',{defaults:appearance,reason:'Set current reviewed appearance as default'},me.csrf))}>{t('save')} · {t('defaults')}</button>:section==='dictionary'?<><p>{t('dictionaryHelp')}</p><details><summary>{t('dictionary')}</summary><label>JSON<textarea rows={12} value={entries} onChange={e=>{setEntries(e.target.value);setPreview(null)}}/></label></details><label>{t('samples')}<textarea value={samples} onChange={e=>{setSamples(e.target.value);setPreview(null)}}/></label><button onClick={()=>void work(async()=>setPreview(await api('/api/admin/dictionary/preview','POST',{entries:JSON.parse(entries),samples:samples.split('\n').filter(Boolean)},me.csrf)))}>{t('preview')}</button>{preview&&<><pre>{JSON.stringify(preview.results,null,2)}</pre><label>{t('reason')}<input value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={!reason} onClick={()=>void work(async()=>{await api('/api/admin/dictionary','POST',{entries:JSON.parse(entries),previewToken:preview.previewToken,reason},me.csrf);setPreview(null);await load()})}>{t('activate')}</button></>}{items.map(i=><p key={i.version}>v{i.version} · {i.active?'active':'inactive'} <button disabled={!reason} onClick={()=>void work(async()=>{await api('/api/admin/dictionary/rollback','POST',{version:i.version,reason},me.csrf);await load()})}>{t('rollback')}</button></p>)}</>:<div className="admin-list">{items.map((i,n)=><article className="community-item" key={i.id??n}><strong><bdi>{i.name??i.title??i.action??i.kind??i.day??i.id}</bdi></strong><p dir="auto">{i.body??i.reason??i.note??''}</p><details><summary>{tr(locale,'advanced')}</summary><pre>{JSON.stringify(i,null,2)}</pre></details>{section==='users'&&me.user.role==='owner'&&<button onClick={()=>setTarget(i.id)}>{t('role')}</button>}{['feedback','questions'].includes(section)&&<button onClick={()=>setSelected(i)}>{t('reply')}</button>}{['reports','chat'].includes(section)&&<button onClick={()=>{setTarget(i.author_id);setEvidence(i.content_id??i.id)}}>{t('apply')}</button>}{['chat','reports'].includes(section)&&<button disabled={!reason} onClick={()=>void work(async()=>{await api('/api/admin/content/'+(i.content_id??i.id),'PATCH',{hidden:!i.hidden,reason},me.csrf);await load()})}>{t(i.hidden?'restore':'hide')}</button>}</article>)}</div>}
 {section==='users'&&me.user.role==='owner'&&target&&<form onSubmit={e=>{e.preventDefault();void work(async()=>{await api('/api/admin/roles','POST',{targetId:target,role:newRole,reason},me.csrf);await load()})}}><p><bdi>{target}</bdi></p><label>{t('role')}<select value={newRole} onChange={e=>setNewRole(e.target.value)}>{['owner','administrator','moderator','support','editor','member'].map(r=><option value={r} key={r}>{r}</option>)}</select></label><label>{t('reason')}<input required value={reason} onChange={e=>setReason(e.target.value)}/></label><button>{t('apply')}</button></form>}
 {selected&&<form onSubmit={e=>{e.preventDefault();void work(async()=>{await api('/api/content','POST',{kind:section==='feedback'?'feedback-reply':'answer',parentId:selected.id,body:response},me.csrf);setResponse('');setSelected(null);await load()})}}><h3>{selected.title}</h3><label>{t('reply')}<textarea required value={response} maxLength={2000} onChange={e=>setResponse(e.target.value)}/></label><button>{t('send')}</button><button type="button" onClick={()=>void work(()=>api('/api/content/'+selected.id+'/resolve','POST',{},me.csrf))}>{t('resolve')}</button></form>}
 {['users','reports','chat','appeals'].includes(section)&&<details open={!!target}><summary>{t('apply')}</summary><form onSubmit={e=>{e.preventDefault();void work(async()=>{await api('/api/admin/sanctions','POST',{targetId:target,kind,reason,evidenceId:evidence||undefined,sanctionId:sanction||undefined,expiresAt:Date.now()+hours*3600000},me.csrf);await load()})}}><label>{t('target')}<input required value={target} onChange={e=>setTarget(e.target.value)}/></label><label>{t('apply')}<select value={kind} onChange={e=>setKind(e.target.value)}>{['warn','mute','suspend','ban','revoke'].map(k=><option key={k} value={k}>{t(k==='revoke'?'revokeSanction':k)}</option>)}</select></label><label>{t('reason')}<input required maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label><label>{t('evidence')}<input value={evidence} onChange={e=>setEvidence(e.target.value)}/></label>{['mute','suspend'].includes(kind)&&<label>{t('duration')}<input type="number" min={1} max={720} value={hours} onChange={e=>setHours(+e.target.value)}/></label>}{kind==='revoke'&&<label>Case ID<input required value={sanction} onChange={e=>setSanction(e.target.value)}/></label>}<button>{t('apply')}</button></form></details>}
 {section==='ai'&&<button className="danger" onClick={()=>void work(()=>api('/api/coach/admin/disable','POST',{reason:'Operator emergency disable'},me.csrf))}>{t('stop')}</button>}<div className="button-row"><button disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-50))}>←</button><button disabled={items.length<50} onClick={()=>setOffset(offset+50)}>{t('older')}</button></div></section>
}
