import {useEffect,useRef,useState} from 'react';
import {onBackground} from './lifecycle';
import {SelfCountry} from './CountryBadge';
import {act,legalActions,observe,buildPots,type HandState,type Action} from './game';
import {chooseBotAction,BOT_PROFILES} from './bots';
import {expandRange} from './ranges';
import {cardText} from './cards';
import {handCategory,evaluate} from './evaluator';
import {AnalysisClient} from './analysis-client';
import type {EquityResult,EquityRequest} from './equity';
import {t,type Locale} from './i18n';
import {Cards,Card,EquityView,words,pct} from './components';
import type {Settings,StudyScenario} from './storage';

export function Table({hand,reveal=false,locale}:{hand:HandState;reveal?:boolean;locale:Locale}){
  return <div className={`poker-table seats-${hand.seats.length}`} data-testid="poker-table">
    <div className="table-felt"><div className="felt-brand">POK<span>POKER ODDS KNOWLEDGE</span></div></div>
    <div className="board-area"><span className="street-badge">{hand.street==='complete'?'SHOWDOWN / REVIEW':hand.street.toUpperCase()}</span><div className="board-cards">{Array.from({length:5},(_,i)=>hand.board[i]!==undefined?<Card key={i} card={hand.board[i]}/>:<span className="card-slot" key={i}/>)}</div><div className="pot-pill">{t(locale,'pot')} <b>{hand.seats.reduce((n,s)=>n+s.totalBet,0)}</b> <small>{t(locale,'chips')}</small></div></div>
    {hand.seats.map((seat,i)=>{const positions=hand.seats.length===2?[{left:50,top:91},{left:50,top:8}]:Array.from({length:hand.seats.length},(_,j)=>{const angle=Math.PI/2+j*2*Math.PI/hand.seats.length;return {left:50+44*Math.cos(angle),top:50+43*Math.sin(angle)}});const p=positions[i];const shown=i===0||reveal||(hand.result?.reason==='showdown'&&!seat.folded);return <div className={`seat ${hand.turn===i?'active':''} ${seat.folded?'folded':''} ${i===0?'hero':''}`} style={{left:`${p.left}%`,top:`${p.top}%`}} key={i} data-testid={`seat-${i}`}>
      <div className="seat-cards"><Cards cards={seat.hole} hidden={!shown} small/></div><div className="seat-info"><div><b>{i===0?t(locale,'hero'):`BOT · ${seat.name}`} </b>{i===0&&<SelfCountry locale={locale}/>} {hand.button===i&&<span className="dealer" title={t(locale,'dealer')}>D</span>}</div><strong>{seat.stack.toLocaleString()}<small> {t(locale,'chips')}</small></strong><span>{seat.folded?words(locale,'Folded / sitting out','Fold / fără jetoane'):seat.stack===0?'ALL-IN':hand.turn===i?words(locale,'● To act','● La acțiune'):i===0?words(locale,'Your information set','Informațiile tale'):BOT_PROFILES[(i-1)%3].name}</span></div>{seat.streetBet>0&&<span className="seat-bet">● {seat.streetBet}</span>}</div>})}
  </div>
}
function publicRequest(hand:HandState,revealed=false):EquityRequest{
  const hero=observe(hand,0),opponents=hero.seats.filter(s=>s.id!==0&&!s.folded);const ids=[0,...opponents.map(s=>s.id)];
  return {hero:hero.hole,board:hero.board,opponents:opponents.map(s=>revealed?{hand:hand.seats[s.id].hole}:{range:expandRange('random')}),samples:10000,seed:24680,method:'auto',pots:buildPots(hand).filter(p=>p.eligible.length>0).map((p,i)=>({id:`Pot ${i+1}`,amount:p.amount,eligible:p.eligible.map(id=>ids.indexOf(id)).filter(id=>id>=0)}))};
}
export default function Play({hand,settings,busy,onAction,onStart,onNext,onReview,onBranch}:{hand:HandState|null;settings:Settings;busy:boolean;onAction:(action:Action,revision:number)=>Promise<void>;onStart:()=>void;onNext:()=>void;onReview:()=>void;onBranch:(s:StudyScenario)=>void}){
  const locale=settings.locale;const [paused,setPaused]=useState(false),[stepToken,setStepToken]=useState(0),[teaching,setTeaching]=useState(false),[revealedCalc,setRevealedCalc]=useState(false),[guess,setGuess]=useState(''),[raiseTo,setRaiseTo]=useState(20);
  const [calculating,setCalculating]=useState(false),[botThinking,setBotThinking]=useState(false),[equity,setEquity]=useState<EquityResult|null>(null),[error,setError]=useState(''),[progress,setProgress]=useState(0);
  const client=useRef(new AnalysisClient()); const calcGeneration=useRef(0); const stepped=useRef(0);const callback=useRef(onAction);callback.current=onAction;
  useEffect(()=>onBackground(()=>{calcGeneration.current++;client.current.cancel();setCalculating(false);setPaused(true);setBotThinking(false)}),[]);
  const legal=hand?legalActions(hand):null,heroTurn=hand?.turn===0;const pot=hand?.seats.reduce((n,s)=>n+s.totalBet,0)??0;const call=hand?observe(hand,0).callAmount:0;const threshold=call/(pot+call||1);const live=hand?.seats.filter(s=>!s.folded).length??0;
  useEffect(()=>{calcGeneration.current++;client.current.cancel();setCalculating(false);setEquity(null);setError('');setRevealedCalc(false);setGuess('');if(hand){const l=legalActions(hand);setRaiseTo(Math.min(l.minRaiseTo,l.maxRaiseTo))}},[hand?.id,hand?.revision]);
  useEffect(()=>{
    if(!hand||hand.turn===null||hand.turn===0||hand.result||busy)return;
    if(paused&&stepToken===stepped.current)return;stepped.current=stepToken;
    let active=true;const snapshot=hand;const actor=hand.turn;const observation=observe(snapshot,actor);const policySeed=hash(`${hand.id}:${hand.revision}:policy`);
    const timer=setTimeout(async()=>{
      setBotThinking(true);try{
        const req:EquityRequest={hero:observation.hole,board:observation.board,opponents:observation.seats.filter(s=>!s.folded&&s.id!==actor).map(s=>({range:expandRange(observation.actions.some(a=>a.seat===s.id&&a.action.type==='raise')?'77+,AJs+,KQs,AQo+':'random')})),method:'monte-carlo',samples:300,seed:(policySeed^0x654321)>>>0};
        let estimate:number|undefined;try{estimate=(await client.current.run(req)).equity}catch{ /* Explicit heuristic fallback when a declared narrow model is incompatible. */ }
        if(active)await callback.current(chooseBotAction(observation,BOT_PROFILES[(actor-1)%3].id,policySeed,estimate),snapshot.revision);
      }catch(e){if(active)setError((e as Error).message)}finally{if(active)setBotThinking(false)}
    },settings.reducedMotion?0:settings.speed);
    return()=>{active=false;clearTimeout(timer);client.current.cancel();setBotThinking(false)};
  },[hand?.id,hand?.revision,paused,stepToken,busy,settings.speed,settings.reducedMotion]);
  useEffect(()=>()=>{calcGeneration.current++;client.current.cancel()},[]);
  async function calculate(revealed=false){if(!hand)return;const generation=++calcGeneration.current;setError('');setEquity(null);setCalculating(true);setProgress(0);try{const result=await client.current.run(publicRequest(hand,revealed),(n)=>{if(generation===calcGeneration.current)setProgress(n)});if(generation===calcGeneration.current)setEquity(result)}catch(e){if(generation===calcGeneration.current)setError((e as Error).message)}finally{if(generation===calcGeneration.current)setCalculating(false)}}
  function branch(){if(!hand)return;const o=observe(hand,0);onBranch({id:crypto.randomUUID(),title:`Hand study · ${hand.street}`,hero:o.hole.map(cardText).join(' '),board:o.board.map(cardText).join(' '),dead:'',opponents:o.seats.filter(s=>s.id!==0&&!s.folded).map(()=> 'random'),origin:words(locale,'Fork from the decision information set. Hidden cards are excluded; opponent ranges are editable assumptions.','Ramură din informațiile deciziei. Cărțile ascunse sunt excluse; intervalele sunt ipoteze editabile.')})}
  if(!hand)return <section className="panel welcome-table"><div className="welcome-cards"><Card card={51}/><Card card={46}/><Card card={41}/></div><span className="eyebrow">{words(locale,'YOUR LOCAL POKER WORKSHOP','ATELIERUL TĂU LOCAL DE POKER')}</span><h1>{words(locale,'Every hand is a chance\nto understand.','Fiecare mână este o șansă\nsă înțelegi.')}</h1><p>{t(locale,'welcomeBody')}</p><button className="primary large" onClick={onStart}>{t(locale,'newHand')} →</button><p className="muted">{settings.seats} seats · {settings.smallBlind}/{settings.bigBlind} blinds · {settings.stack} play chips · No rake</p></section>;
  return <div className="play-layout"><div className="table-column"><div className="table-toolbar"><div><span className="badge">{hand.seats.length}-MAX · NO-LIMIT HOLD'EM</span><span className="muted"> {hand.smallBlind}/{hand.bigBlind}</span></div><div className="button-row compact"><button onClick={()=>setPaused(p=>!p)}>{paused?t(locale,'resume'):t(locale,'pause')}</button><button disabled={!paused||heroTurn||!!hand.result||botThinking||busy} onClick={()=>setStepToken(n=>n+1)}>{t(locale,'step')}</button></div></div>
    {teaching&&<div className="teaching-banner">◉ {t(locale,'teaching')} · {words(locale,'Bots still see only their own cards.','Boții văd în continuare numai cărțile proprii.')}</div>}
    <Table hand={hand} reveal={teaching} locale={locale}/>
    <div className="action-panel" data-testid="action-panel"><div className="action-caption" aria-live="polite"><b>{hand.result?hand.result.summary:heroTurn?words(locale,'Your decision','Decizia ta'):paused?words(locale,'Paused · step through opponent decisions','Pauză · avansează deciziile adversarilor'):words(locale,'Opponent thinking…','Adversarul se gândește…')}</b>{heroTurn&&<span>{call?`${t(locale,'call')} ${call}`:words(locale,'You can check','Poți spune pas')} · {t(locale,'stack')} {hand.seats[0].stack}</span>}</div>
      {hand.result?<div className="button-row"><button className="primary" onClick={onNext} disabled={busy}>{t(locale,'nextHand')}</button><button onClick={onReview}>{t(locale,'review')} →</button><button onClick={onStart}>{words(locale,'Reset training stacks','Resetează stack-urile')}</button></div>:<div className="action-controls"><button disabled={!heroTurn||busy} onClick={()=>onAction({type:'fold'},hand.revision)}>{t(locale,'fold')}</button><button className="primary" disabled={!heroTurn||busy} onClick={()=>onAction({type:legal!.canCheck?'check':'call'},hand.revision)}>{legal?.canCheck?t(locale,'check'):`${t(locale,'call')} ${heroTurn?legal?.callAmount:call}`}</button><div className="raise-control"><label>{t(locale,'raiseTo')}<input aria-label="Raise TO" type="number" min={legal?.shortAllInOnly?legal.maxRaiseTo:legal?.minRaiseTo} max={legal?.maxRaiseTo} step="1" value={raiseTo} disabled={!heroTurn||!legal?.canRaise||busy} onChange={e=>setRaiseTo(+e.target.value)}/></label><button disabled={!heroTurn||!legal?.canRaise||busy||!Number.isInteger(raiseTo)||raiseTo>legal.maxRaiseTo||(raiseTo<legal.minRaiseTo&&raiseTo!==legal.maxRaiseTo)} onClick={()=>onAction({type:'raise',to:raiseTo},hand.revision)}>{legal?.currentBet===0?t(locale,'bet'):t(locale,'raise')}</button></div><button disabled={!heroTurn||busy||(!legal?.canRaise&&legal?.callAmount!==hand.seats[0].stack)} onClick={()=>onAction(legal!.canRaise?{type:'raise',to:legal!.maxRaiseTo}:{type:'call'},hand.revision)}>{t(locale,'allIn')}</button></div>}
      {heroTurn&&legal?.canRaise&&<p className="muted">{t(locale,'raiseTo')} {raiseTo} = {t(locale,'raiseBy')} {Math.max(0,raiseTo-hand.currentBet)} · {words(locale,'additional chips','jetoane suplimentare')} {Math.max(0,raiseTo-hand.seats[0].streetBet)}. {legal.shortAllInOnly?'Short all-in only.':`Minimum TO ${legal.minRaiseTo}.`}</p>}
    </div>
    <div className="table-footer"><label className="check-label"><input type="checkbox" checked={teaching} onChange={e=>{calcGeneration.current++;client.current.cancel();setCalculating(false);setTeaching(e.target.checked);setEquity(null)}}/>{words(locale,'Reveal all for teaching','Dezvăluie tot pentru studiu')}</label><span>{words(locale,'Play chips only · independent local opponents','Doar jetoane de joc · adversari locali')}</span></div>
    {hand.result&&<div className="panel results"><h3>{words(locale,'Pot settlement','Împărțirea poturilor')}</h3>{hand.pots.map((p,i)=><p key={i}><b>{i===0?'Main pot':`Side pot ${i}`} · {p.amount}</b> → {p.shares.map(s=>`${hand.seats[s.seat].name}: ${s.amount}`).join(' / ')}</p>)}{hand.returned.map((r,i)=><p key={i}>{words(locale,'Uncalled returned','Pariu neplătit returnat')}: {hand.seats[r.seat].name} +{r.amount}</p>)}{hand.result.reason==='showdown'&&hand.seats.filter(s=>!s.folded).map(s=><p key={s.id}>{s.name}: {handCategory(evaluate([...s.hole,...hand.board]))}</p>)}</div>}
  </div><aside className="panel decision-panel"><span className="eyebrow">{words(locale,'DECISION NOTEBOOK','CAIETUL DECIZIILOR')}</span><h2>{words(locale,'What price are\nyou being offered?','Ce preț\nți se oferă?')}</h2><p>{words(locale,'Learn the calculation before judging the outcome.','Învață calculul înainte să judeci rezultatul.')}</p><div className="math-givens"><div><span>P · {t(locale,'pot')}</span><b>{pot}</b></div><div><span>C · {t(locale,'call')}</span><b>{call}</b></div></div>
      {settings.mode==='practice'&&!hand.result?<p className="notice">{words(locale,'Practice mode: finish the hand, then revisit each original decision in Hand Review.','Mod practic: termină mâna, apoi revino la deciziile inițiale în Revizuire.')}</p>:<>{settings.mode==='guess'&&!revealedCalc&&<label>{words(locale,'Guess the single-pot threshold (%)','Estimează pragul pentru un singur pot (%)')}<input type="number" value={guess} onChange={e=>setGuess(e.target.value)}/></label>}<button className="text-button" disabled={settings.mode==='guess'&&guess.trim()===''} onClick={()=>setRevealedCalc(r=>!r)}>{revealedCalc?t(locale,'hide'):t(locale,'reveal')} {revealedCalc?'−':'+'}</button>{revealedCalc&&<div className="worked" data-testid="worked-calculation"><div className="formula">C / (P + C)</div><h3>{call} / ({pot} + {call}) = {pct(threshold)}</h3><p>{t(locale,'potOddsHelp')}</p>{settings.mode==='guess'&&<p>{Math.abs(Number(guess)-threshold*100)<=.5?t(locale,'correct'):t(locale,'tryAgain')}</p>}<p className="notice">{words(locale,'This is a heads-up, single eligible pot, no-rake terminal-call model. With future betting or side pots, this threshold alone does not grade your action.','Model pentru doi jucători, un singur pot eligibil, fără rake sau pariuri viitoare. Pragul singur nu evaluează acțiunea când există pariuri viitoare sau poturi laterale.')}</p><p>EV(call) = E × ({pot} + {call}) − {call}</p>{equity&&live===2&&call>0&&buildPots(hand).length===1&&!hand.seats[0].folded&&<p>{words(locale,'At the estimated share','La partea estimată')}: {(equity.equity*(pot+call)-call).toFixed(1)} {t(locale,'chips')} ({words(locale,'terminal model only','doar model terminal')})</p>}</div>}</>}
      {(settings.mode!=='practice'||hand.result)&&!hand.seats[0].folded&&live>1&&<div className="analysis-block"><h3>{t(locale,'rangeBased')}</h3><p className="muted">{words(locale,'Assume all legal hands for each opponent; checkdown, no future betting. Known cards = yours + public board only. Current pot layers reported separately.','Presupune toate mâinile legale pentru fiecare adversar; fără pariuri viitoare. Cărți cunoscute = ale tale + board. Poturile curente sunt separate.')}</p><div className="button-row"><button disabled={calculating||(!heroTurn&&!hand.result&&!paused)||botThinking} onClick={()=>calculate(false)}>{calculating?`${progress}…`:words(locale,'Estimate equity','Estimează echitatea')}</button>{teaching&&<button disabled={calculating||(!heroTurn&&!hand.result&&!paused)||botThinking} onClick={()=>calculate(true)}>{t(locale,'revealedEquity')}</button>}<button onClick={branch}>{words(locale,'Edit ranges →','Editează intervalele →')}</button></div>{calculating&&<button onClick={()=>{calcGeneration.current++;client.current.cancel();setCalculating(false)}}>{t(locale,'stop')}</button>}{equity&&<><h3>{t(locale,equity.inputs.opponents.every(o=>!!o.hand)?'revealedEquity':'rangeBased')}</h3><EquityView result={equity} locale={locale}/></>}</div>}
      {error&&<p className="error" role="alert">{error}</p>}<details><summary>{words(locale,'Opponent model & limits','Modelul adversarilor și limite')}</summary><p>{t(locale,'heuristicHelp')}</p><p>{words(locale,'Bots use 300 sampled outcomes against declared ranges: tight educational ranges for observed raisers, otherwise all hands. Failed range samples fall back to labelled hand/texture heuristics. Their random policy stream is independent of dealing.','Boții folosesc 300 de rezultate eșantionate cu intervale didactice strânse pentru cei care au mărit, altfel toate mâinile. La eșec folosesc euristici de textură. Aleatorul politicii este independent de împărțirea cărților.')}</p></details>
    </aside></div>
}
function hash(text:string){let h=2166136261;for(const c of text){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}




