import {useMemo,useState} from 'react';
import {createHand,act,observe,replayHand,type HandState} from './game';
import {cardText} from './cards';
import {Table} from './Play';
import {t,type Locale} from './i18n';
import {words,pct} from './components';
import type {StudyScenario} from './storage';

export function sidePotLesson():HandState{let h=createHand({id:'side-pot-lesson-v1',seats:[{name:'You',stack:100},{name:'Mira',stack:200},{name:'Alex',stack:300}],button:0,smallBlind:5,bigBlind:10,seed:2026});h=act(h,{type:'raise',to:100});h=act(h,{type:'raise',to:200});h=act(h,{type:'call'});return h;}
export default function Review({hands,locale,onBranch,onFork,onDemo}:{hands:HandState[];locale:Locale;onBranch:(s:StudyScenario)=>void;onFork:(h:HandState)=>void;onDemo:()=>void}){
  const [selected,setSelected]=useState(hands.at(-1)?.id??''),[revision,setRevision]=useState(0),[reveal,setReveal]=useState(false);
  const original=hands.find(h=>h.id===selected)??hands.at(-1);const state=useMemo(()=>original?replayHand(original,Math.min(revision,original.revision)):null,[original,revision]);
  function branch(){if(!state)return;const o=observe(state,0);onBranch({id:crypto.randomUUID(),title:`Review branch · action ${state.revision}`,hero:o.hole.map(cardText).join(' '),board:o.board.map(cardText).join(' '),dead:'',opponents:o.seats.filter(s=>!s.folded&&s.id!==0).map(()=> 'random'),origin:words(locale,`Forked from ${original!.id}, decision ${state.revision}. Original history is preserved; only cards known then are used.`,`Ramificat din ${original!.id}, decizia ${state.revision}. Istoricul original este păstrat; se folosesc doar cărțile cunoscute atunci.`)})}
  return <div className="review-layout"><section className="panel"><div className="section-heading"><div><span className="eyebrow">{words(locale,'REPLAY & REFLECT','REIA ȘI REFLECTEAZĂ')}</span><h2>{t(locale,'review')}</h2></div><button onClick={onDemo}>{words(locale,'Load side-pot lesson','Încarcă lecția de poturi laterale')}</button></div><p>{words(locale,'Review what you knew, not what the river later revealed. Branches never overwrite the original hand.','Revizuiește ce știai, nu ce a dezvăluit riverul mai târziu. Ramurile nu suprascriu mâna originală.')}</p>
    {!original?<p className="empty">{t(locale,'noHistory')}</p>:<><label>{words(locale,'Saved hand','Mână salvată')}<select aria-label="Saved hand" value={original.id} onChange={e=>{setSelected(e.target.value);setRevision(0);setReveal(false)}}>{[...hands].reverse().map((h,i)=><option key={h.id} value={h.id}>{hands.length-i} · {h.seats.length} seats · {h.id.startsWith('side-pot')?'Side-pot lesson':h.result?.summary??'Branch'}</option>)}</select></label><Table hand={state!} reveal={reveal} locale={locale}/><div className="replay-controls"><button onClick={()=>setRevision(0)}>{t(locale,'replay')} ↤</button><button disabled={revision===0} onClick={()=>setRevision(n=>n-1)}>←</button><input aria-label="Replay action" type="range" min="0" max={original.revision} value={Math.min(revision,original.revision)} onChange={e=>setRevision(+e.target.value)}/><button aria-label="Next replay action" disabled={revision>=original.revision} onClick={()=>setRevision(n=>n+1)}>→</button><span>{revision}/{original.revision}</span></div><div className="button-row"><label className="check-label"><input type="checkbox" checked={reveal} onChange={e=>setReveal(e.target.checked)}/>{words(locale,'Reveal completed-hand cards','Dezvăluie cărțile mâinii încheiate')}</label><button disabled={!state||state.seats[0].hole.length!==2||state.seats.filter(s=>!s.folded&&s.id!==0).length===0} onClick={branch}>{t(locale,'branch')}</button><button disabled={!!state?.result} onClick={()=>onFork(state!)}>{words(locale,'Play an alternate branch','Joacă o ramură alternativă')}</button></div></>}
  </section>{state&&<aside className="panel review-notes"><span className="eyebrow">{words(locale,'ORIGINAL INFORMATION SET','INFORMAȚIILE ORIGINALE')}</span><h2>{words(locale,'Before action','Înainte de acțiunea')} {Math.min(state.revision+1,original!.revision)}</h2><p>{state.turn===null?words(locale,'Hand complete','Mână încheiată'):("Actor: " + state.seats[state.turn].name)}</p><p>{words(locale,'Public board and your own cards only. Any revealed future or opponent cards are review information, not grading inputs.','Doar boardul public și cărțile proprii. Cărțile viitoare sau ale adversarilor dezvăluite sunt pentru revizuire, nu pentru evaluare.')}</p><div className="worked"><p>P = {observe(state,0).pot}, C = {observe(state,0).callAmount}</p><h3>C / (P+C) = {pct(observe(state,0).callAmount/(observe(state,0).pot+observe(state,0).callAmount||1))}</h3><p>{t(locale,'potOddsHelp')}</p><p>{words(locale,'Single eligible terminal pot assumption. Strategic decisions remain heuristic; later wins/losses do not alter this calculation.','Ipoteză: un singur pot eligibil, fără decizii ulterioare. Strategia rămâne euristică; rezultatul ulterior nu schimbă calculul.')}</p></div><h3>{words(locale,'Action timeline','Cronologia acțiunilor')}</h3><ol className="timeline">{original!.log.map(entry=><li key={entry.revision} className={entry.revision===revision+1?'selected':''}><button onClick={()=>setRevision(entry.revision-1)}><small>{entry.street}</small><span>{original!.seats[entry.seat].name} · {entry.action.type}{entry.action.to!==undefined?` TO ${entry.action.to}`:''}</span></button></li>)}</ol>{state.result&&<><h3>{words(locale,'Pot settlement','Împărțirea poturilor')}</h3>{state.pots.map((p,i)=><p key={i}>{i===0?'Main':'Side'} {i+1}: {p.amount} → {p.shares.map(s=>`${state.seats[s.seat].name} ${s.amount}`).join(', ')}</p>)}</>}</aside>}</div>
}


